// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comms.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const answerClarification = `-- name: AnswerClarification :one
UPDATE clarifications SET
  answer = $2,
  is_public = $3,
  status = 'answered',
  answered_by = $4,
  answered_at = now(),
  updated_at = now()
WHERE id = $1
RETURNING id, contest_id, task_id, phase_id, contest_entry_id, question, answer, is_public, status, asked_by, answered_by, answered_at, created_at, updated_at
`

type AnswerClarificationParams struct {
	ID         uuid.UUID   `json:"id"`
	Answer     *string     `json:"answer"`
	IsPublic   bool        `json:"is_public"`
	AnsweredBy pgtype.UUID `json:"answered_by"`
}

func (q *Queries) AnswerClarification(ctx context.Context, arg AnswerClarificationParams) (Clarification, error) {
	row := q.db.QueryRow(ctx, answerClarification,
		arg.ID,
		arg.Answer,
		arg.IsPublic,
		arg.AnsweredBy,
	)
	var i Clarification
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.TaskID,
		&i.PhaseID,
		&i.ContestEntryID,
		&i.Question,
		&i.Answer,
		&i.IsPublic,
		&i.Status,
		&i.AskedBy,
		&i.AnsweredBy,
		&i.AnsweredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAnnouncement = `-- name: CreateAnnouncement :one

INSERT INTO announcements (contest_id, task_id, title, content, is_pinned, is_public, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, contest_id, task_id, title, content, is_pinned, is_public, created_by, created_at, updated_at
`

type CreateAnnouncementParams struct {
	ContestID pgtype.UUID `json:"contest_id"`
	TaskID    pgtype.UUID `json:"task_id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	IsPinned  bool        `json:"is_pinned"`
	IsPublic  bool        `json:"is_public"`
	CreatedBy uuid.UUID   `json:"created_by"`
}

// Announcements
func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.ContestID,
		arg.TaskID,
		arg.Title,
		arg.Content,
		arg.IsPinned,
		arg.IsPublic,
		arg.CreatedBy,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.TaskID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.IsPublic,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClarification = `-- name: CreateClarification :one

INSERT INTO clarifications (contest_id, task_id, phase_id, contest_entry_id, question, asked_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, contest_id, task_id, phase_id, contest_entry_id, question, answer, is_public, status, asked_by, answered_by, answered_at, created_at, updated_at
`

type CreateClarificationParams struct {
	ContestID      uuid.UUID   `json:"contest_id"`
	TaskID         pgtype.UUID `json:"task_id"`
	PhaseID        pgtype.UUID `json:"phase_id"`
	ContestEntryID uuid.UUID   `json:"contest_entry_id"`
	Question       string      `json:"question"`
	AskedBy        uuid.UUID   `json:"asked_by"`
}

// Clarifications
func (q *Queries) CreateClarification(ctx context.Context, arg CreateClarificationParams) (Clarification, error) {
	row := q.db.QueryRow(ctx, createClarification,
		arg.ContestID,
		arg.TaskID,
		arg.PhaseID,
		arg.ContestEntryID,
		arg.Question,
		arg.AskedBy,
	)
	var i Clarification
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.TaskID,
		&i.PhaseID,
		&i.ContestEntryID,
		&i.Question,
		&i.Answer,
		&i.IsPublic,
		&i.Status,
		&i.AskedBy,
		&i.AnsweredBy,
		&i.AnsweredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicket = `-- name: CreateTicket :one

INSERT INTO tickets (submission_id, contest_entry_id, category, subject, description, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, submission_id, contest_entry_id, category, subject, description, status, priority, assigned_to, created_by, created_at, resolved_at, updated_at
`

type CreateTicketParams struct {
	SubmissionID   pgtype.UUID    `json:"submission_id"`
	ContestEntryID uuid.UUID      `json:"contest_entry_id"`
	Category       TicketCategory `json:"category"`
	Subject        string         `json:"subject"`
	Description    string         `json:"description"`
	CreatedBy      uuid.UUID      `json:"created_by"`
}

// Tickets
func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.SubmissionID,
		arg.ContestEntryID,
		arg.Category,
		arg.Subject,
		arg.Description,
		arg.CreatedBy,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.ContestEntryID,
		&i.Category,
		&i.Subject,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :exec
DELETE FROM announcements WHERE id = $1
`

func (q *Queries) DeleteAnnouncement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnnouncement, id)
	return err
}

const getClarificationByID = `-- name: GetClarificationByID :one
SELECT id, contest_id, task_id, phase_id, contest_entry_id, question, answer, is_public, status, asked_by, answered_by, answered_at, created_at, updated_at FROM clarifications WHERE id = $1
`

func (q *Queries) GetClarificationByID(ctx context.Context, id uuid.UUID) (Clarification, error) {
	row := q.db.QueryRow(ctx, getClarificationByID, id)
	var i Clarification
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.TaskID,
		&i.PhaseID,
		&i.ContestEntryID,
		&i.Question,
		&i.Answer,
		&i.IsPublic,
		&i.Status,
		&i.AskedBy,
		&i.AnsweredBy,
		&i.AnsweredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnnouncementsByContest = `-- name: ListAnnouncementsByContest :many
SELECT id, contest_id, task_id, title, content, is_pinned, is_public, created_by, created_at, updated_at FROM announcements WHERE contest_id = $1 ORDER BY is_pinned DESC, created_at DESC
`

func (q *Queries) ListAnnouncementsByContest(ctx context.Context, contestID pgtype.UUID) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncementsByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Announcement
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.TaskID,
			&i.Title,
			&i.Content,
			&i.IsPinned,
			&i.IsPublic,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClarificationsByContest = `-- name: ListClarificationsByContest :many
SELECT id, contest_id, task_id, phase_id, contest_entry_id, question, answer, is_public, status, asked_by, answered_by, answered_at, created_at, updated_at FROM clarifications
WHERE contest_id = $1
  AND ($2::clarification_status IS NULL OR status = $2)
  AND (
    $3::boolean
    OR asked_by = $4::uuid
    OR is_public = true
  )
ORDER BY created_at DESC
`

type ListClarificationsByContestParams struct {
	ContestID  uuid.UUID            `json:"contest_id"`
	Status     *ClarificationStatus `json:"status"`
	IncludeAll bool                 `json:"include_all"`
	ViewerID   uuid.UUID            `json:"viewer_id"`
}

func (q *Queries) ListClarificationsByContest(ctx context.Context, arg ListClarificationsByContestParams) ([]Clarification, error) {
	rows, err := q.db.Query(ctx, listClarificationsByContest,
		arg.ContestID,
		arg.Status,
		arg.IncludeAll,
		arg.ViewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Clarification
	for rows.Next() {
		var i Clarification
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.TaskID,
			&i.PhaseID,
			&i.ContestEntryID,
			&i.Question,
			&i.Answer,
			&i.IsPublic,
			&i.Status,
			&i.AskedBy,
			&i.AnsweredBy,
			&i.AnsweredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemAnnouncements = `-- name: ListSystemAnnouncements :many
SELECT id, contest_id, task_id, title, content, is_pinned, is_public, created_by, created_at, updated_at FROM announcements WHERE contest_id IS NULL ORDER BY is_pinned DESC, created_at DESC
`

func (q *Queries) ListSystemAnnouncements(ctx context.Context) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listSystemAnnouncements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Announcement
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.TaskID,
			&i.Title,
			&i.Content,
			&i.IsPinned,
			&i.IsPublic,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsAll = `-- name: ListTicketsAll :many
SELECT id, submission_id, contest_entry_id, category, subject, description, status, priority, assigned_to, created_by, created_at, resolved_at, updated_at FROM tickets
WHERE ($3::ticket_status IS NULL OR status = $3)
ORDER BY priority DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListTicketsAllParams struct {
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
	Status *TicketStatus `json:"status"`
}

func (q *Queries) ListTicketsAll(ctx context.Context, arg ListTicketsAllParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsAll, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.ContestEntryID,
			&i.Category,
			&i.Subject,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssignedTo,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByUser = `-- name: ListTicketsByUser :many
SELECT id, submission_id, contest_entry_id, category, subject, description, status, priority, assigned_to, created_by, created_at, resolved_at, updated_at FROM tickets WHERE created_by = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTicketsByUser(ctx context.Context, createdBy uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByUser, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.ContestEntryID,
			&i.Category,
			&i.Subject,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssignedTo,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveTicket = `-- name: ResolveTicket :one
UPDATE tickets SET status = 'resolved', resolved_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, submission_id, contest_entry_id, category, subject, description, status, priority, assigned_to, created_by, created_at, resolved_at, updated_at
`

func (q *Queries) ResolveTicket(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, resolveTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.ContestEntryID,
		&i.Category,
		&i.Subject,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
UPDATE announcements SET
  title = COALESCE($2, title),
  content = COALESCE($3, content),
  is_pinned = COALESCE($4, is_pinned),
  is_public = COALESCE($5, is_public),
  updated_at = now()
WHERE id = $1
RETURNING id, contest_id, task_id, title, content, is_pinned, is_public, created_by, created_at, updated_at
`

type UpdateAnnouncementParams struct {
	ID       uuid.UUID `json:"id"`
	Title    *string   `json:"title"`
	Content  *string   `json:"content"`
	IsPinned *bool     `json:"is_pinned"`
	IsPublic *bool     `json:"is_public"`
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, updateAnnouncement,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.IsPinned,
		arg.IsPublic,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.TaskID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.IsPublic,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClarificationStatus = `-- name: UpdateClarificationStatus :one
UPDATE clarifications SET
  is_public = COALESCE($2, is_public),
  status = COALESCE($3::clarification_status, status),
  updated_at = now()
WHERE id = $1
RETURNING id, contest_id, task_id, phase_id, contest_entry_id, question, answer, is_public, status, asked_by, answered_by, answered_at, created_at, updated_at
`

type UpdateClarificationStatusParams struct {
	ID       uuid.UUID            `json:"id"`
	IsPublic *bool                `json:"is_public"`
	Status   *ClarificationStatus `json:"status"`
}

func (q *Queries) UpdateClarificationStatus(ctx context.Context, arg UpdateClarificationStatusParams) (Clarification, error) {
	row := q.db.QueryRow(ctx, updateClarificationStatus, arg.ID, arg.IsPublic, arg.Status)
	var i Clarification
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.TaskID,
		&i.PhaseID,
		&i.ContestEntryID,
		&i.Question,
		&i.Answer,
		&i.IsPublic,
		&i.Status,
		&i.AskedBy,
		&i.AnsweredBy,
		&i.AnsweredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets SET
  status = COALESCE($2::ticket_status, status),
  priority = COALESCE($3::ticket_priority, priority),
  assigned_to = COALESCE($4, assigned_to),
  updated_at = now()
WHERE id = $1
RETURNING id, submission_id, contest_entry_id, category, subject, description, status, priority, assigned_to, created_by, created_at, resolved_at, updated_at
`

type UpdateTicketParams struct {
	ID         uuid.UUID       `json:"id"`
	Status     *TicketStatus   `json:"status"`
	Priority   *TicketPriority `json:"priority"`
	AssignedTo pgtype.UUID     `json:"assigned_to"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicket,
		arg.ID,
		arg.Status,
		arg.Priority,
		arg.AssignedTo,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.ContestEntryID,
		&i.Category,
		&i.Subject,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}
