// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contests.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContest = `-- name: CreateContest :one
INSERT INTO contests (
  slug, title, description, banner_url, status, entry_policy,
  registration_start, registration_end, start_time, end_time,
  visibility, rules_json, created_by, max_team_size, require_approval
) VALUES (
  $1, $2, $3, $4, 'draft', $5,
  $6, $7, $8, $9,
  $10, $11, $12, $13, $14
)
RETURNING id, slug, title, description, banner_url, status, entry_policy, registration_start, registration_end, start_time, end_time, visibility, rules_json, created_by, max_team_size, require_approval, created_at, updated_at
`

type CreateContestParams struct {
	Slug              string             `json:"slug"`
	Title             string             `json:"title"`
	Description       *string            `json:"description"`
	BannerUrl         *string            `json:"banner_url"`
	EntryPolicy       ContestEntryPolicy `json:"entry_policy"`
	RegistrationStart pgtype.Timestamptz `json:"registration_start"`
	RegistrationEnd   pgtype.Timestamptz `json:"registration_end"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	Visibility        ContestVisibility  `json:"visibility"`
	RulesJson         []byte             `json:"rules_json"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	MaxTeamSize       int32              `json:"max_team_size"`
	RequireApproval   bool               `json:"require_approval"`
}

func (q *Queries) CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error) {
	row := q.db.QueryRow(ctx, createContest,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.BannerUrl,
		arg.EntryPolicy,
		arg.RegistrationStart,
		arg.RegistrationEnd,
		arg.StartTime,
		arg.EndTime,
		arg.Visibility,
		arg.RulesJson,
		arg.CreatedBy,
		arg.MaxTeamSize,
		arg.RequireApproval,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.BannerUrl,
		&i.Status,
		&i.EntryPolicy,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.StartTime,
		&i.EndTime,
		&i.Visibility,
		&i.RulesJson,
		&i.CreatedBy,
		&i.MaxTeamSize,
		&i.RequireApproval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContest = `-- name: DeleteContest :exec
DELETE FROM contests WHERE id = $1
`

func (q *Queries) DeleteContest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteContest, id)
	return err
}

const getContestByID = `-- name: GetContestByID :one
SELECT id, slug, title, description, banner_url, status, entry_policy, registration_start, registration_end, start_time, end_time, visibility, rules_json, created_by, max_team_size, require_approval, created_at, updated_at FROM contests WHERE id = $1
`

func (q *Queries) GetContestByID(ctx context.Context, id uuid.UUID) (Contest, error) {
	row := q.db.QueryRow(ctx, getContestByID, id)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.BannerUrl,
		&i.Status,
		&i.EntryPolicy,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.StartTime,
		&i.EndTime,
		&i.Visibility,
		&i.RulesJson,
		&i.CreatedBy,
		&i.MaxTeamSize,
		&i.RequireApproval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContestBySlug = `-- name: GetContestBySlug :one
SELECT id, slug, title, description, banner_url, status, entry_policy, registration_start, registration_end, start_time, end_time, visibility, rules_json, created_by, max_team_size, require_approval, created_at, updated_at FROM contests WHERE slug = $1
`

func (q *Queries) GetContestBySlug(ctx context.Context, slug string) (Contest, error) {
	row := q.db.QueryRow(ctx, getContestBySlug, slug)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.BannerUrl,
		&i.Status,
		&i.EntryPolicy,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.StartTime,
		&i.EndTime,
		&i.Visibility,
		&i.RulesJson,
		&i.CreatedBy,
		&i.MaxTeamSize,
		&i.RequireApproval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContests = `-- name: ListContests :many
SELECT id, slug, title, description, banner_url, status, entry_policy, registration_start, registration_end, start_time, end_time, visibility, rules_json, created_by, max_team_size, require_approval, created_at, updated_at FROM contests
WHERE ($3::contest_status IS NULL OR status = $3)
ORDER BY start_time DESC
LIMIT $1 OFFSET $2
`

type ListContestsParams struct {
	Limit  int32          `json:"limit"`
	Offset int32          `json:"offset"`
	Status *ContestStatus `json:"status"`
}

func (q *Queries) ListContests(ctx context.Context, arg ListContestsParams) ([]Contest, error) {
	rows, err := q.db.Query(ctx, listContests, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contest
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.BannerUrl,
			&i.Status,
			&i.EntryPolicy,
			&i.RegistrationStart,
			&i.RegistrationEnd,
			&i.StartTime,
			&i.EndTime,
			&i.Visibility,
			&i.RulesJson,
			&i.CreatedBy,
			&i.MaxTeamSize,
			&i.RequireApproval,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContest = `-- name: UpdateContest :one
UPDATE contests SET
  title = COALESCE($2, title),
  description = COALESCE($3, description),
  banner_url = COALESCE($4, banner_url),
  entry_policy = COALESCE($5::contest_entry_policy, entry_policy),
  registration_start = COALESCE($6, registration_start),
  registration_end = COALESCE($7, registration_end),
  start_time = COALESCE($8, start_time),
  end_time = COALESCE($9, end_time),
  visibility = COALESCE($10::contest_visibility, visibility),
  rules_json = COALESCE($11, rules_json),
  max_team_size = COALESCE($12, max_team_size),
  require_approval = COALESCE($13, require_approval),
  updated_at = now()
WHERE id = $1
RETURNING id, slug, title, description, banner_url, status, entry_policy, registration_start, registration_end, start_time, end_time, visibility, rules_json, created_by, max_team_size, require_approval, created_at, updated_at
`

type UpdateContestParams struct {
	ID                uuid.UUID           `json:"id"`
	Title             *string             `json:"title"`
	Description       *string             `json:"description"`
	BannerUrl         *string             `json:"banner_url"`
	EntryPolicy       *ContestEntryPolicy `json:"entry_policy"`
	RegistrationStart pgtype.Timestamptz  `json:"registration_start"`
	RegistrationEnd   pgtype.Timestamptz  `json:"registration_end"`
	StartTime         pgtype.Timestamptz  `json:"start_time"`
	EndTime           pgtype.Timestamptz  `json:"end_time"`
	Visibility        *ContestVisibility  `json:"visibility"`
	RulesJson         []byte              `json:"rules_json"`
	MaxTeamSize       *int32              `json:"max_team_size"`
	RequireApproval   *bool               `json:"require_approval"`
}

func (q *Queries) UpdateContest(ctx context.Context, arg UpdateContestParams) (Contest, error) {
	row := q.db.QueryRow(ctx, updateContest,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.BannerUrl,
		arg.EntryPolicy,
		arg.RegistrationStart,
		arg.RegistrationEnd,
		arg.StartTime,
		arg.EndTime,
		arg.Visibility,
		arg.RulesJson,
		arg.MaxTeamSize,
		arg.RequireApproval,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.BannerUrl,
		&i.Status,
		&i.EntryPolicy,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.StartTime,
		&i.EndTime,
		&i.Visibility,
		&i.RulesJson,
		&i.CreatedBy,
		&i.MaxTeamSize,
		&i.RequireApproval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContestStatus = `-- name: UpdateContestStatus :one
UPDATE contests SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, slug, title, description, banner_url, status, entry_policy, registration_start, registration_end, start_time, end_time, visibility, rules_json, created_by, max_team_size, require_approval, created_at, updated_at
`

type UpdateContestStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status ContestStatus `json:"status"`
}

func (q *Queries) UpdateContestStatus(ctx context.Context, arg UpdateContestStatusParams) (Contest, error) {
	row := q.db.QueryRow(ctx, updateContestStatus, arg.ID, arg.Status)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.BannerUrl,
		&i.Status,
		&i.EntryPolicy,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.StartTime,
		&i.EndTime,
		&i.Visibility,
		&i.RulesJson,
		&i.CreatedBy,
		&i.MaxTeamSize,
		&i.RequireApproval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
