// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addEntryMember = `-- name: AddEntryMember :exec
INSERT INTO contest_entry_members (contest_entry_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (contest_entry_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddEntryMemberParams struct {
	ContestEntryID uuid.UUID       `json:"contest_entry_id"`
	UserID         uuid.UUID       `json:"user_id"`
	Role           EntryMemberRole `json:"role"`
}

func (q *Queries) AddEntryMember(ctx context.Context, arg AddEntryMemberParams) error {
	_, err := q.db.Exec(ctx, addEntryMember, arg.ContestEntryID, arg.UserID, arg.Role)
	return err
}

const approveContestEntry = `-- name: ApproveContestEntry :one
UPDATE contest_entries SET
  status = 'approved', approved_by = $2, approved_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, contest_id, entry_type, entry_mode, user_id, team_id, display_name, status, registered_by, approved_by, approved_at, start_at, end_at, created_at, updated_at
`

type ApproveContestEntryParams struct {
	ID         uuid.UUID   `json:"id"`
	ApprovedBy pgtype.UUID `json:"approved_by"`
}

func (q *Queries) ApproveContestEntry(ctx context.Context, arg ApproveContestEntryParams) (ContestEntry, error) {
	row := q.db.QueryRow(ctx, approveContestEntry, arg.ID, arg.ApprovedBy)
	var i ContestEntry
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.EntryType,
		&i.EntryMode,
		&i.UserID,
		&i.TeamID,
		&i.DisplayName,
		&i.Status,
		&i.RegisteredBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContestEntry = `-- name: CreateContestEntry :one
INSERT INTO contest_entries (
  contest_id, entry_type, entry_mode, user_id, team_id,
  display_name, status, registered_by, start_at, end_at
) VALUES ($1, $2, $3, $4, $5, $6, 'pending', $7, $8, $9)
RETURNING id, contest_id, entry_type, entry_mode, user_id, team_id, display_name, status, registered_by, approved_by, approved_at, start_at, end_at, created_at, updated_at
`

type CreateContestEntryParams struct {
	ContestID    uuid.UUID          `json:"contest_id"`
	EntryType    EntryType          `json:"entry_type"`
	EntryMode    EntryMode          `json:"entry_mode"`
	UserID       pgtype.UUID        `json:"user_id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	DisplayName  string             `json:"display_name"`
	RegisteredBy uuid.UUID          `json:"registered_by"`
	StartAt      pgtype.Timestamptz `json:"start_at"`
	EndAt        pgtype.Timestamptz `json:"end_at"`
}

func (q *Queries) CreateContestEntry(ctx context.Context, arg CreateContestEntryParams) (ContestEntry, error) {
	row := q.db.QueryRow(ctx, createContestEntry,
		arg.ContestID,
		arg.EntryType,
		arg.EntryMode,
		arg.UserID,
		arg.TeamID,
		arg.DisplayName,
		arg.RegisteredBy,
		arg.StartAt,
		arg.EndAt,
	)
	var i ContestEntry
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.EntryType,
		&i.EntryMode,
		&i.UserID,
		&i.TeamID,
		&i.DisplayName,
		&i.Status,
		&i.RegisteredBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContestEntry = `-- name: DeleteContestEntry :exec
DELETE FROM contest_entries WHERE id = $1
`

func (q *Queries) DeleteContestEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteContestEntry, id)
	return err
}

const disqualifyContestEntry = `-- name: DisqualifyContestEntry :one
UPDATE contest_entries SET status = 'disqualified', updated_at = now()
WHERE id = $1
RETURNING id, contest_id, entry_type, entry_mode, user_id, team_id, display_name, status, registered_by, approved_by, approved_at, start_at, end_at, created_at, updated_at
`

func (q *Queries) DisqualifyContestEntry(ctx context.Context, id uuid.UUID) (ContestEntry, error) {
	row := q.db.QueryRow(ctx, disqualifyContestEntry, id)
	var i ContestEntry
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.EntryType,
		&i.EntryMode,
		&i.UserID,
		&i.TeamID,
		&i.DisplayName,
		&i.Status,
		&i.RegisteredBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContestEntryByID = `-- name: GetContestEntryByID :one
SELECT id, contest_id, entry_type, entry_mode, user_id, team_id, display_name, status, registered_by, approved_by, approved_at, start_at, end_at, created_at, updated_at FROM contest_entries WHERE id = $1
`

func (q *Queries) GetContestEntryByID(ctx context.Context, id uuid.UUID) (ContestEntry, error) {
	row := q.db.QueryRow(ctx, getContestEntryByID, id)
	var i ContestEntry
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.EntryType,
		&i.EntryMode,
		&i.UserID,
		&i.TeamID,
		&i.DisplayName,
		&i.Status,
		&i.RegisteredBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContestEntries = `-- name: ListContestEntries :many
SELECT id, contest_id, entry_type, entry_mode, user_id, team_id, display_name, status, registered_by, approved_by, approved_at, start_at, end_at, created_at, updated_at FROM contest_entries
WHERE contest_id = $1
  AND ($4::entry_mode IS NULL OR entry_mode = $4)
  AND ($5::entry_status IS NULL OR status = $5)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListContestEntriesParams struct {
	ContestID uuid.UUID    `json:"contest_id"`
	Limit     int32        `json:"limit"`
	Offset    int32        `json:"offset"`
	EntryMode *EntryMode   `json:"entry_mode"`
	Status    *EntryStatus `json:"status"`
}

func (q *Queries) ListContestEntries(ctx context.Context, arg ListContestEntriesParams) ([]ContestEntry, error) {
	rows, err := q.db.Query(ctx, listContestEntries,
		arg.ContestID,
		arg.Limit,
		arg.Offset,
		arg.EntryMode,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContestEntry
	for rows.Next() {
		var i ContestEntry
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.EntryType,
			&i.EntryMode,
			&i.UserID,
			&i.TeamID,
			&i.DisplayName,
			&i.Status,
			&i.RegisteredBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryMembers = `-- name: ListEntryMembers :many
SELECT cem.contest_entry_id, cem.user_id, cem.role, cem.joined_at, u.email, u.full_name
FROM contest_entry_members cem
JOIN users u ON u.id = cem.user_id
WHERE cem.contest_entry_id = $1
ORDER BY cem.joined_at
`

type ListEntryMembersRow struct {
	ContestEntryID uuid.UUID          `json:"contest_entry_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Role           EntryMemberRole    `json:"role"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
	Email          string             `json:"email"`
	FullName       string             `json:"full_name"`
}

func (q *Queries) ListEntryMembers(ctx context.Context, contestEntryID uuid.UUID) ([]ListEntryMembersRow, error) {
	rows, err := q.db.Query(ctx, listEntryMembers, contestEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntryMembersRow
	for rows.Next() {
		var i ListEntryMembersRow
		if err := rows.Scan(
			&i.ContestEntryID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Email,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeEntryMember = `-- name: RemoveEntryMember :exec
DELETE FROM contest_entry_members WHERE contest_entry_id = $1 AND user_id = $2
`

type RemoveEntryMemberParams struct {
	ContestEntryID uuid.UUID `json:"contest_entry_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveEntryMember(ctx context.Context, arg RemoveEntryMemberParams) error {
	_, err := q.db.Exec(ctx, removeEntryMember, arg.ContestEntryID, arg.UserID)
	return err
}

const updateContestEntryStatus = `-- name: UpdateContestEntryStatus :one
UPDATE contest_entries SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, contest_id, entry_type, entry_mode, user_id, team_id, display_name, status, registered_by, approved_by, approved_at, start_at, end_at, created_at, updated_at
`

type UpdateContestEntryStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status EntryStatus `json:"status"`
}

func (q *Queries) UpdateContestEntryStatus(ctx context.Context, arg UpdateContestEntryStatusParams) (ContestEntry, error) {
	row := q.db.QueryRow(ctx, updateContestEntryStatus, arg.ID, arg.Status)
	var i ContestEntry
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.EntryType,
		&i.EntryMode,
		&i.UserID,
		&i.TeamID,
		&i.DisplayName,
		&i.Status,
		&i.RegisteredBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
