// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_execution_logs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getCorrectionFactor = `-- name: GetCorrectionFactor :one
SELECT
    CASE
        WHEN COUNT(*) >= 3
        THEN PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY error_ratio)
        ELSE 1.0
    END AS correction_factor,
    COUNT(*) AS sample_count
FROM job_execution_logs
WHERE phase_key = $1
  AND is_final  = $2
  AND created_at > now() - interval '7 days'
  AND error_ratio IS NOT NULL
  AND error_ratio > 0
`

type GetCorrectionFactorParams struct {
	PhaseKey string `json:"phase_key"`
	IsFinal  bool   `json:"is_final"`
}

type GetCorrectionFactorRow struct {
	CorrectionFactor float64 `json:"correction_factor"`
	SampleCount      int64   `json:"sample_count"`
}

// Returns median(error_ratio) for jobs in same group over last 7 days.
// error_ratio = actual / predicted; ratio > 1 means T0 underestimates.
// Falls back to 1.0 if fewer than 3 samples (not enough data).
func (q *Queries) GetCorrectionFactor(ctx context.Context, arg GetCorrectionFactorParams) (GetCorrectionFactorRow, error) {
	row := q.db.QueryRow(ctx, getCorrectionFactor, arg.PhaseKey, arg.IsFinal)
	var i GetCorrectionFactorRow
	err := row.Scan(&i.CorrectionFactor, &i.SampleCount)
	return i, err
}

const insertJobExecutionLog = `-- name: InsertJobExecutionLog :exec
INSERT INTO job_execution_logs (
    submission_id,
    worker_id,
    phase_key,
    is_final,
    predicted_runtime_seconds,
    actual_runtime_seconds
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertJobExecutionLogParams struct {
	SubmissionID            uuid.UUID `json:"submission_id"`
	WorkerID                uuid.UUID `json:"worker_id"`
	PhaseKey                string    `json:"phase_key"`
	IsFinal                 bool      `json:"is_final"`
	PredictedRuntimeSeconds *float32  `json:"predicted_runtime_seconds"`
	ActualRuntimeSeconds    *float32  `json:"actual_runtime_seconds"`
}

func (q *Queries) InsertJobExecutionLog(ctx context.Context, arg InsertJobExecutionLogParams) error {
	_, err := q.db.Exec(ctx, insertJobExecutionLog,
		arg.SubmissionID,
		arg.WorkerID,
		arg.PhaseKey,
		arg.IsFinal,
		arg.PredictedRuntimeSeconds,
		arg.ActualRuntimeSeconds,
	)
	return err
}
