// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_execution_logs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCorrectionFactor = `-- name: GetCorrectionFactor :one
SELECT
    CASE
        WHEN COUNT(*) >= 3
        THEN PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY error_ratio)
        ELSE 1.0
    END AS correction_factor,
    COUNT(*) AS sample_count
FROM job_execution_logs
WHERE phase_key = $1
  AND is_final  = $2
  AND created_at > now() - interval '30 days'
  AND error_ratio IS NOT NULL
  AND error_ratio > 0
`

type GetCorrectionFactorParams struct {
	PhaseKey string `json:"phase_key"`
	IsFinal  bool   `json:"is_final"`
}

type GetCorrectionFactorRow struct {
	CorrectionFactor float64 `json:"correction_factor"`
	SampleCount      int64   `json:"sample_count"`
}

// Returns median(error_ratio) for jobs in same group over last 30 days.
// error_ratio = actual / predicted; ratio > 1 means T0 underestimates.
// Falls back to 1.0 if fewer than 3 samples (not enough data).
func (q *Queries) GetCorrectionFactor(ctx context.Context, arg GetCorrectionFactorParams) (GetCorrectionFactorRow, error) {
	row := q.db.QueryRow(ctx, getCorrectionFactor, arg.PhaseKey, arg.IsFinal)
	var i GetCorrectionFactorRow
	err := row.Scan(&i.CorrectionFactor, &i.SampleCount)
	return i, err
}

const getObservedResourceProfile = `-- name: GetObservedResourceProfile :one
SELECT
    COALESCE(
        PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY peak_ram_bytes)
            FILTER (WHERE peak_ram_bytes IS NOT NULL AND peak_ram_bytes > 0),
        0
    )::bigint AS p95_peak_ram_bytes,
    COALESCE(
        PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY peak_vram_bytes)
            FILTER (WHERE peak_vram_bytes IS NOT NULL AND peak_vram_bytes > 0),
        0
    )::bigint AS p95_peak_vram_bytes,
    COUNT(*) FILTER (
        WHERE peak_ram_bytes IS NOT NULL OR peak_vram_bytes IS NOT NULL
    ) AS sample_count
FROM job_execution_logs
WHERE phase_key = $1
  AND is_final = $2
  AND created_at > now() - interval '30 days'
`

type GetObservedResourceProfileParams struct {
	PhaseKey string `json:"phase_key"`
	IsFinal  bool   `json:"is_final"`
}

type GetObservedResourceProfileRow struct {
	P95PeakRamBytes  int64 `json:"p95_peak_ram_bytes"`
	P95PeakVramBytes int64 `json:"p95_peak_vram_bytes"`
	SampleCount      int64 `json:"sample_count"`
}

// Returns p95 observed RAM/VRAM usage for the same semantic phase + finalness.
func (q *Queries) GetObservedResourceProfile(ctx context.Context, arg GetObservedResourceProfileParams) (GetObservedResourceProfileRow, error) {
	row := q.db.QueryRow(ctx, getObservedResourceProfile, arg.PhaseKey, arg.IsFinal)
	var i GetObservedResourceProfileRow
	err := row.Scan(&i.P95PeakRamBytes, &i.P95PeakVramBytes, &i.SampleCount)
	return i, err
}

const insertJobExecutionLog = `-- name: InsertJobExecutionLog :exec
INSERT INTO job_execution_logs (
    submission_id,
    worker_id,
    phase_key,
    is_final,
    predicted_runtime_seconds,
    actual_runtime_seconds,
    peak_ram_bytes,
    peak_vram_bytes,
    execution_path,
    profile_payload
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertJobExecutionLogParams struct {
	SubmissionID            uuid.UUID `json:"submission_id"`
	WorkerID                uuid.UUID `json:"worker_id"`
	PhaseKey                string    `json:"phase_key"`
	IsFinal                 bool      `json:"is_final"`
	PredictedRuntimeSeconds *float32  `json:"predicted_runtime_seconds"`
	ActualRuntimeSeconds    *float32  `json:"actual_runtime_seconds"`
	PeakRamBytes            *int64    `json:"peak_ram_bytes"`
	PeakVramBytes           *int64    `json:"peak_vram_bytes"`
	ExecutionPath           *string   `json:"execution_path"`
	ProfilePayload          []byte    `json:"profile_payload"`
}

func (q *Queries) InsertJobExecutionLog(ctx context.Context, arg InsertJobExecutionLogParams) error {
	_, err := q.db.Exec(ctx, insertJobExecutionLog,
		arg.SubmissionID,
		arg.WorkerID,
		arg.PhaseKey,
		arg.IsFinal,
		arg.PredictedRuntimeSeconds,
		arg.ActualRuntimeSeconds,
		arg.PeakRamBytes,
		arg.PeakVramBytes,
		arg.ExecutionPath,
		arg.ProfilePayload,
	)
	return err
}

const listRecentJobExecutionLogs = `-- name: ListRecentJobExecutionLogs :many
SELECT
    jel.id,
    jel.submission_id,
    jel.worker_id,
    vw.display_name AS worker_name,
    jel.phase_key,
    jel.is_final,
    jel.predicted_runtime_seconds,
    jel.actual_runtime_seconds,
    jel.peak_ram_bytes,
    jel.peak_vram_bytes,
    jel.execution_path,
    jel.error_ratio,
    jel.created_at
FROM job_execution_logs jel
LEFT JOIN volunteer_workers vw ON vw.id = jel.worker_id
ORDER BY jel.created_at DESC
LIMIT $1
`

type ListRecentJobExecutionLogsRow struct {
	ID                      uuid.UUID          `json:"id"`
	SubmissionID            uuid.UUID          `json:"submission_id"`
	WorkerID                uuid.UUID          `json:"worker_id"`
	WorkerName              *string            `json:"worker_name"`
	PhaseKey                string             `json:"phase_key"`
	IsFinal                 bool               `json:"is_final"`
	PredictedRuntimeSeconds *float32           `json:"predicted_runtime_seconds"`
	ActualRuntimeSeconds    *float32           `json:"actual_runtime_seconds"`
	PeakRamBytes            *int64             `json:"peak_ram_bytes"`
	PeakVramBytes           *int64             `json:"peak_vram_bytes"`
	ExecutionPath           *string            `json:"execution_path"`
	ErrorRatio              *float32           `json:"error_ratio"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRecentJobExecutionLogs(ctx context.Context, limit int32) ([]ListRecentJobExecutionLogsRow, error) {
	rows, err := q.db.Query(ctx, listRecentJobExecutionLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentJobExecutionLogsRow
	for rows.Next() {
		var i ListRecentJobExecutionLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.WorkerID,
			&i.WorkerName,
			&i.PhaseKey,
			&i.IsFinal,
			&i.PredictedRuntimeSeconds,
			&i.ActualRuntimeSeconds,
			&i.PeakRamBytes,
			&i.PeakVramBytes,
			&i.ExecutionPath,
			&i.ErrorRatio,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
