// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboards.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getContestPhaseLeaderboard = `-- name: GetContestPhaseLeaderboard :many

SELECT lb.id, lb.contest_id, lb.contest_phase_def_id, lb.contest_entry_id, lb.rank, lb.score, lb.score_breakdown, lb.entries_count, lb.is_frozen, lb.is_disqualified, lb.dq_reason, lb.updated_at, ce.display_name, ce.entry_type, ce.entry_mode
FROM contest_phase_leaderboard_entries lb
JOIN contest_entries ce ON ce.id = lb.contest_entry_id
WHERE lb.contest_phase_def_id = $1
  AND ($4::entry_mode IS NULL OR ce.entry_mode = $4)
ORDER BY lb.rank ASC NULLS LAST
LIMIT $2 OFFSET $3
`

type GetContestPhaseLeaderboardParams struct {
	ContestPhaseDefID uuid.UUID  `json:"contest_phase_def_id"`
	Limit             int32      `json:"limit"`
	Offset            int32      `json:"offset"`
	EntryMode         *EntryMode `json:"entry_mode"`
}

type GetContestPhaseLeaderboardRow struct {
	ID                uuid.UUID          `json:"id"`
	ContestID         uuid.UUID          `json:"contest_id"`
	ContestPhaseDefID uuid.UUID          `json:"contest_phase_def_id"`
	ContestEntryID    uuid.UUID          `json:"contest_entry_id"`
	Rank              *int32             `json:"rank"`
	Score             string             `json:"score"`
	ScoreBreakdown    []byte             `json:"score_breakdown"`
	EntriesCount      int32              `json:"entries_count"`
	IsFrozen          bool               `json:"is_frozen"`
	IsDisqualified    bool               `json:"is_disqualified"`
	DqReason          *string            `json:"dq_reason"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DisplayName       string             `json:"display_name"`
	EntryType         EntryType          `json:"entry_type"`
	EntryMode         EntryMode          `json:"entry_mode"`
}

// Contest-phase leaderboard
func (q *Queries) GetContestPhaseLeaderboard(ctx context.Context, arg GetContestPhaseLeaderboardParams) ([]GetContestPhaseLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getContestPhaseLeaderboard,
		arg.ContestPhaseDefID,
		arg.Limit,
		arg.Offset,
		arg.EntryMode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContestPhaseLeaderboardRow
	for rows.Next() {
		var i GetContestPhaseLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.ContestPhaseDefID,
			&i.ContestEntryID,
			&i.Rank,
			&i.Score,
			&i.ScoreBreakdown,
			&i.EntriesCount,
			&i.IsFrozen,
			&i.IsDisqualified,
			&i.DqReason,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.EntryType,
			&i.EntryMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskPhaseLeaderboard = `-- name: GetTaskPhaseLeaderboard :many

SELECT lb.id, lb.contest_id, lb.task_id, lb.phase_id, lb.contest_entry_id, lb.rank, lb.score, lb.score_breakdown, lb.chosen_submission_id, lb.entries_count, lb.is_frozen, lb.is_disqualified, lb.dq_reason, lb.updated_at, ce.display_name, ce.entry_type, ce.entry_mode
FROM task_phase_leaderboard_entries lb
JOIN contest_entries ce ON ce.id = lb.contest_entry_id
WHERE lb.phase_id = $1
  AND ($4::entry_mode IS NULL OR ce.entry_mode = $4)
ORDER BY lb.rank ASC NULLS LAST
LIMIT $2 OFFSET $3
`

type GetTaskPhaseLeaderboardParams struct {
	PhaseID   uuid.UUID  `json:"phase_id"`
	Limit     int32      `json:"limit"`
	Offset    int32      `json:"offset"`
	EntryMode *EntryMode `json:"entry_mode"`
}

type GetTaskPhaseLeaderboardRow struct {
	ID                 uuid.UUID          `json:"id"`
	ContestID          uuid.UUID          `json:"contest_id"`
	TaskID             uuid.UUID          `json:"task_id"`
	PhaseID            uuid.UUID          `json:"phase_id"`
	ContestEntryID     uuid.UUID          `json:"contest_entry_id"`
	Rank               *int32             `json:"rank"`
	Score              string             `json:"score"`
	ScoreBreakdown     []byte             `json:"score_breakdown"`
	ChosenSubmissionID pgtype.UUID        `json:"chosen_submission_id"`
	EntriesCount       int32              `json:"entries_count"`
	IsFrozen           bool               `json:"is_frozen"`
	IsDisqualified     bool               `json:"is_disqualified"`
	DqReason           *string            `json:"dq_reason"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DisplayName        string             `json:"display_name"`
	EntryType          EntryType          `json:"entry_type"`
	EntryMode          EntryMode          `json:"entry_mode"`
}

// Task-phase leaderboard
func (q *Queries) GetTaskPhaseLeaderboard(ctx context.Context, arg GetTaskPhaseLeaderboardParams) ([]GetTaskPhaseLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getTaskPhaseLeaderboard,
		arg.PhaseID,
		arg.Limit,
		arg.Offset,
		arg.EntryMode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskPhaseLeaderboardRow
	for rows.Next() {
		var i GetTaskPhaseLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.TaskID,
			&i.PhaseID,
			&i.ContestEntryID,
			&i.Rank,
			&i.Score,
			&i.ScoreBreakdown,
			&i.ChosenSubmissionID,
			&i.EntriesCount,
			&i.IsFrozen,
			&i.IsDisqualified,
			&i.DqReason,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.EntryType,
			&i.EntryMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContestPhaseLeaderboard = `-- name: UpsertContestPhaseLeaderboard :one
INSERT INTO contest_phase_leaderboard_entries (
  contest_id, contest_phase_def_id, contest_entry_id,
  rank, score, score_breakdown, entries_count,
  is_frozen, is_disqualified
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (contest_phase_def_id, contest_entry_id) DO UPDATE SET
  rank = EXCLUDED.rank, score = EXCLUDED.score,
  score_breakdown = EXCLUDED.score_breakdown,
  entries_count = EXCLUDED.entries_count,
  is_frozen = EXCLUDED.is_frozen,
  updated_at = now()
RETURNING id, contest_id, contest_phase_def_id, contest_entry_id, rank, score, score_breakdown, entries_count, is_frozen, is_disqualified, dq_reason, updated_at
`

type UpsertContestPhaseLeaderboardParams struct {
	ContestID         uuid.UUID `json:"contest_id"`
	ContestPhaseDefID uuid.UUID `json:"contest_phase_def_id"`
	ContestEntryID    uuid.UUID `json:"contest_entry_id"`
	Rank              *int32    `json:"rank"`
	Score             string    `json:"score"`
	ScoreBreakdown    []byte    `json:"score_breakdown"`
	EntriesCount      int32     `json:"entries_count"`
	IsFrozen          bool      `json:"is_frozen"`
	IsDisqualified    bool      `json:"is_disqualified"`
}

func (q *Queries) UpsertContestPhaseLeaderboard(ctx context.Context, arg UpsertContestPhaseLeaderboardParams) (ContestPhaseLeaderboardEntry, error) {
	row := q.db.QueryRow(ctx, upsertContestPhaseLeaderboard,
		arg.ContestID,
		arg.ContestPhaseDefID,
		arg.ContestEntryID,
		arg.Rank,
		arg.Score,
		arg.ScoreBreakdown,
		arg.EntriesCount,
		arg.IsFrozen,
		arg.IsDisqualified,
	)
	var i ContestPhaseLeaderboardEntry
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ContestPhaseDefID,
		&i.ContestEntryID,
		&i.Rank,
		&i.Score,
		&i.ScoreBreakdown,
		&i.EntriesCount,
		&i.IsFrozen,
		&i.IsDisqualified,
		&i.DqReason,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTaskPhaseLeaderboard = `-- name: UpsertTaskPhaseLeaderboard :one
INSERT INTO task_phase_leaderboard_entries (
  contest_id, task_id, phase_id, contest_entry_id,
  rank, score, score_breakdown, chosen_submission_id, entries_count,
  is_frozen, is_disqualified
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (phase_id, contest_entry_id) DO UPDATE SET
  rank = EXCLUDED.rank, score = EXCLUDED.score,
  score_breakdown = EXCLUDED.score_breakdown,
  chosen_submission_id = EXCLUDED.chosen_submission_id,
  entries_count = EXCLUDED.entries_count,
  is_frozen = EXCLUDED.is_frozen,
  updated_at = now()
RETURNING id, contest_id, task_id, phase_id, contest_entry_id, rank, score, score_breakdown, chosen_submission_id, entries_count, is_frozen, is_disqualified, dq_reason, updated_at
`

type UpsertTaskPhaseLeaderboardParams struct {
	ContestID          uuid.UUID   `json:"contest_id"`
	TaskID             uuid.UUID   `json:"task_id"`
	PhaseID            uuid.UUID   `json:"phase_id"`
	ContestEntryID     uuid.UUID   `json:"contest_entry_id"`
	Rank               *int32      `json:"rank"`
	Score              string      `json:"score"`
	ScoreBreakdown     []byte      `json:"score_breakdown"`
	ChosenSubmissionID pgtype.UUID `json:"chosen_submission_id"`
	EntriesCount       int32       `json:"entries_count"`
	IsFrozen           bool        `json:"is_frozen"`
	IsDisqualified     bool        `json:"is_disqualified"`
}

func (q *Queries) UpsertTaskPhaseLeaderboard(ctx context.Context, arg UpsertTaskPhaseLeaderboardParams) (TaskPhaseLeaderboardEntry, error) {
	row := q.db.QueryRow(ctx, upsertTaskPhaseLeaderboard,
		arg.ContestID,
		arg.TaskID,
		arg.PhaseID,
		arg.ContestEntryID,
		arg.Rank,
		arg.Score,
		arg.ScoreBreakdown,
		arg.ChosenSubmissionID,
		arg.EntriesCount,
		arg.IsFrozen,
		arg.IsDisqualified,
	)
	var i TaskPhaseLeaderboardEntry
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.TaskID,
		&i.PhaseID,
		&i.ContestEntryID,
		&i.Rank,
		&i.Score,
		&i.ScoreBreakdown,
		&i.ChosenSubmissionID,
		&i.EntriesCount,
		&i.IsFrozen,
		&i.IsDisqualified,
		&i.DqReason,
		&i.UpdatedAt,
	)
	return i, err
}
