// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboards.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAllLeaderboardEntriesForPhase = `-- name: GetAllLeaderboardEntriesForPhase :many
SELECT contest_entry_id, score
FROM task_phase_leaderboard_entries
WHERE phase_id = $1
ORDER BY rank ASC
`

type GetAllLeaderboardEntriesForPhaseRow struct {
	ContestEntryID uuid.UUID `json:"contest_entry_id"`
	Score          string    `json:"score"`
}

// Used to seed Redis ZSET on startup from existing DB state.
func (q *Queries) GetAllLeaderboardEntriesForPhase(ctx context.Context, phaseID uuid.UUID) ([]GetAllLeaderboardEntriesForPhaseRow, error) {
	rows, err := q.db.Query(ctx, getAllLeaderboardEntriesForPhase, phaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLeaderboardEntriesForPhaseRow
	for rows.Next() {
		var i GetAllLeaderboardEntriesForPhaseRow
		if err := rows.Scan(&i.ContestEntryID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBestSubmissionForEntry = `-- name: GetBestSubmissionForEntry :one
SELECT s.id, s.display_score
FROM submissions s
WHERE s.phase_id = $1
  AND s.contest_entry_id = $2
  AND s.status = 'done'
  AND s.display_score IS NOT NULL
ORDER BY s.is_final DESC, s.display_score DESC, s.submitted_at DESC
LIMIT 1
`

type GetBestSubmissionForEntryParams struct {
	PhaseID        uuid.UUID `json:"phase_id"`
	ContestEntryID uuid.UUID `json:"contest_entry_id"`
}

type GetBestSubmissionForEntryRow struct {
	ID           uuid.UUID      `json:"id"`
	DisplayScore pgtype.Numeric `json:"display_score"`
}

// Returns the chosen submission_id and its display_score for an entry in a phase.
func (q *Queries) GetBestSubmissionForEntry(ctx context.Context, arg GetBestSubmissionForEntryParams) (GetBestSubmissionForEntryRow, error) {
	row := q.db.QueryRow(ctx, getBestSubmissionForEntry, arg.PhaseID, arg.ContestEntryID)
	var i GetBestSubmissionForEntryRow
	err := row.Scan(&i.ID, &i.DisplayScore)
	return i, err
}

const getContestPhaseLeaderboard = `-- name: GetContestPhaseLeaderboard :many

SELECT lb.id, lb.contest_id, lb.contest_phase_def_id, lb.contest_entry_id, lb.rank, lb.score, lb.score_breakdown, lb.entries_count, lb.is_frozen, lb.is_disqualified, lb.dq_reason, lb.updated_at, lb.raw_score, ce.display_name, ce.entry_type, ce.entry_mode,
       COALESCE(
         (SELECT array_agg(u.email::text)::text[]
          FROM contest_entry_members cem
          JOIN users u ON u.id = cem.user_id
          WHERE cem.contest_entry_id = ce.id),
         ARRAY[]::text[]
       ) AS user_emails
FROM contest_phase_leaderboard_entries lb
JOIN contest_entries ce ON ce.id = lb.contest_entry_id
WHERE lb.contest_phase_def_id = $1
  AND ($4::entry_mode IS NULL OR ce.entry_mode = $4)
ORDER BY lb.rank ASC NULLS LAST
LIMIT $2 OFFSET $3
`

type GetContestPhaseLeaderboardParams struct {
	ContestPhaseDefID uuid.UUID  `json:"contest_phase_def_id"`
	Limit             int32      `json:"limit"`
	Offset            int32      `json:"offset"`
	EntryMode         *EntryMode `json:"entry_mode"`
}

type GetContestPhaseLeaderboardRow struct {
	ID                uuid.UUID          `json:"id"`
	ContestID         uuid.UUID          `json:"contest_id"`
	ContestPhaseDefID uuid.UUID          `json:"contest_phase_def_id"`
	ContestEntryID    uuid.UUID          `json:"contest_entry_id"`
	Rank              *int32             `json:"rank"`
	Score             string             `json:"score"`
	ScoreBreakdown    []byte             `json:"score_breakdown"`
	EntriesCount      int32              `json:"entries_count"`
	IsFrozen          bool               `json:"is_frozen"`
	IsDisqualified    bool               `json:"is_disqualified"`
	DqReason          *string            `json:"dq_reason"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	RawScore          string             `json:"raw_score"`
	DisplayName       string             `json:"display_name"`
	EntryType         EntryType          `json:"entry_type"`
	EntryMode         EntryMode          `json:"entry_mode"`
	UserEmails        interface{}        `json:"user_emails"`
}

// Contest-phase leaderboard
func (q *Queries) GetContestPhaseLeaderboard(ctx context.Context, arg GetContestPhaseLeaderboardParams) ([]GetContestPhaseLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getContestPhaseLeaderboard,
		arg.ContestPhaseDefID,
		arg.Limit,
		arg.Offset,
		arg.EntryMode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContestPhaseLeaderboardRow
	for rows.Next() {
		var i GetContestPhaseLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.ContestPhaseDefID,
			&i.ContestEntryID,
			&i.Rank,
			&i.Score,
			&i.ScoreBreakdown,
			&i.EntriesCount,
			&i.IsFrozen,
			&i.IsDisqualified,
			&i.DqReason,
			&i.UpdatedAt,
			&i.RawScore,
			&i.DisplayName,
			&i.EntryType,
			&i.EntryMode,
			&i.UserEmails,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhaseMaxScore = `-- name: GetPhaseMaxScore :one

SELECT COALESCE(MAX(raw_score), 0)::float8 AS max_score
FROM task_phase_leaderboard_entries
WHERE phase_id = $1
`

// ── Incremental leaderboard queries (Phase 04) ──────────────────────────────
// Returns current max display_score among all entries in phase.
// Used to decide whether incremental or full recompute is needed.
func (q *Queries) GetPhaseMaxScore(ctx context.Context, phaseID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getPhaseMaxScore, phaseID)
	var max_score float64
	err := row.Scan(&max_score)
	return max_score, err
}

const getTaskPhaseLeaderboard = `-- name: GetTaskPhaseLeaderboard :many

SELECT lb.id, lb.contest_id, lb.task_id, lb.phase_id, lb.contest_entry_id, lb.rank, lb.score, lb.score_breakdown, lb.chosen_submission_id, lb.entries_count, lb.is_frozen, lb.is_disqualified, lb.dq_reason, lb.updated_at, lb.raw_score, ce.display_name, ce.entry_type, ce.entry_mode,
       COALESCE(
         (SELECT array_agg(u.email::text)::text[]
          FROM contest_entry_members cem
          JOIN users u ON u.id = cem.user_id
          WHERE cem.contest_entry_id = ce.id),
         ARRAY[]::text[]
       ) AS user_emails
FROM task_phase_leaderboard_entries lb
JOIN contest_entries ce ON ce.id = lb.contest_entry_id
WHERE lb.phase_id = $1
  AND ($4::entry_mode IS NULL OR ce.entry_mode = $4)
ORDER BY lb.rank ASC NULLS LAST
LIMIT $2 OFFSET $3
`

type GetTaskPhaseLeaderboardParams struct {
	PhaseID   uuid.UUID  `json:"phase_id"`
	Limit     int32      `json:"limit"`
	Offset    int32      `json:"offset"`
	EntryMode *EntryMode `json:"entry_mode"`
}

type GetTaskPhaseLeaderboardRow struct {
	ID                 uuid.UUID          `json:"id"`
	ContestID          uuid.UUID          `json:"contest_id"`
	TaskID             uuid.UUID          `json:"task_id"`
	PhaseID            uuid.UUID          `json:"phase_id"`
	ContestEntryID     uuid.UUID          `json:"contest_entry_id"`
	Rank               *int32             `json:"rank"`
	Score              string             `json:"score"`
	ScoreBreakdown     []byte             `json:"score_breakdown"`
	ChosenSubmissionID pgtype.UUID        `json:"chosen_submission_id"`
	EntriesCount       int32              `json:"entries_count"`
	IsFrozen           bool               `json:"is_frozen"`
	IsDisqualified     bool               `json:"is_disqualified"`
	DqReason           *string            `json:"dq_reason"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	RawScore           string             `json:"raw_score"`
	DisplayName        string             `json:"display_name"`
	EntryType          EntryType          `json:"entry_type"`
	EntryMode          EntryMode          `json:"entry_mode"`
	UserEmails         interface{}        `json:"user_emails"`
}

// Task-phase leaderboard
func (q *Queries) GetTaskPhaseLeaderboard(ctx context.Context, arg GetTaskPhaseLeaderboardParams) ([]GetTaskPhaseLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getTaskPhaseLeaderboard,
		arg.PhaseID,
		arg.Limit,
		arg.Offset,
		arg.EntryMode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskPhaseLeaderboardRow
	for rows.Next() {
		var i GetTaskPhaseLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.TaskID,
			&i.PhaseID,
			&i.ContestEntryID,
			&i.Rank,
			&i.Score,
			&i.ScoreBreakdown,
			&i.ChosenSubmissionID,
			&i.EntriesCount,
			&i.IsFrozen,
			&i.IsDisqualified,
			&i.DqReason,
			&i.UpdatedAt,
			&i.RawScore,
			&i.DisplayName,
			&i.EntryType,
			&i.EntryMode,
			&i.UserEmails,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeContestPhaseLeaderboard = `-- name: RecomputeContestPhaseLeaderboard :exec
WITH phases_in_def AS (
  SELECT p.id AS phase_id, p.task_id, p.leaderboard_mode, t.higher_is_better, t.contest_id
  FROM phases p
  JOIN tasks t ON t.id = p.task_id
  WHERE p.contest_phase_def_id = $1::uuid
    AND t.contest_id = $2::uuid
),
per_phase_choice AS (
  SELECT
    s.contest_id,
    s.phase_id,
    s.contest_entry_id,
    s.id AS submission_id,
    s.display_score,
    row_number() OVER (
      PARTITION BY s.phase_id, s.contest_entry_id
      ORDER BY
        s.is_final DESC,
        CASE WHEN pid.leaderboard_mode = 'latest' THEN s.submitted_at END DESC NULLS LAST,
        CASE WHEN pid.leaderboard_mode = 'best' AND pid.higher_is_better THEN s.display_score END DESC NULLS LAST,
        CASE WHEN pid.leaderboard_mode = 'best' AND NOT pid.higher_is_better THEN s.display_score END ASC NULLS LAST,
        s.submitted_at DESC
    ) AS rn
  FROM submissions s
  JOIN phases_in_def pid ON pid.phase_id = s.phase_id
  WHERE s.status = 'done'
    AND s.display_score IS NOT NULL
),
chosen AS (
  SELECT contest_id, phase_id, contest_entry_id, submission_id, display_score, rn FROM per_phase_choice WHERE rn = 1
),
chosen_with_max AS (
  SELECT c.contest_id, c.phase_id, c.contest_entry_id, c.submission_id, c.display_score, c.rn,
         MAX(c.display_score) OVER(PARTITION BY c.phase_id) as max_phase_score
  FROM chosen c
),
agg AS (
  SELECT
    c.contest_id,
    $1::uuid AS contest_phase_def_id,
    c.contest_entry_id,
    SUM(
      CASE 
        WHEN ct.scale_scores = TRUE THEN
          CASE 
            WHEN COALESCE(c.max_phase_score, 0) > 0 THEN (c.display_score / c.max_phase_score) * 100
            ELSE 0
          END
        ELSE c.display_score
      END
    ) AS total_score,
    SUM(c.display_score) AS raw_score,
    COUNT(*)::int AS entries_count
  FROM chosen_with_max c
  JOIN contests ct ON ct.id = c.contest_id
  GROUP BY c.contest_id, c.contest_entry_id, ct.scale_scores
),
ranked AS (
  SELECT
    a.contest_id, a.contest_phase_def_id, a.contest_entry_id, a.total_score, a.raw_score, a.entries_count,
    dense_rank() OVER (ORDER BY a.total_score DESC NULLS LAST)::int AS rank
  FROM agg a
)
INSERT INTO contest_phase_leaderboard_entries (
  contest_id, contest_phase_def_id, contest_entry_id,
  rank, score, raw_score, score_breakdown, entries_count,
  is_frozen, is_disqualified
)
SELECT
  r.contest_id,
  r.contest_phase_def_id,
  r.contest_entry_id,
  r.rank,
  r.total_score,
  r.raw_score,
  NULL::jsonb,
  r.entries_count,
  false,
  (ce.status = 'disqualified')
FROM ranked r
JOIN contest_entries ce ON ce.id = r.contest_entry_id
ON CONFLICT (contest_phase_def_id, contest_entry_id) DO UPDATE SET
  rank = EXCLUDED.rank,
  score = EXCLUDED.score,
  raw_score = EXCLUDED.raw_score,
  score_breakdown = EXCLUDED.score_breakdown,
  entries_count = EXCLUDED.entries_count,
  is_frozen = EXCLUDED.is_frozen,
  updated_at = now()
`

type RecomputeContestPhaseLeaderboardParams struct {
	ContestPhaseDefID uuid.UUID `json:"contest_phase_def_id"`
	ContestID         uuid.UUID `json:"contest_id"`
}

func (q *Queries) RecomputeContestPhaseLeaderboard(ctx context.Context, arg RecomputeContestPhaseLeaderboardParams) error {
	_, err := q.db.Exec(ctx, recomputeContestPhaseLeaderboard, arg.ContestPhaseDefID, arg.ContestID)
	return err
}

const recomputeTaskPhaseLeaderboard = `-- name: RecomputeTaskPhaseLeaderboard :exec
WITH candidate AS (
  SELECT
    s.contest_id,
    s.task_id,
    s.phase_id,
    s.contest_entry_id,
    s.id AS submission_id,
    s.display_score,
    row_number() OVER (
      PARTITION BY s.contest_entry_id
      ORDER BY
        s.is_final DESC,
        CASE WHEN $1::leaderboard_mode = 'latest' THEN s.submitted_at END DESC NULLS LAST,
        CASE WHEN $1::leaderboard_mode = 'best' AND $2::boolean THEN s.display_score END DESC NULLS LAST,
        CASE WHEN $1::leaderboard_mode = 'best' AND NOT $2::boolean THEN s.display_score END ASC NULLS LAST,
        s.submitted_at DESC
    ) AS rn,
    count(*) OVER (PARTITION BY s.contest_entry_id) AS entries_count
  FROM submissions s
  WHERE s.phase_id = $3::uuid
    AND s.status = 'done'
    AND s.display_score IS NOT NULL
),
chosen AS (
  SELECT contest_id, task_id, phase_id, contest_entry_id, submission_id, display_score, rn, entries_count FROM candidate WHERE rn = 1
),
chosen_with_max AS (
  SELECT c.contest_id, c.task_id, c.phase_id, c.contest_entry_id, c.submission_id, c.display_score, c.rn, c.entries_count,
         MAX(c.display_score) OVER() as max_phase_score
  FROM chosen c
),
ranked AS (
  SELECT
    c.contest_id, c.task_id, c.phase_id, c.contest_entry_id, c.submission_id, c.display_score, c.rn, c.entries_count, c.max_phase_score,
    dense_rank() OVER (
      ORDER BY
        CASE WHEN $1::leaderboard_mode = 'best' AND $2::boolean THEN c.display_score END DESC NULLS LAST,
        CASE WHEN $1::leaderboard_mode = 'best' AND NOT $2::boolean THEN c.display_score END ASC NULLS LAST,
        c.display_score DESC NULLS LAST
    )::int AS rank
  FROM chosen_with_max c
)
INSERT INTO task_phase_leaderboard_entries (
  contest_id, task_id, phase_id, contest_entry_id,
  rank, score, raw_score, score_breakdown, chosen_submission_id, entries_count,
  is_frozen, is_disqualified
)
SELECT
  r.contest_id,
  r.task_id,
  r.phase_id,
  r.contest_entry_id,
  r.rank,
  CASE 
    WHEN ct.scale_scores = TRUE THEN
      CASE 
        WHEN COALESCE(r.max_phase_score, 0) > 0 THEN (r.display_score / r.max_phase_score) * 100
        ELSE 0
      END
    ELSE r.display_score
  END AS score,
  r.display_score AS raw_score,
  NULL::jsonb,
  r.submission_id,
  r.entries_count,
  p.is_frozen,
  (ce.status = 'disqualified')
FROM ranked r
JOIN phases p ON p.id = r.phase_id
JOIN contest_entries ce ON ce.id = r.contest_entry_id
JOIN contests ct ON ct.id = r.contest_id
ON CONFLICT (phase_id, contest_entry_id) DO UPDATE SET
  rank = EXCLUDED.rank,
  score = EXCLUDED.score,
  raw_score = EXCLUDED.raw_score,
  score_breakdown = EXCLUDED.score_breakdown,
  chosen_submission_id = EXCLUDED.chosen_submission_id,
  entries_count = EXCLUDED.entries_count,
  is_frozen = EXCLUDED.is_frozen,
  updated_at = now()
`

type RecomputeTaskPhaseLeaderboardParams struct {
	LeaderboardMode LeaderboardMode `json:"leaderboard_mode"`
	HigherIsBetter  bool            `json:"higher_is_better"`
	PhaseID         uuid.UUID       `json:"phase_id"`
}

func (q *Queries) RecomputeTaskPhaseLeaderboard(ctx context.Context, arg RecomputeTaskPhaseLeaderboardParams) error {
	_, err := q.db.Exec(ctx, recomputeTaskPhaseLeaderboard, arg.LeaderboardMode, arg.HigherIsBetter, arg.PhaseID)
	return err
}

const updateSingleLeaderboardEntry = `-- name: UpdateSingleLeaderboardEntry :exec
UPDATE task_phase_leaderboard_entries
SET
    rank       = $3,
    score      = $4,
    raw_score  = $5,
    chosen_submission_id = $6,
    entries_count        = $7,
    updated_at = now()
WHERE phase_id = $1 AND contest_entry_id = $2
`

type UpdateSingleLeaderboardEntryParams struct {
	PhaseID            uuid.UUID   `json:"phase_id"`
	ContestEntryID     uuid.UUID   `json:"contest_entry_id"`
	Rank               *int32      `json:"rank"`
	Score              string      `json:"score"`
	RawScore           string      `json:"raw_score"`
	ChosenSubmissionID pgtype.UUID `json:"chosen_submission_id"`
	EntriesCount       int32       `json:"entries_count"`
}

// Updates one entry after incremental recompute (O(log n) path).
func (q *Queries) UpdateSingleLeaderboardEntry(ctx context.Context, arg UpdateSingleLeaderboardEntryParams) error {
	_, err := q.db.Exec(ctx, updateSingleLeaderboardEntry,
		arg.PhaseID,
		arg.ContestEntryID,
		arg.Rank,
		arg.Score,
		arg.RawScore,
		arg.ChosenSubmissionID,
		arg.EntriesCount,
	)
	return err
}

const upsertContestPhaseLeaderboard = `-- name: UpsertContestPhaseLeaderboard :one
INSERT INTO contest_phase_leaderboard_entries (
  contest_id, contest_phase_def_id, contest_entry_id,
  rank, score, score_breakdown, entries_count,
  is_frozen, is_disqualified
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (contest_phase_def_id, contest_entry_id) DO UPDATE SET
  rank = EXCLUDED.rank, score = EXCLUDED.score,
  score_breakdown = EXCLUDED.score_breakdown,
  entries_count = EXCLUDED.entries_count,
  is_frozen = EXCLUDED.is_frozen,
  updated_at = now()
RETURNING id, contest_id, contest_phase_def_id, contest_entry_id, rank, score, score_breakdown, entries_count, is_frozen, is_disqualified, dq_reason, updated_at, raw_score
`

type UpsertContestPhaseLeaderboardParams struct {
	ContestID         uuid.UUID `json:"contest_id"`
	ContestPhaseDefID uuid.UUID `json:"contest_phase_def_id"`
	ContestEntryID    uuid.UUID `json:"contest_entry_id"`
	Rank              *int32    `json:"rank"`
	Score             string    `json:"score"`
	ScoreBreakdown    []byte    `json:"score_breakdown"`
	EntriesCount      int32     `json:"entries_count"`
	IsFrozen          bool      `json:"is_frozen"`
	IsDisqualified    bool      `json:"is_disqualified"`
}

func (q *Queries) UpsertContestPhaseLeaderboard(ctx context.Context, arg UpsertContestPhaseLeaderboardParams) (ContestPhaseLeaderboardEntry, error) {
	row := q.db.QueryRow(ctx, upsertContestPhaseLeaderboard,
		arg.ContestID,
		arg.ContestPhaseDefID,
		arg.ContestEntryID,
		arg.Rank,
		arg.Score,
		arg.ScoreBreakdown,
		arg.EntriesCount,
		arg.IsFrozen,
		arg.IsDisqualified,
	)
	var i ContestPhaseLeaderboardEntry
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ContestPhaseDefID,
		&i.ContestEntryID,
		&i.Rank,
		&i.Score,
		&i.ScoreBreakdown,
		&i.EntriesCount,
		&i.IsFrozen,
		&i.IsDisqualified,
		&i.DqReason,
		&i.UpdatedAt,
		&i.RawScore,
	)
	return i, err
}

const upsertTaskPhaseLeaderboard = `-- name: UpsertTaskPhaseLeaderboard :one
INSERT INTO task_phase_leaderboard_entries (
  contest_id, task_id, phase_id, contest_entry_id,
  rank, score, score_breakdown, chosen_submission_id, entries_count,
  is_frozen, is_disqualified
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (phase_id, contest_entry_id) DO UPDATE SET
  rank = EXCLUDED.rank, score = EXCLUDED.score,
  score_breakdown = EXCLUDED.score_breakdown,
  chosen_submission_id = EXCLUDED.chosen_submission_id,
  entries_count = EXCLUDED.entries_count,
  is_frozen = EXCLUDED.is_frozen,
  updated_at = now()
RETURNING id, contest_id, task_id, phase_id, contest_entry_id, rank, score, score_breakdown, chosen_submission_id, entries_count, is_frozen, is_disqualified, dq_reason, updated_at, raw_score
`

type UpsertTaskPhaseLeaderboardParams struct {
	ContestID          uuid.UUID   `json:"contest_id"`
	TaskID             uuid.UUID   `json:"task_id"`
	PhaseID            uuid.UUID   `json:"phase_id"`
	ContestEntryID     uuid.UUID   `json:"contest_entry_id"`
	Rank               *int32      `json:"rank"`
	Score              string      `json:"score"`
	ScoreBreakdown     []byte      `json:"score_breakdown"`
	ChosenSubmissionID pgtype.UUID `json:"chosen_submission_id"`
	EntriesCount       int32       `json:"entries_count"`
	IsFrozen           bool        `json:"is_frozen"`
	IsDisqualified     bool        `json:"is_disqualified"`
}

func (q *Queries) UpsertTaskPhaseLeaderboard(ctx context.Context, arg UpsertTaskPhaseLeaderboardParams) (TaskPhaseLeaderboardEntry, error) {
	row := q.db.QueryRow(ctx, upsertTaskPhaseLeaderboard,
		arg.ContestID,
		arg.TaskID,
		arg.PhaseID,
		arg.ContestEntryID,
		arg.Rank,
		arg.Score,
		arg.ScoreBreakdown,
		arg.ChosenSubmissionID,
		arg.EntriesCount,
		arg.IsFrozen,
		arg.IsDisqualified,
	)
	var i TaskPhaseLeaderboardEntry
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.TaskID,
		&i.PhaseID,
		&i.ContestEntryID,
		&i.Rank,
		&i.Score,
		&i.ScoreBreakdown,
		&i.ChosenSubmissionID,
		&i.EntriesCount,
		&i.IsFrozen,
		&i.IsDisqualified,
		&i.DqReason,
		&i.UpdatedAt,
		&i.RawScore,
	)
	return i, err
}
