// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ClarificationStatus string

const (
	ClarificationStatusPending  ClarificationStatus = "pending"
	ClarificationStatusAnswered ClarificationStatus = "answered"
	ClarificationStatusClosed   ClarificationStatus = "closed"
)

func (e *ClarificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClarificationStatus(s)
	case string:
		*e = ClarificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ClarificationStatus: %T", src)
	}
	return nil
}

type NullClarificationStatus struct {
	ClarificationStatus ClarificationStatus `json:"clarification_status"`
	Valid               bool                `json:"valid"` // Valid is true if ClarificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClarificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ClarificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClarificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClarificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClarificationStatus), nil
}

func (e ClarificationStatus) Valid() bool {
	switch e {
	case ClarificationStatusPending,
		ClarificationStatusAnswered,
		ClarificationStatusClosed:
		return true
	}
	return false
}

type ContestEntryPolicy string

const (
	ContestEntryPolicyIndividual ContestEntryPolicy = "individual"
	ContestEntryPolicyTeam       ContestEntryPolicy = "team"
	ContestEntryPolicyBoth       ContestEntryPolicy = "both"
)

func (e *ContestEntryPolicy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContestEntryPolicy(s)
	case string:
		*e = ContestEntryPolicy(s)
	default:
		return fmt.Errorf("unsupported scan type for ContestEntryPolicy: %T", src)
	}
	return nil
}

type NullContestEntryPolicy struct {
	ContestEntryPolicy ContestEntryPolicy `json:"contest_entry_policy"`
	Valid              bool               `json:"valid"` // Valid is true if ContestEntryPolicy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContestEntryPolicy) Scan(value interface{}) error {
	if value == nil {
		ns.ContestEntryPolicy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContestEntryPolicy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContestEntryPolicy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContestEntryPolicy), nil
}

func (e ContestEntryPolicy) Valid() bool {
	switch e {
	case ContestEntryPolicyIndividual,
		ContestEntryPolicyTeam,
		ContestEntryPolicyBoth:
		return true
	}
	return false
}

type ContestPhaseKey string

const (
	ContestPhaseKeyPublicTest   ContestPhaseKey = "public_test"
	ContestPhaseKeyPrivateTest  ContestPhaseKey = "private_test"
	ContestPhaseKeyFinalPublic  ContestPhaseKey = "final_public"
	ContestPhaseKeyFinalPrivate ContestPhaseKey = "final_private"
)

func (e *ContestPhaseKey) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContestPhaseKey(s)
	case string:
		*e = ContestPhaseKey(s)
	default:
		return fmt.Errorf("unsupported scan type for ContestPhaseKey: %T", src)
	}
	return nil
}

type NullContestPhaseKey struct {
	ContestPhaseKey ContestPhaseKey `json:"contest_phase_key"`
	Valid           bool            `json:"valid"` // Valid is true if ContestPhaseKey is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContestPhaseKey) Scan(value interface{}) error {
	if value == nil {
		ns.ContestPhaseKey, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContestPhaseKey.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContestPhaseKey) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContestPhaseKey), nil
}

func (e ContestPhaseKey) Valid() bool {
	switch e {
	case ContestPhaseKeyPublicTest,
		ContestPhaseKeyPrivateTest,
		ContestPhaseKeyFinalPublic,
		ContestPhaseKeyFinalPrivate:
		return true
	}
	return false
}

type ContestStatus string

const (
	ContestStatusDraft            ContestStatus = "draft"
	ContestStatusRegistrationOpen ContestStatus = "registration_open"
	ContestStatusRunning          ContestStatus = "running"
	ContestStatusEnded            ContestStatus = "ended"
	ContestStatusArchived         ContestStatus = "archived"
)

func (e *ContestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContestStatus(s)
	case string:
		*e = ContestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContestStatus: %T", src)
	}
	return nil
}

type NullContestStatus struct {
	ContestStatus ContestStatus `json:"contest_status"`
	Valid         bool          `json:"valid"` // Valid is true if ContestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContestStatus), nil
}

func (e ContestStatus) Valid() bool {
	switch e {
	case ContestStatusDraft,
		ContestStatusRegistrationOpen,
		ContestStatusRunning,
		ContestStatusEnded,
		ContestStatusArchived:
		return true
	}
	return false
}

type ContestVisibility string

const (
	ContestVisibilityPublic  ContestVisibility = "public"
	ContestVisibilityPrivate ContestVisibility = "private"
)

func (e *ContestVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContestVisibility(s)
	case string:
		*e = ContestVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for ContestVisibility: %T", src)
	}
	return nil
}

type NullContestVisibility struct {
	ContestVisibility ContestVisibility `json:"contest_visibility"`
	Valid             bool              `json:"valid"` // Valid is true if ContestVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContestVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.ContestVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContestVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContestVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContestVisibility), nil
}

func (e ContestVisibility) Valid() bool {
	switch e {
	case ContestVisibilityPublic,
		ContestVisibilityPrivate:
		return true
	}
	return false
}

type EntryMemberRole string

const (
	EntryMemberRoleLeader EntryMemberRole = "leader"
	EntryMemberRoleMember EntryMemberRole = "member"
)

func (e *EntryMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryMemberRole(s)
	case string:
		*e = EntryMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryMemberRole: %T", src)
	}
	return nil
}

type NullEntryMemberRole struct {
	EntryMemberRole EntryMemberRole `json:"entry_member_role"`
	Valid           bool            `json:"valid"` // Valid is true if EntryMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.EntryMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryMemberRole), nil
}

func (e EntryMemberRole) Valid() bool {
	switch e {
	case EntryMemberRoleLeader,
		EntryMemberRoleMember:
		return true
	}
	return false
}

type EntryMode string

const (
	EntryModeOfficial EntryMode = "official"
	EntryModeVirtual  EntryMode = "virtual"
	EntryModePractice EntryMode = "practice"
)

func (e *EntryMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryMode(s)
	case string:
		*e = EntryMode(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryMode: %T", src)
	}
	return nil
}

type NullEntryMode struct {
	EntryMode EntryMode `json:"entry_mode"`
	Valid     bool      `json:"valid"` // Valid is true if EntryMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryMode) Scan(value interface{}) error {
	if value == nil {
		ns.EntryMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryMode), nil
}

func (e EntryMode) Valid() bool {
	switch e {
	case EntryModeOfficial,
		EntryModeVirtual,
		EntryModePractice:
		return true
	}
	return false
}

type EntryStatus string

const (
	EntryStatusPending      EntryStatus = "pending"
	EntryStatusApproved     EntryStatus = "approved"
	EntryStatusActive       EntryStatus = "active"
	EntryStatusDisqualified EntryStatus = "disqualified"
	EntryStatusFinished     EntryStatus = "finished"
)

func (e *EntryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryStatus(s)
	case string:
		*e = EntryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryStatus: %T", src)
	}
	return nil
}

type NullEntryStatus struct {
	EntryStatus EntryStatus `json:"entry_status"`
	Valid       bool        `json:"valid"` // Valid is true if EntryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EntryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryStatus), nil
}

func (e EntryStatus) Valid() bool {
	switch e {
	case EntryStatusPending,
		EntryStatusApproved,
		EntryStatusActive,
		EntryStatusDisqualified,
		EntryStatusFinished:
		return true
	}
	return false
}

type EntryType string

const (
	EntryTypeIndividual EntryType = "individual"
	EntryTypeTeam       EntryType = "team"
)

func (e *EntryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryType(s)
	case string:
		*e = EntryType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryType: %T", src)
	}
	return nil
}

type NullEntryType struct {
	EntryType EntryType `json:"entry_type"`
	Valid     bool      `json:"valid"` // Valid is true if EntryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryType) Scan(value interface{}) error {
	if value == nil {
		ns.EntryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryType), nil
}

func (e EntryType) Valid() bool {
	switch e {
	case EntryTypeIndividual,
		EntryTypeTeam:
		return true
	}
	return false
}

type EvalJobStatus string

const (
	EvalJobStatusPending EvalJobStatus = "pending"
	EvalJobStatusRunning EvalJobStatus = "running"
	EvalJobStatusDone    EvalJobStatus = "done"
	EvalJobStatusFailed  EvalJobStatus = "failed"
)

func (e *EvalJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EvalJobStatus(s)
	case string:
		*e = EvalJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EvalJobStatus: %T", src)
	}
	return nil
}

type NullEvalJobStatus struct {
	EvalJobStatus EvalJobStatus `json:"eval_job_status"`
	Valid         bool          `json:"valid"` // Valid is true if EvalJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEvalJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EvalJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EvalJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEvalJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EvalJobStatus), nil
}

func (e EvalJobStatus) Valid() bool {
	switch e {
	case EvalJobStatusPending,
		EvalJobStatusRunning,
		EvalJobStatusDone,
		EvalJobStatusFailed:
		return true
	}
	return false
}

type EvalJobType string

const (
	EvalJobTypeValidate EvalJobType = "validate"
	EvalJobTypeJudge    EvalJobType = "judge"
	EvalJobTypeRejudge  EvalJobType = "rejudge"
)

func (e *EvalJobType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EvalJobType(s)
	case string:
		*e = EvalJobType(s)
	default:
		return fmt.Errorf("unsupported scan type for EvalJobType: %T", src)
	}
	return nil
}

type NullEvalJobType struct {
	EvalJobType EvalJobType `json:"eval_job_type"`
	Valid       bool        `json:"valid"` // Valid is true if EvalJobType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEvalJobType) Scan(value interface{}) error {
	if value == nil {
		ns.EvalJobType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EvalJobType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEvalJobType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EvalJobType), nil
}

func (e EvalJobType) Valid() bool {
	switch e {
	case EvalJobTypeValidate,
		EvalJobTypeJudge,
		EvalJobTypeRejudge:
		return true
	}
	return false
}

type LeaderboardMode string

const (
	LeaderboardModeBest   LeaderboardMode = "best"
	LeaderboardModeLatest LeaderboardMode = "latest"
)

func (e *LeaderboardMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeaderboardMode(s)
	case string:
		*e = LeaderboardMode(s)
	default:
		return fmt.Errorf("unsupported scan type for LeaderboardMode: %T", src)
	}
	return nil
}

type NullLeaderboardMode struct {
	LeaderboardMode LeaderboardMode `json:"leaderboard_mode"`
	Valid           bool            `json:"valid"` // Valid is true if LeaderboardMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeaderboardMode) Scan(value interface{}) error {
	if value == nil {
		ns.LeaderboardMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeaderboardMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeaderboardMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeaderboardMode), nil
}

func (e LeaderboardMode) Valid() bool {
	switch e {
	case LeaderboardModeBest,
		LeaderboardModeLatest:
		return true
	}
	return false
}

type SubmissionStatus string

const (
	SubmissionStatusUploaded   SubmissionStatus = "uploaded"
	SubmissionStatusValidating SubmissionStatus = "validating"
	SubmissionStatusQueued     SubmissionStatus = "queued"
	SubmissionStatusRunning    SubmissionStatus = "running"
	SubmissionStatusDone       SubmissionStatus = "done"
	SubmissionStatusFailed     SubmissionStatus = "failed"
)

func (e *SubmissionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubmissionStatus(s)
	case string:
		*e = SubmissionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubmissionStatus: %T", src)
	}
	return nil
}

type NullSubmissionStatus struct {
	SubmissionStatus SubmissionStatus `json:"submission_status"`
	Valid            bool             `json:"valid"` // Valid is true if SubmissionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubmissionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubmissionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubmissionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubmissionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubmissionStatus), nil
}

func (e SubmissionStatus) Valid() bool {
	switch e {
	case SubmissionStatusUploaded,
		SubmissionStatusValidating,
		SubmissionStatusQueued,
		SubmissionStatusRunning,
		SubmissionStatusDone,
		SubmissionStatusFailed:
		return true
	}
	return false
}

type TeamRole string

const (
	TeamRoleManager TeamRole = "manager"
	TeamRoleMember  TeamRole = "member"
)

func (e *TeamRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamRole(s)
	case string:
		*e = TeamRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamRole: %T", src)
	}
	return nil
}

type NullTeamRole struct {
	TeamRole TeamRole `json:"team_role"`
	Valid    bool     `json:"valid"` // Valid is true if TeamRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamRole) Scan(value interface{}) error {
	if value == nil {
		ns.TeamRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamRole), nil
}

func (e TeamRole) Valid() bool {
	switch e {
	case TeamRoleManager,
		TeamRoleMember:
		return true
	}
	return false
}

type TicketCategory string

const (
	TicketCategoryUpload TicketCategory = "upload"
	TicketCategoryJudge  TicketCategory = "judge"
	TicketCategoryScore  TicketCategory = "score"
	TicketCategorySystem TicketCategory = "system"
)

func (e *TicketCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketCategory(s)
	case string:
		*e = TicketCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketCategory: %T", src)
	}
	return nil
}

type NullTicketCategory struct {
	TicketCategory TicketCategory `json:"ticket_category"`
	Valid          bool           `json:"valid"` // Valid is true if TicketCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketCategory) Scan(value interface{}) error {
	if value == nil {
		ns.TicketCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketCategory), nil
}

func (e TicketCategory) Valid() bool {
	switch e {
	case TicketCategoryUpload,
		TicketCategoryJudge,
		TicketCategoryScore,
		TicketCategorySystem:
		return true
	}
	return false
}

type TicketPriority string

const (
	TicketPriorityLow    TicketPriority = "low"
	TicketPriorityNormal TicketPriority = "normal"
	TicketPriorityHigh   TicketPriority = "high"
	TicketPriorityUrgent TicketPriority = "urgent"
)

func (e *TicketPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketPriority(s)
	case string:
		*e = TicketPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketPriority: %T", src)
	}
	return nil
}

type NullTicketPriority struct {
	TicketPriority TicketPriority `json:"ticket_priority"`
	Valid          bool           `json:"valid"` // Valid is true if TicketPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TicketPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketPriority), nil
}

func (e TicketPriority) Valid() bool {
	switch e {
	case TicketPriorityLow,
		TicketPriorityNormal,
		TicketPriorityHigh,
		TicketPriorityUrgent:
		return true
	}
	return false
}

type TicketStatus string

const (
	TicketStatusOpen       TicketStatus = "open"
	TicketStatusInProgress TicketStatus = "in_progress"
	TicketStatusResolved   TicketStatus = "resolved"
	TicketStatusRejected   TicketStatus = "rejected"
)

func (e *TicketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketStatus(s)
	case string:
		*e = TicketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketStatus: %T", src)
	}
	return nil
}

type NullTicketStatus struct {
	TicketStatus TicketStatus `json:"ticket_status"`
	Valid        bool         `json:"valid"` // Valid is true if TicketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketStatus), nil
}

func (e TicketStatus) Valid() bool {
	switch e {
	case TicketStatusOpen,
		TicketStatusInProgress,
		TicketStatusResolved,
		TicketStatusRejected:
		return true
	}
	return false
}

type UserRole string

const (
	UserRoleContestant UserRole = "contestant"
	UserRoleJury       UserRole = "jury"
	UserRoleAdmin      UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

func (e UserRole) Valid() bool {
	switch e {
	case UserRoleContestant,
		UserRoleJury,
		UserRoleAdmin:
		return true
	}
	return false
}

type Announcement struct {
	ID        uuid.UUID          `json:"id"`
	ContestID uuid.UUID          `json:"contest_id"`
	TaskID    pgtype.UUID        `json:"task_id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	IsPinned  bool               `json:"is_pinned"`
	IsPublic  bool               `json:"is_public"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Clarification struct {
	ID             uuid.UUID           `json:"id"`
	ContestID      uuid.UUID           `json:"contest_id"`
	TaskID         pgtype.UUID         `json:"task_id"`
	PhaseID        pgtype.UUID         `json:"phase_id"`
	ContestEntryID uuid.UUID           `json:"contest_entry_id"`
	Question       string              `json:"question"`
	Answer         *string             `json:"answer"`
	IsPublic       bool                `json:"is_public"`
	Status         ClarificationStatus `json:"status"`
	AskedBy        uuid.UUID           `json:"asked_by"`
	AnsweredBy     pgtype.UUID         `json:"answered_by"`
	AnsweredAt     pgtype.Timestamptz  `json:"answered_at"`
	CreatedAt      pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz  `json:"updated_at"`
}

type Contest struct {
	ID                uuid.UUID          `json:"id"`
	Slug              string             `json:"slug"`
	Title             string             `json:"title"`
	Description       *string            `json:"description"`
	BannerUrl         *string            `json:"banner_url"`
	Status            ContestStatus      `json:"status"`
	EntryPolicy       ContestEntryPolicy `json:"entry_policy"`
	RegistrationStart pgtype.Timestamptz `json:"registration_start"`
	RegistrationEnd   pgtype.Timestamptz `json:"registration_end"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	Visibility        ContestVisibility  `json:"visibility"`
	RulesJson         []byte             `json:"rules_json"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	MaxTeamSize       int32              `json:"max_team_size"`
	RequireApproval   bool               `json:"require_approval"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ContestEntry struct {
	ID           uuid.UUID          `json:"id"`
	ContestID    uuid.UUID          `json:"contest_id"`
	EntryType    EntryType          `json:"entry_type"`
	EntryMode    EntryMode          `json:"entry_mode"`
	UserID       pgtype.UUID        `json:"user_id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	DisplayName  string             `json:"display_name"`
	Status       EntryStatus        `json:"status"`
	RegisteredBy uuid.UUID          `json:"registered_by"`
	ApprovedBy   pgtype.UUID        `json:"approved_by"`
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
	StartAt      pgtype.Timestamptz `json:"start_at"`
	EndAt        pgtype.Timestamptz `json:"end_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ContestEntryMember struct {
	ContestEntryID uuid.UUID          `json:"contest_entry_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Role           EntryMemberRole    `json:"role"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
}

type ContestPhaseDef struct {
	ID        uuid.UUID       `json:"id"`
	ContestID uuid.UUID       `json:"contest_id"`
	Key       ContestPhaseKey `json:"key"`
	Title     string          `json:"title"`
	SortOrder int32           `json:"sort_order"`
}

type ContestPhaseLeaderboardEntry struct {
	ID                uuid.UUID          `json:"id"`
	ContestID         uuid.UUID          `json:"contest_id"`
	ContestPhaseDefID uuid.UUID          `json:"contest_phase_def_id"`
	ContestEntryID    uuid.UUID          `json:"contest_entry_id"`
	Rank              *int32             `json:"rank"`
	Score             string             `json:"score"`
	ScoreBreakdown    []byte             `json:"score_breakdown"`
	EntriesCount      int32              `json:"entries_count"`
	IsFrozen          bool               `json:"is_frozen"`
	IsDisqualified    bool               `json:"is_disqualified"`
	DqReason          *string            `json:"dq_reason"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type EvaluationJob struct {
	ID              uuid.UUID          `json:"id"`
	SubmissionID    uuid.UUID          `json:"submission_id"`
	JobType         EvalJobType        `json:"job_type"`
	Status          EvalJobStatus      `json:"status"`
	Priority        int32              `json:"priority"`
	WorkerID        *string            `json:"worker_id"`
	AttemptCount    int32              `json:"attempt_count"`
	MaxAttempts     int32              `json:"max_attempts"`
	InputData       []byte             `json:"input_data"`
	OutputData      []byte             `json:"output_data"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	ExecutionTimeMs *int32             `json:"execution_time_ms"`
	ErrorLog        *string            `json:"error_log"`
	ExternalJobID   *string            `json:"external_job_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Phase struct {
	ID                  uuid.UUID          `json:"id"`
	TaskID              uuid.UUID          `json:"task_id"`
	ContestPhaseDefID   uuid.UUID          `json:"contest_phase_def_id"`
	Slug                string             `json:"slug"`
	Title               string             `json:"title"`
	Description         *string            `json:"description"`
	OpenTime            pgtype.Timestamptz `json:"open_time"`
	CloseTime           pgtype.Timestamptz `json:"close_time"`
	JudgeKey            string             `json:"judge_key"`
	SubmissionLimit     *int32             `json:"submission_limit"`
	LeaderboardMode     LeaderboardMode    `json:"leaderboard_mode"`
	AllowOfficialSubmit bool               `json:"allow_official_submit"`
	AllowVirtualSubmit  bool               `json:"allow_virtual_submit"`
	AllowPracticeSubmit bool               `json:"allow_practice_submit"`
	DisplayScores       bool               `json:"display_scores"`
	IsFrozen            bool               `json:"is_frozen"`
	IsFinal             bool               `json:"is_final"`
	SortOrder           int32              `json:"sort_order"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Submission struct {
	ID               uuid.UUID          `json:"id"`
	ContestID        uuid.UUID          `json:"contest_id"`
	ContestEntryID   uuid.UUID          `json:"contest_entry_id"`
	TaskID           uuid.UUID          `json:"task_id"`
	PhaseID          uuid.UUID          `json:"phase_id"`
	SubmittedBy      uuid.UUID          `json:"submitted_by"`
	Status           SubmissionStatus   `json:"status"`
	SubmittedAt      pgtype.Timestamptz `json:"submitted_at"`
	FileCount        int32              `json:"file_count"`
	TotalSizeBytes   int64              `json:"total_size_bytes"`
	ManifestHash     *string            `json:"manifest_hash"`
	ValidationResult []byte             `json:"validation_result"`
	ErrorMessage     *string            `json:"error_message"`
	RawScore         pgtype.Numeric     `json:"raw_score"`
	DisplayScore     pgtype.Numeric     `json:"display_score"`
	ScorePayload     []byte             `json:"score_payload"`
	EvaluatedAt      pgtype.Timestamptz `json:"evaluated_at"`
	IsFinal          bool               `json:"is_final"`
	RejudgeCount     int32              `json:"rejudge_count"`
	ClientIp         *string            `json:"client_ip"`
	UserAgent        *string            `json:"user_agent"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type SubmissionFile struct {
	ID               uuid.UUID          `json:"id"`
	SubmissionID     uuid.UUID          `json:"submission_id"`
	OriginalFilename string             `json:"original_filename"`
	StoragePath      string             `json:"storage_path"`
	FileSize         int64              `json:"file_size"`
	ContentType      *string            `json:"content_type"`
	HashSha256       *string            `json:"hash_sha256"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID                  uuid.UUID          `json:"id"`
	ContestID           uuid.UUID          `json:"contest_id"`
	Slug                string             `json:"slug"`
	Title               string             `json:"title"`
	Description         *string            `json:"description"`
	ProblemStatementUrl *string            `json:"problem_statement_url"`
	SubmissionSchema    []byte             `json:"submission_schema"`
	ScoreLabel          string             `json:"score_label"`
	HigherIsBetter      bool               `json:"higher_is_better"`
	SortOrder           int32              `json:"sort_order"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type TaskPhaseLeaderboardEntry struct {
	ID                 uuid.UUID          `json:"id"`
	ContestID          uuid.UUID          `json:"contest_id"`
	TaskID             uuid.UUID          `json:"task_id"`
	PhaseID            uuid.UUID          `json:"phase_id"`
	ContestEntryID     uuid.UUID          `json:"contest_entry_id"`
	Rank               *int32             `json:"rank"`
	Score              string             `json:"score"`
	ScoreBreakdown     []byte             `json:"score_breakdown"`
	ChosenSubmissionID pgtype.UUID        `json:"chosen_submission_id"`
	EntriesCount       int32              `json:"entries_count"`
	IsFrozen           bool               `json:"is_frozen"`
	IsDisqualified     bool               `json:"is_disqualified"`
	DqReason           *string            `json:"dq_reason"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Team struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	OwnerID   uuid.UUID          `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TeamMember struct {
	TeamID   uuid.UUID          `json:"team_id"`
	UserID   uuid.UUID          `json:"user_id"`
	Role     TeamRole           `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type Ticket struct {
	ID             uuid.UUID          `json:"id"`
	SubmissionID   pgtype.UUID        `json:"submission_id"`
	ContestEntryID uuid.UUID          `json:"contest_entry_id"`
	Category       TicketCategory     `json:"category"`
	Subject        string             `json:"subject"`
	Description    string             `json:"description"`
	Status         TicketStatus       `json:"status"`
	Priority       TicketPriority     `json:"priority"`
	AssignedTo     pgtype.UUID        `json:"assigned_to"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Role         UserRole           `json:"role"`
	StudentID    *string            `json:"student_id"`
	AvatarUrl    *string            `json:"avatar_url"`
	LastVisit    pgtype.Timestamptz `json:"last_visit"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
