// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phases.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPhase = `-- name: CreatePhase :one
INSERT INTO phases (
  task_id, contest_phase_def_id, slug, title, description,
  open_time, close_time, judge_key, submission_limit,
  leaderboard_mode, allow_official_submit, allow_virtual_submit,
  allow_practice_submit, display_scores, is_frozen, is_final, sort_order
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, task_id, contest_phase_def_id, slug, title, description, open_time, close_time, judge_key, submission_limit, leaderboard_mode, allow_official_submit, allow_virtual_submit, allow_practice_submit, display_scores, is_frozen, is_final, sort_order, created_at, updated_at
`

type CreatePhaseParams struct {
	TaskID              uuid.UUID          `json:"task_id"`
	ContestPhaseDefID   uuid.UUID          `json:"contest_phase_def_id"`
	Slug                string             `json:"slug"`
	Title               string             `json:"title"`
	Description         *string            `json:"description"`
	OpenTime            pgtype.Timestamptz `json:"open_time"`
	CloseTime           pgtype.Timestamptz `json:"close_time"`
	JudgeKey            string             `json:"judge_key"`
	SubmissionLimit     *int32             `json:"submission_limit"`
	LeaderboardMode     LeaderboardMode    `json:"leaderboard_mode"`
	AllowOfficialSubmit bool               `json:"allow_official_submit"`
	AllowVirtualSubmit  bool               `json:"allow_virtual_submit"`
	AllowPracticeSubmit bool               `json:"allow_practice_submit"`
	DisplayScores       bool               `json:"display_scores"`
	IsFrozen            bool               `json:"is_frozen"`
	IsFinal             bool               `json:"is_final"`
	SortOrder           int32              `json:"sort_order"`
}

func (q *Queries) CreatePhase(ctx context.Context, arg CreatePhaseParams) (Phase, error) {
	row := q.db.QueryRow(ctx, createPhase,
		arg.TaskID,
		arg.ContestPhaseDefID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.OpenTime,
		arg.CloseTime,
		arg.JudgeKey,
		arg.SubmissionLimit,
		arg.LeaderboardMode,
		arg.AllowOfficialSubmit,
		arg.AllowVirtualSubmit,
		arg.AllowPracticeSubmit,
		arg.DisplayScores,
		arg.IsFrozen,
		arg.IsFinal,
		arg.SortOrder,
	)
	var i Phase
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ContestPhaseDefID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.OpenTime,
		&i.CloseTime,
		&i.JudgeKey,
		&i.SubmissionLimit,
		&i.LeaderboardMode,
		&i.AllowOfficialSubmit,
		&i.AllowVirtualSubmit,
		&i.AllowPracticeSubmit,
		&i.DisplayScores,
		&i.IsFrozen,
		&i.IsFinal,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePhase = `-- name: DeletePhase :exec
DELETE FROM phases WHERE id = $1
`

func (q *Queries) DeletePhase(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePhase, id)
	return err
}

const getPhaseByID = `-- name: GetPhaseByID :one
SELECT id, task_id, contest_phase_def_id, slug, title, description, open_time, close_time, judge_key, submission_limit, leaderboard_mode, allow_official_submit, allow_virtual_submit, allow_practice_submit, display_scores, is_frozen, is_final, sort_order, created_at, updated_at FROM phases WHERE id = $1
`

func (q *Queries) GetPhaseByID(ctx context.Context, id uuid.UUID) (Phase, error) {
	row := q.db.QueryRow(ctx, getPhaseByID, id)
	var i Phase
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ContestPhaseDefID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.OpenTime,
		&i.CloseTime,
		&i.JudgeKey,
		&i.SubmissionLimit,
		&i.LeaderboardMode,
		&i.AllowOfficialSubmit,
		&i.AllowVirtualSubmit,
		&i.AllowPracticeSubmit,
		&i.DisplayScores,
		&i.IsFrozen,
		&i.IsFinal,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPhasesByTask = `-- name: ListPhasesByTask :many
SELECT id, task_id, contest_phase_def_id, slug, title, description, open_time, close_time, judge_key, submission_limit, leaderboard_mode, allow_official_submit, allow_virtual_submit, allow_practice_submit, display_scores, is_frozen, is_final, sort_order, created_at, updated_at FROM phases WHERE task_id = $1 ORDER BY sort_order
`

func (q *Queries) ListPhasesByTask(ctx context.Context, taskID uuid.UUID) ([]Phase, error) {
	rows, err := q.db.Query(ctx, listPhasesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Phase
	for rows.Next() {
		var i Phase
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ContestPhaseDefID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.OpenTime,
			&i.CloseTime,
			&i.JudgeKey,
			&i.SubmissionLimit,
			&i.LeaderboardMode,
			&i.AllowOfficialSubmit,
			&i.AllowVirtualSubmit,
			&i.AllowPracticeSubmit,
			&i.DisplayScores,
			&i.IsFrozen,
			&i.IsFinal,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPhaseFrozen = `-- name: SetPhaseFrozen :one
UPDATE phases SET is_frozen = $2, updated_at = now() WHERE id = $1 RETURNING id, task_id, contest_phase_def_id, slug, title, description, open_time, close_time, judge_key, submission_limit, leaderboard_mode, allow_official_submit, allow_virtual_submit, allow_practice_submit, display_scores, is_frozen, is_final, sort_order, created_at, updated_at
`

type SetPhaseFrozenParams struct {
	ID       uuid.UUID `json:"id"`
	IsFrozen bool      `json:"is_frozen"`
}

func (q *Queries) SetPhaseFrozen(ctx context.Context, arg SetPhaseFrozenParams) (Phase, error) {
	row := q.db.QueryRow(ctx, setPhaseFrozen, arg.ID, arg.IsFrozen)
	var i Phase
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ContestPhaseDefID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.OpenTime,
		&i.CloseTime,
		&i.JudgeKey,
		&i.SubmissionLimit,
		&i.LeaderboardMode,
		&i.AllowOfficialSubmit,
		&i.AllowVirtualSubmit,
		&i.AllowPracticeSubmit,
		&i.DisplayScores,
		&i.IsFrozen,
		&i.IsFinal,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePhase = `-- name: UpdatePhase :one
UPDATE phases SET
  title = COALESCE($2, title),
  description = COALESCE($3, description),
  open_time = COALESCE($4, open_time),
  close_time = COALESCE($5, close_time),
  judge_key = COALESCE($6, judge_key),
  submission_limit = COALESCE($7, submission_limit),
  display_scores = COALESCE($8, display_scores),
  is_frozen = COALESCE($9, is_frozen),
  updated_at = now()
WHERE id = $1
RETURNING id, task_id, contest_phase_def_id, slug, title, description, open_time, close_time, judge_key, submission_limit, leaderboard_mode, allow_official_submit, allow_virtual_submit, allow_practice_submit, display_scores, is_frozen, is_final, sort_order, created_at, updated_at
`

type UpdatePhaseParams struct {
	ID              uuid.UUID          `json:"id"`
	Title           *string            `json:"title"`
	Description     *string            `json:"description"`
	OpenTime        pgtype.Timestamptz `json:"open_time"`
	CloseTime       pgtype.Timestamptz `json:"close_time"`
	JudgeKey        *string            `json:"judge_key"`
	SubmissionLimit *int32             `json:"submission_limit"`
	DisplayScores   *bool              `json:"display_scores"`
	IsFrozen        *bool              `json:"is_frozen"`
}

func (q *Queries) UpdatePhase(ctx context.Context, arg UpdatePhaseParams) (Phase, error) {
	row := q.db.QueryRow(ctx, updatePhase,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.OpenTime,
		arg.CloseTime,
		arg.JudgeKey,
		arg.SubmissionLimit,
		arg.DisplayScores,
		arg.IsFrozen,
	)
	var i Phase
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ContestPhaseDefID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.OpenTime,
		&i.CloseTime,
		&i.JudgeKey,
		&i.SubmissionLimit,
		&i.LeaderboardMode,
		&i.AllowOfficialSubmit,
		&i.AllowVirtualSubmit,
		&i.AllowPracticeSubmit,
		&i.DisplayScores,
		&i.IsFrozen,
		&i.IsFinal,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
