// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phase_defs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPhaseDef = `-- name: CreatePhaseDef :one
INSERT INTO contest_phase_defs (contest_id, key, title, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, contest_id, key, title, sort_order
`

type CreatePhaseDefParams struct {
	ContestID uuid.UUID       `json:"contest_id"`
	Key       ContestPhaseKey `json:"key"`
	Title     string          `json:"title"`
	SortOrder int32           `json:"sort_order"`
}

func (q *Queries) CreatePhaseDef(ctx context.Context, arg CreatePhaseDefParams) (ContestPhaseDef, error) {
	row := q.db.QueryRow(ctx, createPhaseDef,
		arg.ContestID,
		arg.Key,
		arg.Title,
		arg.SortOrder,
	)
	var i ContestPhaseDef
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Key,
		&i.Title,
		&i.SortOrder,
	)
	return i, err
}

const deletePhaseDef = `-- name: DeletePhaseDef :exec
DELETE FROM contest_phase_defs WHERE id = $1
`

func (q *Queries) DeletePhaseDef(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePhaseDef, id)
	return err
}

const getPhaseDefByID = `-- name: GetPhaseDefByID :one
SELECT id, contest_id, key, title, sort_order FROM contest_phase_defs WHERE id = $1
`

func (q *Queries) GetPhaseDefByID(ctx context.Context, id uuid.UUID) (ContestPhaseDef, error) {
	row := q.db.QueryRow(ctx, getPhaseDefByID, id)
	var i ContestPhaseDef
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Key,
		&i.Title,
		&i.SortOrder,
	)
	return i, err
}

const listPhaseDefsByContest = `-- name: ListPhaseDefsByContest :many
SELECT id, contest_id, key, title, sort_order FROM contest_phase_defs
WHERE contest_id = $1
ORDER BY sort_order
`

func (q *Queries) ListPhaseDefsByContest(ctx context.Context, contestID uuid.UUID) ([]ContestPhaseDef, error) {
	rows, err := q.db.Query(ctx, listPhaseDefsByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContestPhaseDef
	for rows.Next() {
		var i ContestPhaseDef
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.Key,
			&i.Title,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePhaseDef = `-- name: UpdatePhaseDef :one
UPDATE contest_phase_defs SET
  title = COALESCE($2, title),
  sort_order = COALESCE($3, sort_order)
WHERE id = $1
RETURNING id, contest_id, key, title, sort_order
`

type UpdatePhaseDefParams struct {
	ID        uuid.UUID `json:"id"`
	Title     *string   `json:"title"`
	SortOrder *int32    `json:"sort_order"`
}

func (q *Queries) UpdatePhaseDef(ctx context.Context, arg UpdatePhaseDefParams) (ContestPhaseDef, error) {
	row := q.db.QueryRow(ctx, updatePhaseDef, arg.ID, arg.Title, arg.SortOrder)
	var i ContestPhaseDef
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Key,
		&i.Title,
		&i.SortOrder,
	)
	return i, err
}
