// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptTeamInvitation(ctx context.Context, arg AcceptTeamInvitationParams) error
	AddEntryMember(ctx context.Context, arg AddEntryMemberParams) error
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	AnswerClarification(ctx context.Context, arg AnswerClarificationParams) (Clarification, error)
	ApproveContestEntry(ctx context.Context, arg ApproveContestEntryParams) (ContestEntry, error)
	ApproveVolunteerWorker(ctx context.Context, arg ApproveVolunteerWorkerParams) (VolunteerWorker, error)
	CountActiveEntries(ctx context.Context) (int64, error)
	CountContests(ctx context.Context) (int64, error)
	CountSubmissions(ctx context.Context) (int64, error)
	CountTasks(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWorkerActiveClaims(ctx context.Context, workerID uuid.UUID) (int64, error)
	CountWorkerActiveClaimsByKind(ctx context.Context, workerID uuid.UUID) (CountWorkerActiveClaimsByKindRow, error)
	// Announcements
	CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error)
	// Clarifications
	CreateClarification(ctx context.Context, arg CreateClarificationParams) (Clarification, error)
	CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error)
	CreateContestEntry(ctx context.Context, arg CreateContestEntryParams) (ContestEntry, error)
	CreateEvaluationSet(ctx context.Context, arg CreateEvaluationSetParams) (TaskEvaluationSet, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreatePhase(ctx context.Context, arg CreatePhaseParams) (Phase, error)
	CreatePhaseDef(ctx context.Context, arg CreatePhaseDefParams) (ContestPhaseDef, error)
	// Creates submission row before file upload completes.
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateSubmissionFile(ctx context.Context, arg CreateSubmissionFileParams) (SubmissionFile, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	// Tickets
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVolunteerWorker(ctx context.Context, arg CreateVolunteerWorkerParams) (VolunteerWorker, error)
	CreateWorkerClaim(ctx context.Context, arg CreateWorkerClaimParams) (VolunteerWorkerClaim, error)
	// Creates a claim with lease + predicted finish time for scheduling.
	CreateWorkerClaimWithFinish(ctx context.Context, arg CreateWorkerClaimWithFinishParams) (VolunteerWorkerClaim, error)
	DeactivateVolunteerWorker(ctx context.Context, id uuid.UUID) (VolunteerWorker, error)
	DeclineTeamInvitation(ctx context.Context, arg DeclineTeamInvitationParams) error
	DeleteAnnouncement(ctx context.Context, id uuid.UUID) error
	DeleteContest(ctx context.Context, id uuid.UUID) error
	DeleteContestEntry(ctx context.Context, id uuid.UUID) error
	DeletePhase(ctx context.Context, id uuid.UUID) error
	DeletePhaseDef(ctx context.Context, id uuid.UUID) error
	// Remove users from global ranking who no longer have any leaderboard entries.
	DeleteStaleGlobalRankings(ctx context.Context, phaseKey ContestPhaseKey) error
	// Batch delete stale claims in one query; RETURNING for re-enqueue loop.
	DeleteStaleWorkerClaims(ctx context.Context, arg DeleteStaleWorkerClaimsParams) ([]DeleteStaleWorkerClaimsRow, error)
	DeleteSubmissionFilesBySubmission(ctx context.Context, submissionID uuid.UUID) error
	DeleteTask(ctx context.Context, id uuid.UUID) error
	DeleteTeam(ctx context.Context, arg DeleteTeamParams) error
	DeleteVolunteerWorker(ctx context.Context, id uuid.UUID) error
	DeleteWorkerClaim(ctx context.Context, arg DeleteWorkerClaimParams) error
	DisqualifyContestEntry(ctx context.Context, id uuid.UUID) (ContestEntry, error)
	// ── Global Best Finish Time Scheduling ──────────────────────────────────────
	// Returns all active workers and when they will next have a free slot.
	// earliest_available_at = now() if worker has free capacity, else min(predicted_finish_at).
	GetAllActiveWorkersWithEarliestAvailable(ctx context.Context) ([]GetAllActiveWorkersWithEarliestAvailableRow, error)
	// Used to seed Redis ZSET on startup from existing DB state.
	GetAllLeaderboardEntriesForPhase(ctx context.Context, phaseID uuid.UUID) ([]GetAllLeaderboardEntriesForPhaseRow, error)
	// Returns the chosen submission_id and its display_score for an entry in a phase.
	GetBestSubmissionForEntry(ctx context.Context, arg GetBestSubmissionForEntryParams) (GetBestSubmissionForEntryRow, error)
	GetClarificationByID(ctx context.Context, id uuid.UUID) (Clarification, error)
	GetContestByID(ctx context.Context, id uuid.UUID) (Contest, error)
	GetContestBySlug(ctx context.Context, slug string) (Contest, error)
	GetContestEntryByID(ctx context.Context, id uuid.UUID) (ContestEntry, error)
	// Contest-phase leaderboard
	GetContestPhaseLeaderboard(ctx context.Context, arg GetContestPhaseLeaderboardParams) ([]GetContestPhaseLeaderboardRow, error)
	// Returns median(error_ratio) for jobs in same group over last 30 days.
	// error_ratio = actual / predicted; ratio > 1 means T0 underestimates.
	// Falls back to 1.0 if fewer than 3 samples (not enough data).
	GetCorrectionFactor(ctx context.Context, arg GetCorrectionFactorParams) (GetCorrectionFactorRow, error)
	GetEvaluationSetByID(ctx context.Context, id uuid.UUID) (TaskEvaluationSet, error)
	GetEvaluationSetByTaskAndKey(ctx context.Context, arg GetEvaluationSetByTaskAndKeyParams) (TaskEvaluationSet, error)
	GetGlobalPhaseRanking(ctx context.Context, arg GetGlobalPhaseRankingParams) ([]GetGlobalPhaseRankingRow, error)
	// Returns p95 observed RAM/VRAM usage for the same semantic phase + finalness.
	GetObservedResourceProfile(ctx context.Context, arg GetObservedResourceProfileParams) (GetObservedResourceProfileRow, error)
	GetPhaseByID(ctx context.Context, id uuid.UUID) (Phase, error)
	GetPhaseDefByID(ctx context.Context, id uuid.UUID) (ContestPhaseDef, error)
	// ── Incremental leaderboard queries (Phase 04) ──────────────────────────────
	// Returns current max display_score among all entries in phase.
	// Used to decide whether incremental or full recompute is needed.
	GetPhaseMaxScore(ctx context.Context, phaseID uuid.UUID) (float64, error)
	GetSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error)
	GetSubmissionForWorker(ctx context.Context, id uuid.UUID) (GetSubmissionForWorkerRow, error)
	GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error)
	// Task-phase leaderboard
	GetTaskPhaseLeaderboard(ctx context.Context, arg GetTaskPhaseLeaderboardParams) ([]GetTaskPhaseLeaderboardRow, error)
	GetTaskSubmissionStats(ctx context.Context) ([]GetTaskSubmissionStatsRow, error)
	GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamBySlug(ctx context.Context, slug string) (Team, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username *string) (User, error)
	GetValidPasswordResetToken(ctx context.Context, token string) (GetValidPasswordResetTokenRow, error)
	GetVolunteerWorkerByID(ctx context.Context, id uuid.UUID) (VolunteerWorker, error)
	GetVolunteerWorkerByToken(ctx context.Context, apiToken *string) (VolunteerWorker, error)
	GetWorkerClaimBySubmission(ctx context.Context, submissionID uuid.UUID) (VolunteerWorkerClaim, error)
	IncrementWorkerCompleted(ctx context.Context, apiToken *string) (VolunteerWorker, error)
	IncrementWorkerFailed(ctx context.Context, apiToken *string) (VolunteerWorker, error)
	IncrementWorkerFailedByID(ctx context.Context, id uuid.UUID) (VolunteerWorker, error)
	InsertJobExecutionLog(ctx context.Context, arg InsertJobExecutionLogParams) error
	InviteTeamMember(ctx context.Context, arg InviteTeamMemberParams) error
	ListAnnouncementsByContest(ctx context.Context, contestID pgtype.UUID) ([]Announcement, error)
	ListClarificationsByContest(ctx context.Context, arg ListClarificationsByContestParams) ([]Clarification, error)
	ListContestEntries(ctx context.Context, arg ListContestEntriesParams) ([]ContestEntry, error)
	ListContests(ctx context.Context, arg ListContestsParams) ([]Contest, error)
	ListEntryMembers(ctx context.Context, contestEntryID uuid.UUID) ([]ListEntryMembersRow, error)
	ListEvaluationSetAssets(ctx context.Context, evaluationSetID uuid.UUID) ([]EvaluationSetAsset, error)
	ListEvaluationSetsByTask(ctx context.Context, taskID uuid.UUID) ([]TaskEvaluationSet, error)
	ListPendingInvitations(ctx context.Context, userID uuid.UUID) ([]ListPendingInvitationsRow, error)
	ListPhaseDefsByContest(ctx context.Context, contestID uuid.UUID) ([]ContestPhaseDef, error)
	ListPhasesByTask(ctx context.Context, taskID uuid.UUID) ([]Phase, error)
	ListRecentJobExecutionLogs(ctx context.Context, limit int32) ([]ListRecentJobExecutionLogsRow, error)
	ListStaleWorkerClaims2(ctx context.Context, claimedAt pgtype.Timestamptz) ([]ListStaleWorkerClaims2Row, error)
	ListSubmissionFilesBySubmission(ctx context.Context, submissionID uuid.UUID) ([]SubmissionFile, error)
	ListSubmissionsByEntry(ctx context.Context, arg ListSubmissionsByEntryParams) ([]Submission, error)
	ListSystemAnnouncements(ctx context.Context) ([]Announcement, error)
	ListTaskAssets(ctx context.Context, taskID uuid.UUID) ([]TaskAsset, error)
	ListTasksByContest(ctx context.Context, contestID uuid.UUID) ([]Task, error)
	ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error)
	ListTeamsByUser(ctx context.Context, userID uuid.UUID) ([]Team, error)
	ListTicketsAll(ctx context.Context, arg ListTicketsAllParams) ([]Ticket, error)
	ListTicketsByUser(ctx context.Context, createdBy uuid.UUID) ([]Ticket, error)
	ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error)
	ListVolunteerWorkers(ctx context.Context) ([]VolunteerWorker, error)
	// ── Engineering optimizations (Phase 06) ────────────────────────────────────
	// Single aggregation to replace N+1 CountWorkerActiveClaims in AdminList.
	ListWorkerActiveClaimCounts(ctx context.Context) ([]ListWorkerActiveClaimCountsRow, error)
	MarkPasswordResetTokenUsed(ctx context.Context, token string) error
	MarkSubmissionDone(ctx context.Context, arg MarkSubmissionDoneParams) (Submission, error)
	MarkSubmissionFailed(ctx context.Context, arg MarkSubmissionFailedParams) (Submission, error)
	MarkSubmissionFinal(ctx context.Context, id uuid.UUID) (Submission, error)
	MarkSubmissionQueued(ctx context.Context, arg MarkSubmissionQueuedParams) (Submission, error)
	MarkSubmissionRequeued(ctx context.Context, id uuid.UUID) (Submission, error)
	MarkSubmissionRunning(ctx context.Context, id uuid.UUID) (Submission, error)
	RecomputeContestPhaseLeaderboard(ctx context.Context, arg RecomputeContestPhaseLeaderboardParams) error
	// Uses leaderboard scores (already scaled). Each user appears once per task
	// with their BEST score across all entries (individual + team), preventing
	// score accumulation for users who joined multiple entries.
	// Uses UPSERT to avoid DELETE-CTE optimization bug in PostgreSQL 12+.
	// Pick best score per (user, task); if same score take earliest (lowest penalty)
	RecomputeGlobalPhaseRanking(ctx context.Context, phaseKey ContestPhaseKey) error
	// penalty_minutes = minutes from contest start to the FIRST submission achieving the best score (ICPC-style).
	RecomputeTaskPhaseLeaderboard(ctx context.Context, arg RecomputeTaskPhaseLeaderboardParams) error
	RejectVolunteerWorker(ctx context.Context, id uuid.UUID) (VolunteerWorker, error)
	RemoveEntryMember(ctx context.Context, arg RemoveEntryMemberParams) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	RenewWorkerClaimLease(ctx context.Context, arg RenewWorkerClaimLeaseParams) (VolunteerWorkerClaim, error)
	ResetOtherFinalSubmissions(ctx context.Context, arg ResetOtherFinalSubmissionsParams) error
	ResolveTicket(ctx context.Context, id uuid.UUID) (Ticket, error)
	SetPhaseFrozen(ctx context.Context, arg SetPhaseFrozenParams) (Phase, error)
	TouchUserLastVisit(ctx context.Context, id uuid.UUID) error
	UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error)
	UpdateClarificationStatus(ctx context.Context, arg UpdateClarificationStatusParams) (Clarification, error)
	UpdateContest(ctx context.Context, arg UpdateContestParams) (Contest, error)
	UpdateContestEntryStatus(ctx context.Context, arg UpdateContestEntryStatusParams) (ContestEntry, error)
	UpdateContestStatus(ctx context.Context, arg UpdateContestStatusParams) (Contest, error)
	UpdatePhase(ctx context.Context, arg UpdatePhaseParams) (Phase, error)
	UpdatePhaseDef(ctx context.Context, arg UpdatePhaseDefParams) (ContestPhaseDef, error)
	// Updates rank/score for one entry (incremental O(log n) path).
	// penalty_minutes is intentionally NOT updated here — only full recompute sets it correctly.
	UpdateSingleLeaderboardEntry(ctx context.Context, arg UpdateSingleLeaderboardEntryParams) error
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error)
	UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) (User, error)
	UpdateWorkerHeartbeat(ctx context.Context, arg UpdateWorkerHeartbeatParams) (VolunteerWorker, error)
	UpsertContestPhaseLeaderboard(ctx context.Context, arg UpsertContestPhaseLeaderboardParams) (ContestPhaseLeaderboardEntry, error)
	UpsertEvaluationSetAsset(ctx context.Context, arg UpsertEvaluationSetAssetParams) (EvaluationSetAsset, error)
	UpsertTaskAsset(ctx context.Context, arg UpsertTaskAssetParams) (TaskAsset, error)
	UpsertTaskPhaseLeaderboard(ctx context.Context, arg UpsertTaskPhaseLeaderboardParams) (TaskPhaseLeaderboardEntry, error)
	// Bounded check: stops scanning after max_workers rows found.
	// Returns true when worker already has max_workers active claims.
	WorkerIsAtCapacity(ctx context.Context, arg WorkerIsAtCapacityParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
