// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddEntryMember(ctx context.Context, arg AddEntryMemberParams) error
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	AnswerClarification(ctx context.Context, arg AnswerClarificationParams) (Clarification, error)
	ApproveContestEntry(ctx context.Context, arg ApproveContestEntryParams) (ContestEntry, error)
	CountActiveEntries(ctx context.Context) (int64, error)
	CountContests(ctx context.Context) (int64, error)
	CountSubmissions(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// Announcements
	CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error)
	// Clarifications
	CreateClarification(ctx context.Context, arg CreateClarificationParams) (Clarification, error)
	CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error)
	CreateContestEntry(ctx context.Context, arg CreateContestEntryParams) (ContestEntry, error)
	CreatePhase(ctx context.Context, arg CreatePhaseParams) (Phase, error)
	CreatePhaseDef(ctx context.Context, arg CreatePhaseDefParams) (ContestPhaseDef, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	// Tickets
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAnnouncement(ctx context.Context, id uuid.UUID) error
	DeleteContest(ctx context.Context, id uuid.UUID) error
	DeleteContestEntry(ctx context.Context, id uuid.UUID) error
	DeletePhase(ctx context.Context, id uuid.UUID) error
	DeletePhaseDef(ctx context.Context, id uuid.UUID) error
	DeleteTask(ctx context.Context, id uuid.UUID) error
	DisqualifyContestEntry(ctx context.Context, id uuid.UUID) (ContestEntry, error)
	GetClarificationByID(ctx context.Context, id uuid.UUID) (Clarification, error)
	GetContestByID(ctx context.Context, id uuid.UUID) (Contest, error)
	GetContestBySlug(ctx context.Context, slug string) (Contest, error)
	GetContestEntryByID(ctx context.Context, id uuid.UUID) (ContestEntry, error)
	// Contest-phase leaderboard
	GetContestPhaseLeaderboard(ctx context.Context, arg GetContestPhaseLeaderboardParams) ([]GetContestPhaseLeaderboardRow, error)
	GetPhaseByID(ctx context.Context, id uuid.UUID) (Phase, error)
	GetSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error)
	GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error)
	// Task-phase leaderboard
	GetTaskPhaseLeaderboard(ctx context.Context, arg GetTaskPhaseLeaderboardParams) ([]GetTaskPhaseLeaderboardRow, error)
	GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamBySlug(ctx context.Context, slug string) (Team, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListAnnouncementsByContest(ctx context.Context, contestID uuid.UUID) ([]Announcement, error)
	ListClarificationsByContest(ctx context.Context, arg ListClarificationsByContestParams) ([]Clarification, error)
	ListContestEntries(ctx context.Context, arg ListContestEntriesParams) ([]ContestEntry, error)
	ListContests(ctx context.Context, arg ListContestsParams) ([]Contest, error)
	ListEntryMembers(ctx context.Context, contestEntryID uuid.UUID) ([]ListEntryMembersRow, error)
	ListPhaseDefsByContest(ctx context.Context, contestID uuid.UUID) ([]ContestPhaseDef, error)
	ListPhasesByTask(ctx context.Context, taskID uuid.UUID) ([]Phase, error)
	ListSubmissionsByEntry(ctx context.Context, arg ListSubmissionsByEntryParams) ([]Submission, error)
	ListTasksByContest(ctx context.Context, contestID uuid.UUID) ([]Task, error)
	ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error)
	ListTeamsByUser(ctx context.Context, userID uuid.UUID) ([]Team, error)
	ListTicketsAll(ctx context.Context, arg ListTicketsAllParams) ([]Ticket, error)
	ListTicketsByUser(ctx context.Context, createdBy uuid.UUID) ([]Ticket, error)
	ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error)
	MarkSubmissionFinal(ctx context.Context, id uuid.UUID) (Submission, error)
	RemoveEntryMember(ctx context.Context, arg RemoveEntryMemberParams) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	ResolveTicket(ctx context.Context, id uuid.UUID) (Ticket, error)
	SetPhaseFrozen(ctx context.Context, arg SetPhaseFrozenParams) (Phase, error)
	TouchUserLastVisit(ctx context.Context, id uuid.UUID) error
	UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error)
	UpdateClarificationStatus(ctx context.Context, arg UpdateClarificationStatusParams) (Clarification, error)
	UpdateContest(ctx context.Context, arg UpdateContestParams) (Contest, error)
	UpdateContestEntryStatus(ctx context.Context, arg UpdateContestEntryStatusParams) (ContestEntry, error)
	UpdateContestStatus(ctx context.Context, arg UpdateContestStatusParams) (Contest, error)
	UpdatePhase(ctx context.Context, arg UpdatePhaseParams) (Phase, error)
	UpdatePhaseDef(ctx context.Context, arg UpdatePhaseDefParams) (ContestPhaseDef, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error)
	UpsertContestPhaseLeaderboard(ctx context.Context, arg UpsertContestPhaseLeaderboardParams) (ContestPhaseLeaderboardEntry, error)
	UpsertTaskPhaseLeaderboard(ctx context.Context, arg UpsertTaskPhaseLeaderboardParams) (TaskPhaseLeaderboardEntry, error)
}

var _ Querier = (*Queries)(nil)
