// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddEntryMember(ctx context.Context, arg AddEntryMemberParams) error
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	AnswerClarification(ctx context.Context, arg AnswerClarificationParams) (Clarification, error)
	ApproveContestEntry(ctx context.Context, arg ApproveContestEntryParams) (ContestEntry, error)
	ApproveVolunteerWorker(ctx context.Context, arg ApproveVolunteerWorkerParams) (VolunteerWorker, error)
	CountActiveEntries(ctx context.Context) (int64, error)
	CountContests(ctx context.Context) (int64, error)
	CountSubmissions(ctx context.Context) (int64, error)
	CountTasks(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWorkerActiveClaims(ctx context.Context, workerID uuid.UUID) (int64, error)
	// Announcements
	CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error)
	// Clarifications
	CreateClarification(ctx context.Context, arg CreateClarificationParams) (Clarification, error)
	CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error)
	CreateContestEntry(ctx context.Context, arg CreateContestEntryParams) (ContestEntry, error)
	CreateEvaluationSet(ctx context.Context, arg CreateEvaluationSetParams) (TaskEvaluationSet, error)
	CreatePhase(ctx context.Context, arg CreatePhaseParams) (Phase, error)
	CreatePhaseDef(ctx context.Context, arg CreatePhaseDefParams) (ContestPhaseDef, error)
	// Creates submission row before file upload completes.
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateSubmissionFile(ctx context.Context, arg CreateSubmissionFileParams) (SubmissionFile, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	// Tickets
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVolunteerWorker(ctx context.Context, arg CreateVolunteerWorkerParams) (VolunteerWorker, error)
	CreateWorkerClaim(ctx context.Context, arg CreateWorkerClaimParams) (VolunteerWorkerClaim, error)
	DeactivateVolunteerWorker(ctx context.Context, id uuid.UUID) (VolunteerWorker, error)
	DeleteAnnouncement(ctx context.Context, id uuid.UUID) error
	DeleteContest(ctx context.Context, id uuid.UUID) error
	DeleteContestEntry(ctx context.Context, id uuid.UUID) error
	DeletePhase(ctx context.Context, id uuid.UUID) error
	DeletePhaseDef(ctx context.Context, id uuid.UUID) error
	// Batch delete all stale claims in one query; RETURNING for re-enqueue loop.
	DeleteStaleWorkerClaims(ctx context.Context, claimedAt pgtype.Timestamptz) ([]DeleteStaleWorkerClaimsRow, error)
	DeleteSubmissionFilesBySubmission(ctx context.Context, submissionID uuid.UUID) error
	DeleteTask(ctx context.Context, id uuid.UUID) error
	DeleteVolunteerWorker(ctx context.Context, id uuid.UUID) error
	DeleteWorkerClaim(ctx context.Context, arg DeleteWorkerClaimParams) error
	DisqualifyContestEntry(ctx context.Context, id uuid.UUID) (ContestEntry, error)
	// Used to seed Redis ZSET on startup from existing DB state.
	GetAllLeaderboardEntriesForPhase(ctx context.Context, phaseID uuid.UUID) ([]GetAllLeaderboardEntriesForPhaseRow, error)
	// Returns the chosen submission_id and its display_score for an entry in a phase.
	GetBestSubmissionForEntry(ctx context.Context, arg GetBestSubmissionForEntryParams) (GetBestSubmissionForEntryRow, error)
	GetClarificationByID(ctx context.Context, id uuid.UUID) (Clarification, error)
	GetContestByID(ctx context.Context, id uuid.UUID) (Contest, error)
	GetContestBySlug(ctx context.Context, slug string) (Contest, error)
	GetContestEntryByID(ctx context.Context, id uuid.UUID) (ContestEntry, error)
	// Contest-phase leaderboard
	GetContestPhaseLeaderboard(ctx context.Context, arg GetContestPhaseLeaderboardParams) ([]GetContestPhaseLeaderboardRow, error)
	// Returns median(error_ratio) for jobs in same group over last 7 days.
	// error_ratio = actual / predicted; ratio > 1 means T0 underestimates.
	// Falls back to 1.0 if fewer than 3 samples (not enough data).
	GetCorrectionFactor(ctx context.Context, arg GetCorrectionFactorParams) (GetCorrectionFactorRow, error)
	GetEvaluationSetByID(ctx context.Context, id uuid.UUID) (TaskEvaluationSet, error)
	GetEvaluationSetByTaskAndKey(ctx context.Context, arg GetEvaluationSetByTaskAndKeyParams) (TaskEvaluationSet, error)
	GetPhaseByID(ctx context.Context, id uuid.UUID) (Phase, error)
	GetPhaseDefByID(ctx context.Context, id uuid.UUID) (ContestPhaseDef, error)
	// ── Incremental leaderboard queries (Phase 04) ──────────────────────────────
	// Returns current max display_score among all entries in phase.
	// Used to decide whether incremental or full recompute is needed.
	GetPhaseMaxScore(ctx context.Context, phaseID uuid.UUID) (float64, error)
	GetSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error)
	GetSubmissionForWorker(ctx context.Context, id uuid.UUID) (GetSubmissionForWorkerRow, error)
	GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error)
	// Task-phase leaderboard
	GetTaskPhaseLeaderboard(ctx context.Context, arg GetTaskPhaseLeaderboardParams) ([]GetTaskPhaseLeaderboardRow, error)
	GetTaskSubmissionStats(ctx context.Context) ([]GetTaskSubmissionStatsRow, error)
	GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamBySlug(ctx context.Context, slug string) (Team, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetVolunteerWorkerByID(ctx context.Context, id uuid.UUID) (VolunteerWorker, error)
	GetVolunteerWorkerByToken(ctx context.Context, apiToken *string) (VolunteerWorker, error)
	GetWorkerClaimBySubmission(ctx context.Context, submissionID uuid.UUID) (VolunteerWorkerClaim, error)
	IncrementWorkerCompleted(ctx context.Context, apiToken *string) (VolunteerWorker, error)
	IncrementWorkerFailed(ctx context.Context, apiToken *string) (VolunteerWorker, error)
	IncrementWorkerFailedByID(ctx context.Context, id uuid.UUID) (VolunteerWorker, error)
	InsertJobExecutionLog(ctx context.Context, arg InsertJobExecutionLogParams) error
	ListAnnouncementsByContest(ctx context.Context, contestID pgtype.UUID) ([]Announcement, error)
	ListClarificationsByContest(ctx context.Context, arg ListClarificationsByContestParams) ([]Clarification, error)
	ListContestEntries(ctx context.Context, arg ListContestEntriesParams) ([]ContestEntry, error)
	ListContests(ctx context.Context, arg ListContestsParams) ([]Contest, error)
	ListEntryMembers(ctx context.Context, contestEntryID uuid.UUID) ([]ListEntryMembersRow, error)
	ListEvaluationSetAssets(ctx context.Context, evaluationSetID uuid.UUID) ([]EvaluationSetAsset, error)
	ListEvaluationSetsByTask(ctx context.Context, taskID uuid.UUID) ([]TaskEvaluationSet, error)
	ListPhaseDefsByContest(ctx context.Context, contestID uuid.UUID) ([]ContestPhaseDef, error)
	ListPhasesByTask(ctx context.Context, taskID uuid.UUID) ([]Phase, error)
	ListStaleWorkerClaims2(ctx context.Context, claimedAt pgtype.Timestamptz) ([]ListStaleWorkerClaims2Row, error)
	ListSubmissionFilesBySubmission(ctx context.Context, submissionID uuid.UUID) ([]SubmissionFile, error)
	ListSubmissionsByEntry(ctx context.Context, arg ListSubmissionsByEntryParams) ([]Submission, error)
	ListSystemAnnouncements(ctx context.Context) ([]Announcement, error)
	ListTaskAssets(ctx context.Context, taskID uuid.UUID) ([]TaskAsset, error)
	ListTasksByContest(ctx context.Context, contestID uuid.UUID) ([]Task, error)
	ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error)
	ListTeamsByUser(ctx context.Context, userID uuid.UUID) ([]Team, error)
	ListTicketsAll(ctx context.Context, arg ListTicketsAllParams) ([]Ticket, error)
	ListTicketsByUser(ctx context.Context, createdBy uuid.UUID) ([]Ticket, error)
	ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error)
	ListVolunteerWorkers(ctx context.Context) ([]VolunteerWorker, error)
	// ── Engineering optimizations (Phase 06) ────────────────────────────────────
	// Single aggregation to replace N+1 CountWorkerActiveClaims in AdminList.
	ListWorkerActiveClaimCounts(ctx context.Context) ([]ListWorkerActiveClaimCountsRow, error)
	MarkSubmissionDone(ctx context.Context, arg MarkSubmissionDoneParams) (Submission, error)
	MarkSubmissionFailed(ctx context.Context, arg MarkSubmissionFailedParams) (Submission, error)
	MarkSubmissionFinal(ctx context.Context, id uuid.UUID) (Submission, error)
	MarkSubmissionQueued(ctx context.Context, arg MarkSubmissionQueuedParams) (Submission, error)
	MarkSubmissionRunning(ctx context.Context, id uuid.UUID) (Submission, error)
	RecomputeContestPhaseLeaderboard(ctx context.Context, arg RecomputeContestPhaseLeaderboardParams) error
	RecomputeTaskPhaseLeaderboard(ctx context.Context, arg RecomputeTaskPhaseLeaderboardParams) error
	RejectVolunteerWorker(ctx context.Context, id uuid.UUID) (VolunteerWorker, error)
	RemoveEntryMember(ctx context.Context, arg RemoveEntryMemberParams) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	ResetOtherFinalSubmissions(ctx context.Context, arg ResetOtherFinalSubmissionsParams) error
	ResolveTicket(ctx context.Context, id uuid.UUID) (Ticket, error)
	SetPhaseFrozen(ctx context.Context, arg SetPhaseFrozenParams) (Phase, error)
	TouchUserLastVisit(ctx context.Context, id uuid.UUID) error
	UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error)
	UpdateClarificationStatus(ctx context.Context, arg UpdateClarificationStatusParams) (Clarification, error)
	UpdateContest(ctx context.Context, arg UpdateContestParams) (Contest, error)
	UpdateContestEntryStatus(ctx context.Context, arg UpdateContestEntryStatusParams) (ContestEntry, error)
	UpdateContestStatus(ctx context.Context, arg UpdateContestStatusParams) (Contest, error)
	UpdatePhase(ctx context.Context, arg UpdatePhaseParams) (Phase, error)
	UpdatePhaseDef(ctx context.Context, arg UpdatePhaseDefParams) (ContestPhaseDef, error)
	// Updates one entry after incremental recompute (O(log n) path).
	UpdateSingleLeaderboardEntry(ctx context.Context, arg UpdateSingleLeaderboardEntryParams) error
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error)
	UpdateWorkerHeartbeat(ctx context.Context, arg UpdateWorkerHeartbeatParams) (VolunteerWorker, error)
	UpsertContestPhaseLeaderboard(ctx context.Context, arg UpsertContestPhaseLeaderboardParams) (ContestPhaseLeaderboardEntry, error)
	UpsertEvaluationSetAsset(ctx context.Context, arg UpsertEvaluationSetAssetParams) (EvaluationSetAsset, error)
	UpsertTaskAsset(ctx context.Context, arg UpsertTaskAssetParams) (TaskAsset, error)
	UpsertTaskPhaseLeaderboard(ctx context.Context, arg UpsertTaskPhaseLeaderboardParams) (TaskPhaseLeaderboardEntry, error)
	// Bounded check: stops scanning after max_workers rows found.
	// Returns true when worker already has max_workers active claims.
	WorkerIsAtCapacity(ctx context.Context, arg WorkerIsAtCapacityParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
