// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countTasks = `-- name: CountTasks :one
SELECT count(*) FROM tasks
`

func (q *Queries) CountTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTaskSubmissionStats = `-- name: GetTaskSubmissionStats :many
SELECT
  s.task_id,
  count(*)::bigint AS total_submissions,
  count(*) FILTER (WHERE s.status = 'done')::bigint AS done_submissions,
  count(DISTINCT s.contest_entry_id) FILTER (WHERE s.status = 'done')::bigint AS solved_entries
FROM submissions s
JOIN tasks t ON t.id = s.task_id
JOIN contests c ON c.id = t.contest_id
WHERE c.visibility = 'public'
GROUP BY s.task_id
`

type GetTaskSubmissionStatsRow struct {
	TaskID           uuid.UUID `json:"task_id"`
	TotalSubmissions int64     `json:"total_submissions"`
	DoneSubmissions  int64     `json:"done_submissions"`
	SolvedEntries    int64     `json:"solved_entries"`
}

func (q *Queries) GetTaskSubmissionStats(ctx context.Context) ([]GetTaskSubmissionStatsRow, error) {
	rows, err := q.db.Query(ctx, getTaskSubmissionStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskSubmissionStatsRow
	for rows.Next() {
		var i GetTaskSubmissionStatsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.TotalSubmissions,
			&i.DoneSubmissions,
			&i.SolvedEntries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
