// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submissions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSubmissionsByEntryPhase = `-- name: CountSubmissionsByEntryPhase :one
SELECT COUNT(*)::int FROM submissions
WHERE contest_entry_id = $1 AND task_id = $2 AND phase_id = $3
`

type CountSubmissionsByEntryPhaseParams struct {
	ContestEntryID uuid.UUID `json:"contest_entry_id"`
	TaskID         uuid.UUID `json:"task_id"`
	PhaseID        uuid.UUID `json:"phase_id"`
}

func (q *Queries) CountSubmissionsByEntryPhase(ctx context.Context, arg CountSubmissionsByEntryPhaseParams) (int32, error) {
	row := q.db.QueryRow(ctx, countSubmissionsByEntryPhase, arg.ContestEntryID, arg.TaskID, arg.PhaseID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (
  contest_id, contest_entry_id, task_id, phase_id, submitted_by,
  status, file_count, total_size_bytes, manifest_hash, client_ip, user_agent
) VALUES ($1, $2, $3, $4, $5, 'uploaded', $6, $7, $8, $9, $10)
RETURNING id, contest_id, contest_entry_id, task_id, phase_id, submitted_by, status, submitted_at, file_count, total_size_bytes, manifest_hash, validation_result, error_message, raw_score, display_score, score_payload, evaluated_at, is_final, rejudge_count, client_ip, user_agent, created_at, updated_at
`

type CreateSubmissionParams struct {
	ContestID      uuid.UUID `json:"contest_id"`
	ContestEntryID uuid.UUID `json:"contest_entry_id"`
	TaskID         uuid.UUID `json:"task_id"`
	PhaseID        uuid.UUID `json:"phase_id"`
	SubmittedBy    uuid.UUID `json:"submitted_by"`
	FileCount      int32     `json:"file_count"`
	TotalSizeBytes int64     `json:"total_size_bytes"`
	ManifestHash   *string   `json:"manifest_hash"`
	ClientIp       *string   `json:"client_ip"`
	UserAgent      *string   `json:"user_agent"`
}

// Creates submission row before file upload completes.
func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.ContestID,
		arg.ContestEntryID,
		arg.TaskID,
		arg.PhaseID,
		arg.SubmittedBy,
		arg.FileCount,
		arg.TotalSizeBytes,
		arg.ManifestHash,
		arg.ClientIp,
		arg.UserAgent,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ContestEntryID,
		&i.TaskID,
		&i.PhaseID,
		&i.SubmittedBy,
		&i.Status,
		&i.SubmittedAt,
		&i.FileCount,
		&i.TotalSizeBytes,
		&i.ManifestHash,
		&i.ValidationResult,
		&i.ErrorMessage,
		&i.RawScore,
		&i.DisplayScore,
		&i.ScorePayload,
		&i.EvaluatedAt,
		&i.IsFinal,
		&i.RejudgeCount,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, contest_id, contest_entry_id, task_id, phase_id, submitted_by, status, submitted_at, file_count, total_size_bytes, manifest_hash, validation_result, error_message, raw_score, display_score, score_payload, evaluated_at, is_final, rejudge_count, client_ip, user_agent, created_at, updated_at FROM submissions WHERE id = $1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ContestEntryID,
		&i.TaskID,
		&i.PhaseID,
		&i.SubmittedBy,
		&i.Status,
		&i.SubmittedAt,
		&i.FileCount,
		&i.TotalSizeBytes,
		&i.ManifestHash,
		&i.ValidationResult,
		&i.ErrorMessage,
		&i.RawScore,
		&i.DisplayScore,
		&i.ScorePayload,
		&i.EvaluatedAt,
		&i.IsFinal,
		&i.RejudgeCount,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionForWorker = `-- name: GetSubmissionForWorker :one
SELECT s.id, s.contest_id, s.contest_entry_id, s.task_id, s.phase_id,
       p.judge_key, p.contest_phase_def_id, p.evaluation_set_id, p.is_final,
       cpd.key AS phase_key,
       t.submission_schema::text AS submission_schema,
       ce.entry_mode,
       s.submitted_at,
       s.total_size_bytes
FROM submissions s
JOIN phases         p  ON p.id  = s.phase_id
JOIN contest_phase_defs cpd ON cpd.id = p.contest_phase_def_id
JOIN tasks          t  ON t.id  = s.task_id
JOIN contest_entries ce ON ce.id = s.contest_entry_id
WHERE s.id = $1
`

type GetSubmissionForWorkerRow struct {
	ID                uuid.UUID          `json:"id"`
	ContestID         uuid.UUID          `json:"contest_id"`
	ContestEntryID    uuid.UUID          `json:"contest_entry_id"`
	TaskID            uuid.UUID          `json:"task_id"`
	PhaseID           uuid.UUID          `json:"phase_id"`
	JudgeKey          string             `json:"judge_key"`
	ContestPhaseDefID uuid.UUID          `json:"contest_phase_def_id"`
	EvaluationSetID   uuid.UUID          `json:"evaluation_set_id"`
	IsFinal           bool               `json:"is_final"`
	PhaseKey          ContestPhaseKey    `json:"phase_key"`
	SubmissionSchema  string             `json:"submission_schema"`
	EntryMode         EntryMode          `json:"entry_mode"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	TotalSizeBytes    int64              `json:"total_size_bytes"`
}

func (q *Queries) GetSubmissionForWorker(ctx context.Context, id uuid.UUID) (GetSubmissionForWorkerRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionForWorker, id)
	var i GetSubmissionForWorkerRow
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ContestEntryID,
		&i.TaskID,
		&i.PhaseID,
		&i.JudgeKey,
		&i.ContestPhaseDefID,
		&i.EvaluationSetID,
		&i.IsFinal,
		&i.PhaseKey,
		&i.SubmissionSchema,
		&i.EntryMode,
		&i.SubmittedAt,
		&i.TotalSizeBytes,
	)
	return i, err
}

const listSubmissionsByEntry = `-- name: ListSubmissionsByEntry :many
SELECT id, contest_id, contest_entry_id, task_id, phase_id, submitted_by, status, submitted_at, file_count, total_size_bytes, manifest_hash, validation_result, error_message, raw_score, display_score, score_payload, evaluated_at, is_final, rejudge_count, client_ip, user_agent, created_at, updated_at FROM submissions
WHERE contest_entry_id = $1
  AND ($4::uuid IS NULL OR task_id = $4)
  AND ($5::uuid IS NULL OR phase_id = $5)
ORDER BY submitted_at DESC
LIMIT $2 OFFSET $3
`

type ListSubmissionsByEntryParams struct {
	ContestEntryID uuid.UUID   `json:"contest_entry_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
	TaskID         pgtype.UUID `json:"task_id"`
	PhaseID        pgtype.UUID `json:"phase_id"`
}

func (q *Queries) ListSubmissionsByEntry(ctx context.Context, arg ListSubmissionsByEntryParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByEntry,
		arg.ContestEntryID,
		arg.Limit,
		arg.Offset,
		arg.TaskID,
		arg.PhaseID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.ContestEntryID,
			&i.TaskID,
			&i.PhaseID,
			&i.SubmittedBy,
			&i.Status,
			&i.SubmittedAt,
			&i.FileCount,
			&i.TotalSizeBytes,
			&i.ManifestHash,
			&i.ValidationResult,
			&i.ErrorMessage,
			&i.RawScore,
			&i.DisplayScore,
			&i.ScorePayload,
			&i.EvaluatedAt,
			&i.IsFinal,
			&i.RejudgeCount,
			&i.ClientIp,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubmissionDone = `-- name: MarkSubmissionDone :one
UPDATE submissions s
SET status        = 'done',
    raw_score     = $2,
    display_score = $3,
    score_payload = $4::varchar::jsonb,
    evaluated_at  = now(),
    updated_at    = now(),
    error_message = NULL
WHERE s.id = $1
  AND s.status = 'running'
  AND EXISTS (
    SELECT 1
    FROM volunteer_worker_claims c
    WHERE c.submission_id = s.id
      AND c.worker_id = $5
      AND c.attempt_id = $6
  )
RETURNING id, contest_id, contest_entry_id, task_id, phase_id, submitted_by, status, submitted_at, file_count, total_size_bytes, manifest_hash, validation_result, error_message, raw_score, display_score, score_payload, evaluated_at, is_final, rejudge_count, client_ip, user_agent, created_at, updated_at
`

type MarkSubmissionDoneParams struct {
	ID           uuid.UUID      `json:"id"`
	RawScore     pgtype.Numeric `json:"raw_score"`
	DisplayScore pgtype.Numeric `json:"display_score"`
	Column4      string         `json:"column_4"`
	WorkerID     uuid.UUID      `json:"worker_id"`
	AttemptID    uuid.UUID      `json:"attempt_id"`
}

func (q *Queries) MarkSubmissionDone(ctx context.Context, arg MarkSubmissionDoneParams) (Submission, error) {
	row := q.db.QueryRow(ctx, markSubmissionDone,
		arg.ID,
		arg.RawScore,
		arg.DisplayScore,
		arg.Column4,
		arg.WorkerID,
		arg.AttemptID,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ContestEntryID,
		&i.TaskID,
		&i.PhaseID,
		&i.SubmittedBy,
		&i.Status,
		&i.SubmittedAt,
		&i.FileCount,
		&i.TotalSizeBytes,
		&i.ManifestHash,
		&i.ValidationResult,
		&i.ErrorMessage,
		&i.RawScore,
		&i.DisplayScore,
		&i.ScorePayload,
		&i.EvaluatedAt,
		&i.IsFinal,
		&i.RejudgeCount,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSubmissionFailed = `-- name: MarkSubmissionFailed :one
UPDATE submissions s
SET status        = 'failed',
    error_message = $2,
    updated_at    = now()
WHERE s.id = $1
  AND s.status = 'running'
  AND EXISTS (
    SELECT 1
    FROM volunteer_worker_claims c
    WHERE c.submission_id = s.id
      AND c.worker_id = $3
      AND c.attempt_id = $4
  )
RETURNING id, contest_id, contest_entry_id, task_id, phase_id, submitted_by, status, submitted_at, file_count, total_size_bytes, manifest_hash, validation_result, error_message, raw_score, display_score, score_payload, evaluated_at, is_final, rejudge_count, client_ip, user_agent, created_at, updated_at
`

type MarkSubmissionFailedParams struct {
	ID           uuid.UUID `json:"id"`
	ErrorMessage *string   `json:"error_message"`
	WorkerID     uuid.UUID `json:"worker_id"`
	AttemptID    uuid.UUID `json:"attempt_id"`
}

func (q *Queries) MarkSubmissionFailed(ctx context.Context, arg MarkSubmissionFailedParams) (Submission, error) {
	row := q.db.QueryRow(ctx, markSubmissionFailed,
		arg.ID,
		arg.ErrorMessage,
		arg.WorkerID,
		arg.AttemptID,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ContestEntryID,
		&i.TaskID,
		&i.PhaseID,
		&i.SubmittedBy,
		&i.Status,
		&i.SubmittedAt,
		&i.FileCount,
		&i.TotalSizeBytes,
		&i.ManifestHash,
		&i.ValidationResult,
		&i.ErrorMessage,
		&i.RawScore,
		&i.DisplayScore,
		&i.ScorePayload,
		&i.EvaluatedAt,
		&i.IsFinal,
		&i.RejudgeCount,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSubmissionFinal = `-- name: MarkSubmissionFinal :one
UPDATE submissions SET is_final = true, updated_at = now() WHERE id = $1 RETURNING id, contest_id, contest_entry_id, task_id, phase_id, submitted_by, status, submitted_at, file_count, total_size_bytes, manifest_hash, validation_result, error_message, raw_score, display_score, score_payload, evaluated_at, is_final, rejudge_count, client_ip, user_agent, created_at, updated_at
`

func (q *Queries) MarkSubmissionFinal(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, markSubmissionFinal, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ContestEntryID,
		&i.TaskID,
		&i.PhaseID,
		&i.SubmittedBy,
		&i.Status,
		&i.SubmittedAt,
		&i.FileCount,
		&i.TotalSizeBytes,
		&i.ManifestHash,
		&i.ValidationResult,
		&i.ErrorMessage,
		&i.RawScore,
		&i.DisplayScore,
		&i.ScorePayload,
		&i.EvaluatedAt,
		&i.IsFinal,
		&i.RejudgeCount,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSubmissionQueued = `-- name: MarkSubmissionQueued :one
UPDATE submissions
SET status='queued', file_count=$2, total_size_bytes=$3, updated_at=now(), error_message=NULL
WHERE id=$1
RETURNING id, contest_id, contest_entry_id, task_id, phase_id, submitted_by, status, submitted_at, file_count, total_size_bytes, manifest_hash, validation_result, error_message, raw_score, display_score, score_payload, evaluated_at, is_final, rejudge_count, client_ip, user_agent, created_at, updated_at
`

type MarkSubmissionQueuedParams struct {
	ID             uuid.UUID `json:"id"`
	FileCount      int32     `json:"file_count"`
	TotalSizeBytes int64     `json:"total_size_bytes"`
}

func (q *Queries) MarkSubmissionQueued(ctx context.Context, arg MarkSubmissionQueuedParams) (Submission, error) {
	row := q.db.QueryRow(ctx, markSubmissionQueued, arg.ID, arg.FileCount, arg.TotalSizeBytes)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ContestEntryID,
		&i.TaskID,
		&i.PhaseID,
		&i.SubmittedBy,
		&i.Status,
		&i.SubmittedAt,
		&i.FileCount,
		&i.TotalSizeBytes,
		&i.ManifestHash,
		&i.ValidationResult,
		&i.ErrorMessage,
		&i.RawScore,
		&i.DisplayScore,
		&i.ScorePayload,
		&i.EvaluatedAt,
		&i.IsFinal,
		&i.RejudgeCount,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSubmissionRequeued = `-- name: MarkSubmissionRequeued :one
UPDATE submissions
SET status='queued', updated_at=now(), error_message=NULL
WHERE id=$1
  AND status='running'
RETURNING id, contest_id, contest_entry_id, task_id, phase_id, submitted_by, status, submitted_at, file_count, total_size_bytes, manifest_hash, validation_result, error_message, raw_score, display_score, score_payload, evaluated_at, is_final, rejudge_count, client_ip, user_agent, created_at, updated_at
`

func (q *Queries) MarkSubmissionRequeued(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, markSubmissionRequeued, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ContestEntryID,
		&i.TaskID,
		&i.PhaseID,
		&i.SubmittedBy,
		&i.Status,
		&i.SubmittedAt,
		&i.FileCount,
		&i.TotalSizeBytes,
		&i.ManifestHash,
		&i.ValidationResult,
		&i.ErrorMessage,
		&i.RawScore,
		&i.DisplayScore,
		&i.ScorePayload,
		&i.EvaluatedAt,
		&i.IsFinal,
		&i.RejudgeCount,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSubmissionRunning = `-- name: MarkSubmissionRunning :one
UPDATE submissions
SET status = 'running', updated_at = now()
WHERE id = $1
RETURNING id, contest_id, contest_entry_id, task_id, phase_id, submitted_by, status, submitted_at, file_count, total_size_bytes, manifest_hash, validation_result, error_message, raw_score, display_score, score_payload, evaluated_at, is_final, rejudge_count, client_ip, user_agent, created_at, updated_at
`

func (q *Queries) MarkSubmissionRunning(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, markSubmissionRunning, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ContestEntryID,
		&i.TaskID,
		&i.PhaseID,
		&i.SubmittedBy,
		&i.Status,
		&i.SubmittedAt,
		&i.FileCount,
		&i.TotalSizeBytes,
		&i.ManifestHash,
		&i.ValidationResult,
		&i.ErrorMessage,
		&i.RawScore,
		&i.DisplayScore,
		&i.ScorePayload,
		&i.EvaluatedAt,
		&i.IsFinal,
		&i.RejudgeCount,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requeueOrphanRunningSubmissions = `-- name: RequeueOrphanRunningSubmissions :many
WITH orphan AS (
  SELECT s.id
  FROM submissions s
  WHERE s.status = 'running'
    AND s.updated_at < $1
    AND NOT EXISTS (
      SELECT 1
      FROM volunteer_worker_claims c
      WHERE c.submission_id = s.id
    )
  ORDER BY s.updated_at ASC
  LIMIT $2
)
UPDATE submissions s
SET status='queued', updated_at=now(), error_message=NULL
FROM orphan
WHERE s.id = orphan.id
RETURNING s.id, s.contest_id, s.contest_entry_id, s.task_id, s.phase_id, s.submitted_by, s.status, s.submitted_at, s.file_count, s.total_size_bytes, s.manifest_hash, s.validation_result, s.error_message, s.raw_score, s.display_score, s.score_payload, s.evaluated_at, s.is_final, s.rejudge_count, s.client_ip, s.user_agent, s.created_at, s.updated_at
`

type RequeueOrphanRunningSubmissionsParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) RequeueOrphanRunningSubmissions(ctx context.Context, arg RequeueOrphanRunningSubmissionsParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, requeueOrphanRunningSubmissions, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.ContestEntryID,
			&i.TaskID,
			&i.PhaseID,
			&i.SubmittedBy,
			&i.Status,
			&i.SubmittedAt,
			&i.FileCount,
			&i.TotalSizeBytes,
			&i.ManifestHash,
			&i.ValidationResult,
			&i.ErrorMessage,
			&i.RawScore,
			&i.DisplayScore,
			&i.ScorePayload,
			&i.EvaluatedAt,
			&i.IsFinal,
			&i.RejudgeCount,
			&i.ClientIp,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetOtherFinalSubmissions = `-- name: ResetOtherFinalSubmissions :exec
UPDATE submissions
SET is_final = false, updated_at = now()
WHERE contest_entry_id = $1 AND task_id = $2 AND phase_id = $3 AND id != $4
`

type ResetOtherFinalSubmissionsParams struct {
	ContestEntryID uuid.UUID `json:"contest_entry_id"`
	TaskID         uuid.UUID `json:"task_id"`
	PhaseID        uuid.UUID `json:"phase_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) ResetOtherFinalSubmissions(ctx context.Context, arg ResetOtherFinalSubmissionsParams) error {
	_, err := q.db.Exec(ctx, resetOtherFinalSubmissions,
		arg.ContestEntryID,
		arg.TaskID,
		arg.PhaseID,
		arg.ID,
	)
	return err
}
