// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submissions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (
  contest_id, contest_entry_id, task_id, phase_id, submitted_by,
  status, file_count, total_size_bytes, manifest_hash, client_ip, user_agent
) VALUES ($1, $2, $3, $4, $5, 'uploaded', $6, $7, $8, $9, $10)
RETURNING id, contest_id, contest_entry_id, task_id, phase_id, submitted_by, status, submitted_at, file_count, total_size_bytes, manifest_hash, validation_result, error_message, raw_score, display_score, score_payload, evaluated_at, is_final, rejudge_count, client_ip, user_agent, created_at, updated_at
`

type CreateSubmissionParams struct {
	ContestID      uuid.UUID `json:"contest_id"`
	ContestEntryID uuid.UUID `json:"contest_entry_id"`
	TaskID         uuid.UUID `json:"task_id"`
	PhaseID        uuid.UUID `json:"phase_id"`
	SubmittedBy    uuid.UUID `json:"submitted_by"`
	FileCount      int32     `json:"file_count"`
	TotalSizeBytes int64     `json:"total_size_bytes"`
	ManifestHash   *string   `json:"manifest_hash"`
	ClientIp       *string   `json:"client_ip"`
	UserAgent      *string   `json:"user_agent"`
}

// Creates submission row before file upload completes.
func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.ContestID,
		arg.ContestEntryID,
		arg.TaskID,
		arg.PhaseID,
		arg.SubmittedBy,
		arg.FileCount,
		arg.TotalSizeBytes,
		arg.ManifestHash,
		arg.ClientIp,
		arg.UserAgent,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ContestEntryID,
		&i.TaskID,
		&i.PhaseID,
		&i.SubmittedBy,
		&i.Status,
		&i.SubmittedAt,
		&i.FileCount,
		&i.TotalSizeBytes,
		&i.ManifestHash,
		&i.ValidationResult,
		&i.ErrorMessage,
		&i.RawScore,
		&i.DisplayScore,
		&i.ScorePayload,
		&i.EvaluatedAt,
		&i.IsFinal,
		&i.RejudgeCount,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, contest_id, contest_entry_id, task_id, phase_id, submitted_by, status, submitted_at, file_count, total_size_bytes, manifest_hash, validation_result, error_message, raw_score, display_score, score_payload, evaluated_at, is_final, rejudge_count, client_ip, user_agent, created_at, updated_at FROM submissions WHERE id = $1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ContestEntryID,
		&i.TaskID,
		&i.PhaseID,
		&i.SubmittedBy,
		&i.Status,
		&i.SubmittedAt,
		&i.FileCount,
		&i.TotalSizeBytes,
		&i.ManifestHash,
		&i.ValidationResult,
		&i.ErrorMessage,
		&i.RawScore,
		&i.DisplayScore,
		&i.ScorePayload,
		&i.EvaluatedAt,
		&i.IsFinal,
		&i.RejudgeCount,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubmissionsByEntry = `-- name: ListSubmissionsByEntry :many
SELECT id, contest_id, contest_entry_id, task_id, phase_id, submitted_by, status, submitted_at, file_count, total_size_bytes, manifest_hash, validation_result, error_message, raw_score, display_score, score_payload, evaluated_at, is_final, rejudge_count, client_ip, user_agent, created_at, updated_at FROM submissions
WHERE contest_entry_id = $1
  AND ($4::uuid IS NULL OR task_id = $4)
  AND ($5::uuid IS NULL OR phase_id = $5)
ORDER BY submitted_at DESC
LIMIT $2 OFFSET $3
`

type ListSubmissionsByEntryParams struct {
	ContestEntryID uuid.UUID   `json:"contest_entry_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
	TaskID         pgtype.UUID `json:"task_id"`
	PhaseID        pgtype.UUID `json:"phase_id"`
}

func (q *Queries) ListSubmissionsByEntry(ctx context.Context, arg ListSubmissionsByEntryParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByEntry,
		arg.ContestEntryID,
		arg.Limit,
		arg.Offset,
		arg.TaskID,
		arg.PhaseID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.ContestEntryID,
			&i.TaskID,
			&i.PhaseID,
			&i.SubmittedBy,
			&i.Status,
			&i.SubmittedAt,
			&i.FileCount,
			&i.TotalSizeBytes,
			&i.ManifestHash,
			&i.ValidationResult,
			&i.ErrorMessage,
			&i.RawScore,
			&i.DisplayScore,
			&i.ScorePayload,
			&i.EvaluatedAt,
			&i.IsFinal,
			&i.RejudgeCount,
			&i.ClientIp,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubmissionFinal = `-- name: MarkSubmissionFinal :one
UPDATE submissions SET is_final = true, updated_at = now() WHERE id = $1 RETURNING id, contest_id, contest_entry_id, task_id, phase_id, submitted_by, status, submitted_at, file_count, total_size_bytes, manifest_hash, validation_result, error_message, raw_score, display_score, score_payload, evaluated_at, is_final, rejudge_count, client_ip, user_agent, created_at, updated_at
`

func (q *Queries) MarkSubmissionFinal(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, markSubmissionFinal, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ContestEntryID,
		&i.TaskID,
		&i.PhaseID,
		&i.SubmittedBy,
		&i.Status,
		&i.SubmittedAt,
		&i.FileCount,
		&i.TotalSizeBytes,
		&i.ManifestHash,
		&i.ValidationResult,
		&i.ErrorMessage,
		&i.RawScore,
		&i.DisplayScore,
		&i.ScorePayload,
		&i.EvaluatedAt,
		&i.IsFinal,
		&i.RejudgeCount,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSubmissionQueued = `-- name: MarkSubmissionQueued :one
UPDATE submissions
SET status='queued', file_count=$2, total_size_bytes=$3, updated_at=now(), error_message=NULL
WHERE id=$1
RETURNING id, contest_id, contest_entry_id, task_id, phase_id, submitted_by, status, submitted_at, file_count, total_size_bytes, manifest_hash, validation_result, error_message, raw_score, display_score, score_payload, evaluated_at, is_final, rejudge_count, client_ip, user_agent, created_at, updated_at
`

type MarkSubmissionQueuedParams struct {
	ID             uuid.UUID `json:"id"`
	FileCount      int32     `json:"file_count"`
	TotalSizeBytes int64     `json:"total_size_bytes"`
}

func (q *Queries) MarkSubmissionQueued(ctx context.Context, arg MarkSubmissionQueuedParams) (Submission, error) {
	row := q.db.QueryRow(ctx, markSubmissionQueued, arg.ID, arg.FileCount, arg.TotalSizeBytes)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ContestEntryID,
		&i.TaskID,
		&i.PhaseID,
		&i.SubmittedBy,
		&i.Status,
		&i.SubmittedAt,
		&i.FileCount,
		&i.TotalSizeBytes,
		&i.ManifestHash,
		&i.ValidationResult,
		&i.ErrorMessage,
		&i.RawScore,
		&i.DisplayScore,
		&i.ScorePayload,
		&i.EvaluatedAt,
		&i.IsFinal,
		&i.RejudgeCount,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
