// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submission_files.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSubmissionFile = `-- name: CreateSubmissionFile :one
INSERT INTO submission_files (
  submission_id, original_filename, storage_path, file_size, content_type, hash_sha256
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, submission_id, original_filename, storage_path, file_size, content_type, hash_sha256, created_at
`

type CreateSubmissionFileParams struct {
	SubmissionID     uuid.UUID `json:"submission_id"`
	OriginalFilename string    `json:"original_filename"`
	StoragePath      string    `json:"storage_path"`
	FileSize         int64     `json:"file_size"`
	ContentType      *string   `json:"content_type"`
	HashSha256       *string   `json:"hash_sha256"`
}

func (q *Queries) CreateSubmissionFile(ctx context.Context, arg CreateSubmissionFileParams) (SubmissionFile, error) {
	row := q.db.QueryRow(ctx, createSubmissionFile,
		arg.SubmissionID,
		arg.OriginalFilename,
		arg.StoragePath,
		arg.FileSize,
		arg.ContentType,
		arg.HashSha256,
	)
	var i SubmissionFile
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.OriginalFilename,
		&i.StoragePath,
		&i.FileSize,
		&i.ContentType,
		&i.HashSha256,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSubmissionFilesBySubmission = `-- name: DeleteSubmissionFilesBySubmission :exec
DELETE FROM submission_files WHERE submission_id = $1
`

func (q *Queries) DeleteSubmissionFilesBySubmission(ctx context.Context, submissionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubmissionFilesBySubmission, submissionID)
	return err
}

const listSubmissionFilesBySubmission = `-- name: ListSubmissionFilesBySubmission :many
SELECT id, submission_id, original_filename, storage_path, file_size, content_type, hash_sha256, created_at FROM submission_files WHERE submission_id = $1 ORDER BY created_at
`

func (q *Queries) ListSubmissionFilesBySubmission(ctx context.Context, submissionID uuid.UUID) ([]SubmissionFile, error) {
	rows, err := q.db.Query(ctx, listSubmissionFilesBySubmission, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubmissionFile
	for rows.Next() {
		var i SubmissionFile
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.OriginalFilename,
			&i.StoragePath,
			&i.FileSize,
			&i.ContentType,
			&i.HashSha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
