// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_assets.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listTaskAssets = `-- name: ListTaskAssets :many
SELECT id, task_id, asset_key, original_filename, storage_path, file_size, content_type, hash_sha256, created_at, updated_at FROM task_assets WHERE task_id = $1 ORDER BY asset_key
`

func (q *Queries) ListTaskAssets(ctx context.Context, taskID uuid.UUID) ([]TaskAsset, error) {
	rows, err := q.db.Query(ctx, listTaskAssets, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskAsset
	for rows.Next() {
		var i TaskAsset
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AssetKey,
			&i.OriginalFilename,
			&i.StoragePath,
			&i.FileSize,
			&i.ContentType,
			&i.HashSha256,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTaskAsset = `-- name: UpsertTaskAsset :one
INSERT INTO task_assets (
  task_id, asset_key, original_filename, storage_path, file_size, content_type, hash_sha256
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (task_id, asset_key) DO UPDATE SET
  original_filename = EXCLUDED.original_filename,
  storage_path = EXCLUDED.storage_path,
  file_size = EXCLUDED.file_size,
  content_type = EXCLUDED.content_type,
  hash_sha256 = EXCLUDED.hash_sha256,
  updated_at = now()
RETURNING id, task_id, asset_key, original_filename, storage_path, file_size, content_type, hash_sha256, created_at, updated_at
`

type UpsertTaskAssetParams struct {
	TaskID           uuid.UUID `json:"task_id"`
	AssetKey         string    `json:"asset_key"`
	OriginalFilename string    `json:"original_filename"`
	StoragePath      string    `json:"storage_path"`
	FileSize         int64     `json:"file_size"`
	ContentType      *string   `json:"content_type"`
	HashSha256       *string   `json:"hash_sha256"`
}

func (q *Queries) UpsertTaskAsset(ctx context.Context, arg UpsertTaskAssetParams) (TaskAsset, error) {
	row := q.db.QueryRow(ctx, upsertTaskAsset,
		arg.TaskID,
		arg.AssetKey,
		arg.OriginalFilename,
		arg.StoragePath,
		arg.FileSize,
		arg.ContentType,
		arg.HashSha256,
	)
	var i TaskAsset
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AssetKey,
		&i.OriginalFilename,
		&i.StoragePath,
		&i.FileSize,
		&i.ContentType,
		&i.HashSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
