// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  contest_id, slug, title, description, problem_statement_url,
  submission_schema, score_label, higher_is_better, sort_order
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, contest_id, slug, title, description, problem_statement_url, submission_schema, score_label, higher_is_better, sort_order, created_at, updated_at
`

type CreateTaskParams struct {
	ContestID           uuid.UUID `json:"contest_id"`
	Slug                string    `json:"slug"`
	Title               string    `json:"title"`
	Description         *string   `json:"description"`
	ProblemStatementUrl *string   `json:"problem_statement_url"`
	SubmissionSchema    []byte    `json:"submission_schema"`
	ScoreLabel          string    `json:"score_label"`
	HigherIsBetter      bool      `json:"higher_is_better"`
	SortOrder           int32     `json:"sort_order"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ContestID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.ProblemStatementUrl,
		arg.SubmissionSchema,
		arg.ScoreLabel,
		arg.HigherIsBetter,
		arg.SortOrder,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.ProblemStatementUrl,
		&i.SubmissionSchema,
		&i.ScoreLabel,
		&i.HigherIsBetter,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, contest_id, slug, title, description, problem_statement_url, submission_schema, score_label, higher_is_better, sort_order, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.ProblemStatementUrl,
		&i.SubmissionSchema,
		&i.ScoreLabel,
		&i.HigherIsBetter,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByContest = `-- name: ListTasksByContest :many
SELECT id, contest_id, slug, title, description, problem_statement_url, submission_schema, score_label, higher_is_better, sort_order, created_at, updated_at FROM tasks WHERE contest_id = $1 ORDER BY sort_order
`

func (q *Queries) ListTasksByContest(ctx context.Context, contestID uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.ProblemStatementUrl,
			&i.SubmissionSchema,
			&i.ScoreLabel,
			&i.HigherIsBetter,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET
  title = COALESCE($2, title),
  description = COALESCE($3, description),
  problem_statement_url = COALESCE($4, problem_statement_url),
  submission_schema = COALESCE($5, submission_schema),
  score_label = COALESCE($6, score_label),
  higher_is_better = COALESCE($7, higher_is_better),
  sort_order = COALESCE($8, sort_order),
  updated_at = now()
WHERE id = $1
RETURNING id, contest_id, slug, title, description, problem_statement_url, submission_schema, score_label, higher_is_better, sort_order, created_at, updated_at
`

type UpdateTaskParams struct {
	ID                  uuid.UUID `json:"id"`
	Title               *string   `json:"title"`
	Description         *string   `json:"description"`
	ProblemStatementUrl *string   `json:"problem_statement_url"`
	SubmissionSchema    []byte    `json:"submission_schema"`
	ScoreLabel          *string   `json:"score_label"`
	HigherIsBetter      *bool     `json:"higher_is_better"`
	SortOrder           *int32    `json:"sort_order"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ProblemStatementUrl,
		arg.SubmissionSchema,
		arg.ScoreLabel,
		arg.HigherIsBetter,
		arg.SortOrder,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.ProblemStatementUrl,
		&i.SubmissionSchema,
		&i.ScoreLabel,
		&i.HigherIsBetter,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
