// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, full_name, role, student_id, avatar_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, password_hash, full_name, role, student_id, avatar_url, last_visit, created_at, updated_at
`

type CreateUserParams struct {
	Email        string   `json:"email"`
	PasswordHash string   `json:"password_hash"`
	FullName     string   `json:"full_name"`
	Role         UserRole `json:"role"`
	StudentID    *string  `json:"student_id"`
	AvatarUrl    *string  `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
		arg.StudentID,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.StudentID,
		&i.AvatarUrl,
		&i.LastVisit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, role, student_id, avatar_url, last_visit, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.StudentID,
		&i.AvatarUrl,
		&i.LastVisit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, role, student_id, avatar_url, last_visit, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.StudentID,
		&i.AvatarUrl,
		&i.LastVisit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchUserLastVisit = `-- name: TouchUserLastVisit :exec
UPDATE users SET last_visit = now() WHERE id = $1
`

func (q *Queries) TouchUserLastVisit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLastVisit, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET full_name  = COALESCE($2, full_name),
    student_id = COALESCE($3, student_id),
    avatar_url = COALESCE($4, avatar_url),
    updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, full_name, role, student_id, avatar_url, last_visit, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID        uuid.UUID `json:"id"`
	FullName  string    `json:"full_name"`
	StudentID *string   `json:"student_id"`
	AvatarUrl *string   `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FullName,
		arg.StudentID,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.StudentID,
		&i.AvatarUrl,
		&i.LastVisit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
