// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: volunteer_worker_claims.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkerActiveClaims = `-- name: CountWorkerActiveClaims :one
SELECT COUNT(*) FROM volunteer_worker_claims WHERE worker_id = $1
`

func (q *Queries) CountWorkerActiveClaims(ctx context.Context, workerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkerActiveClaims, workerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkerClaim = `-- name: CreateWorkerClaim :one
INSERT INTO volunteer_worker_claims (worker_id, submission_id)
VALUES ($1, $2)
RETURNING id, worker_id, submission_id, claimed_at
`

type CreateWorkerClaimParams struct {
	WorkerID     uuid.UUID `json:"worker_id"`
	SubmissionID uuid.UUID `json:"submission_id"`
}

func (q *Queries) CreateWorkerClaim(ctx context.Context, arg CreateWorkerClaimParams) (VolunteerWorkerClaim, error) {
	row := q.db.QueryRow(ctx, createWorkerClaim, arg.WorkerID, arg.SubmissionID)
	var i VolunteerWorkerClaim
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.SubmissionID,
		&i.ClaimedAt,
	)
	return i, err
}

const deleteWorkerClaim = `-- name: DeleteWorkerClaim :exec
DELETE FROM volunteer_worker_claims
WHERE worker_id = $1 AND submission_id = $2
`

type DeleteWorkerClaimParams struct {
	WorkerID     uuid.UUID `json:"worker_id"`
	SubmissionID uuid.UUID `json:"submission_id"`
}

func (q *Queries) DeleteWorkerClaim(ctx context.Context, arg DeleteWorkerClaimParams) error {
	_, err := q.db.Exec(ctx, deleteWorkerClaim, arg.WorkerID, arg.SubmissionID)
	return err
}

const getWorkerClaimBySubmission = `-- name: GetWorkerClaimBySubmission :one
SELECT id, worker_id, submission_id, claimed_at FROM volunteer_worker_claims WHERE submission_id = $1
`

func (q *Queries) GetWorkerClaimBySubmission(ctx context.Context, submissionID uuid.UUID) (VolunteerWorkerClaim, error) {
	row := q.db.QueryRow(ctx, getWorkerClaimBySubmission, submissionID)
	var i VolunteerWorkerClaim
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.SubmissionID,
		&i.ClaimedAt,
	)
	return i, err
}

const listStaleWorkerClaims2 = `-- name: ListStaleWorkerClaims2 :many
SELECT c.id, c.worker_id, c.submission_id, c.claimed_at, w.id AS wid
FROM volunteer_worker_claims c
JOIN volunteer_workers w ON w.id = c.worker_id
WHERE c.claimed_at < $1
`

type ListStaleWorkerClaims2Row struct {
	ID           uuid.UUID          `json:"id"`
	WorkerID     uuid.UUID          `json:"worker_id"`
	SubmissionID uuid.UUID          `json:"submission_id"`
	ClaimedAt    pgtype.Timestamptz `json:"claimed_at"`
	Wid          uuid.UUID          `json:"wid"`
}

func (q *Queries) ListStaleWorkerClaims2(ctx context.Context, claimedAt pgtype.Timestamptz) ([]ListStaleWorkerClaims2Row, error) {
	rows, err := q.db.Query(ctx, listStaleWorkerClaims2, claimedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleWorkerClaims2Row
	for rows.Next() {
		var i ListStaleWorkerClaims2Row
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.SubmissionID,
			&i.ClaimedAt,
			&i.Wid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
