// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: volunteer_workers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveVolunteerWorker = `-- name: ApproveVolunteerWorker :one
UPDATE volunteer_workers
SET status      = 'active',
    api_token   = $2,
    approved_at = now(),
    updated_at  = now()
WHERE id = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, current_job_id, job_claimed_at, jobs_completed, jobs_failed, approved_at, created_at, updated_at
`

type ApproveVolunteerWorkerParams struct {
	ID       uuid.UUID `json:"id"`
	ApiToken *string   `json:"api_token"`
}

func (q *Queries) ApproveVolunteerWorker(ctx context.Context, arg ApproveVolunteerWorkerParams) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, approveVolunteerWorker, arg.ID, arg.ApiToken)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.CurrentJobID,
		&i.JobClaimedAt,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimWorkerJob = `-- name: ClaimWorkerJob :one
UPDATE volunteer_workers
SET current_job_id = $2,
    job_claimed_at = now(),
    updated_at     = now()
WHERE api_token = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, current_job_id, job_claimed_at, jobs_completed, jobs_failed, approved_at, created_at, updated_at
`

type ClaimWorkerJobParams struct {
	ApiToken     *string     `json:"api_token"`
	CurrentJobID pgtype.UUID `json:"current_job_id"`
}

func (q *Queries) ClaimWorkerJob(ctx context.Context, arg ClaimWorkerJobParams) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, claimWorkerJob, arg.ApiToken, arg.CurrentJobID)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.CurrentJobID,
		&i.JobClaimedAt,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeWorkerJob = `-- name: CompleteWorkerJob :one
UPDATE volunteer_workers
SET current_job_id = NULL,
    job_claimed_at = NULL,
    jobs_completed = jobs_completed + 1,
    last_seen_at   = now(),
    updated_at     = now()
WHERE api_token = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, current_job_id, job_claimed_at, jobs_completed, jobs_failed, approved_at, created_at, updated_at
`

func (q *Queries) CompleteWorkerJob(ctx context.Context, apiToken *string) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, completeWorkerJob, apiToken)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.CurrentJobID,
		&i.JobClaimedAt,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVolunteerWorker = `-- name: CreateVolunteerWorker :one
INSERT INTO volunteer_workers (user_id, display_name, capabilities)
VALUES ($1, $2, $3)
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, current_job_id, job_claimed_at, jobs_completed, jobs_failed, approved_at, created_at, updated_at
`

type CreateVolunteerWorkerParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	DisplayName  string      `json:"display_name"`
	Capabilities []byte      `json:"capabilities"`
}

func (q *Queries) CreateVolunteerWorker(ctx context.Context, arg CreateVolunteerWorkerParams) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, createVolunteerWorker, arg.UserID, arg.DisplayName, arg.Capabilities)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.CurrentJobID,
		&i.JobClaimedAt,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateVolunteerWorker = `-- name: DeactivateVolunteerWorker :one
UPDATE volunteer_workers
SET status     = 'inactive',
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, current_job_id, job_claimed_at, jobs_completed, jobs_failed, approved_at, created_at, updated_at
`

func (q *Queries) DeactivateVolunteerWorker(ctx context.Context, id uuid.UUID) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, deactivateVolunteerWorker, id)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.CurrentJobID,
		&i.JobClaimedAt,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVolunteerWorker = `-- name: DeleteVolunteerWorker :exec
DELETE FROM volunteer_workers WHERE id = $1
`

func (q *Queries) DeleteVolunteerWorker(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVolunteerWorker, id)
	return err
}

const failWorkerJob = `-- name: FailWorkerJob :one
UPDATE volunteer_workers
SET current_job_id = NULL,
    job_claimed_at = NULL,
    jobs_failed    = jobs_failed + 1,
    last_seen_at   = now(),
    updated_at     = now()
WHERE api_token = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, current_job_id, job_claimed_at, jobs_completed, jobs_failed, approved_at, created_at, updated_at
`

func (q *Queries) FailWorkerJob(ctx context.Context, apiToken *string) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, failWorkerJob, apiToken)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.CurrentJobID,
		&i.JobClaimedAt,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const forceReleaseWorkerJob = `-- name: ForceReleaseWorkerJob :one
UPDATE volunteer_workers
SET current_job_id = NULL,
    job_claimed_at = NULL,
    jobs_failed    = jobs_failed + 1,
    updated_at     = now()
WHERE id = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, current_job_id, job_claimed_at, jobs_completed, jobs_failed, approved_at, created_at, updated_at
`

func (q *Queries) ForceReleaseWorkerJob(ctx context.Context, id uuid.UUID) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, forceReleaseWorkerJob, id)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.CurrentJobID,
		&i.JobClaimedAt,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVolunteerWorkerByID = `-- name: GetVolunteerWorkerByID :one
SELECT id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, current_job_id, job_claimed_at, jobs_completed, jobs_failed, approved_at, created_at, updated_at FROM volunteer_workers WHERE id = $1
`

func (q *Queries) GetVolunteerWorkerByID(ctx context.Context, id uuid.UUID) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, getVolunteerWorkerByID, id)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.CurrentJobID,
		&i.JobClaimedAt,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVolunteerWorkerByToken = `-- name: GetVolunteerWorkerByToken :one
SELECT id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, current_job_id, job_claimed_at, jobs_completed, jobs_failed, approved_at, created_at, updated_at FROM volunteer_workers
WHERE api_token = $1 AND status = 'active'
LIMIT 1
`

func (q *Queries) GetVolunteerWorkerByToken(ctx context.Context, apiToken *string) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, getVolunteerWorkerByToken, apiToken)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.CurrentJobID,
		&i.JobClaimedAt,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaleWorkerClaims = `-- name: ListStaleWorkerClaims :many
SELECT id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, current_job_id, job_claimed_at, jobs_completed, jobs_failed, approved_at, created_at, updated_at FROM volunteer_workers
WHERE current_job_id IS NOT NULL
  AND job_claimed_at < $1
`

func (q *Queries) ListStaleWorkerClaims(ctx context.Context, jobClaimedAt pgtype.Timestamptz) ([]VolunteerWorker, error) {
	rows, err := q.db.Query(ctx, listStaleWorkerClaims, jobClaimedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VolunteerWorker
	for rows.Next() {
		var i VolunteerWorker
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Status,
			&i.ApiToken,
			&i.Capabilities,
			&i.LastSeenAt,
			&i.CpuUsage,
			&i.RamUsage,
			&i.CurrentJobID,
			&i.JobClaimedAt,
			&i.JobsCompleted,
			&i.JobsFailed,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolunteerWorkers = `-- name: ListVolunteerWorkers :many
SELECT id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, current_job_id, job_claimed_at, jobs_completed, jobs_failed, approved_at, created_at, updated_at FROM volunteer_workers
ORDER BY created_at DESC
`

func (q *Queries) ListVolunteerWorkers(ctx context.Context) ([]VolunteerWorker, error) {
	rows, err := q.db.Query(ctx, listVolunteerWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VolunteerWorker
	for rows.Next() {
		var i VolunteerWorker
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Status,
			&i.ApiToken,
			&i.Capabilities,
			&i.LastSeenAt,
			&i.CpuUsage,
			&i.RamUsage,
			&i.CurrentJobID,
			&i.JobClaimedAt,
			&i.JobsCompleted,
			&i.JobsFailed,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectVolunteerWorker = `-- name: RejectVolunteerWorker :one
UPDATE volunteer_workers
SET status     = 'rejected',
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, current_job_id, job_claimed_at, jobs_completed, jobs_failed, approved_at, created_at, updated_at
`

func (q *Queries) RejectVolunteerWorker(ctx context.Context, id uuid.UUID) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, rejectVolunteerWorker, id)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.CurrentJobID,
		&i.JobClaimedAt,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkerHeartbeat = `-- name: UpdateWorkerHeartbeat :one
UPDATE volunteer_workers
SET last_seen_at = now(),
    cpu_usage    = $2,
    ram_usage    = $3,
    updated_at   = now()
WHERE api_token = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, current_job_id, job_claimed_at, jobs_completed, jobs_failed, approved_at, created_at, updated_at
`

type UpdateWorkerHeartbeatParams struct {
	ApiToken *string `json:"api_token"`
	CpuUsage *int16  `json:"cpu_usage"`
	RamUsage *int16  `json:"ram_usage"`
}

func (q *Queries) UpdateWorkerHeartbeat(ctx context.Context, arg UpdateWorkerHeartbeatParams) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, updateWorkerHeartbeat, arg.ApiToken, arg.CpuUsage, arg.RamUsage)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.CurrentJobID,
		&i.JobClaimedAt,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
