// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: volunteer_workers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveVolunteerWorker = `-- name: ApproveVolunteerWorker :one
UPDATE volunteer_workers
SET status      = 'active',
    api_token   = $2,
    approved_at = now(),
    updated_at  = now()
WHERE id = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

type ApproveVolunteerWorkerParams struct {
	ID       uuid.UUID `json:"id"`
	ApiToken *string   `json:"api_token"`
}

func (q *Queries) ApproveVolunteerWorker(ctx context.Context, arg ApproveVolunteerWorkerParams) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, approveVolunteerWorker, arg.ID, arg.ApiToken)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const countWorkerActiveClaimsByKind = `-- name: CountWorkerActiveClaimsByKind :one
SELECT
    COUNT(*) FILTER (WHERE s.is_final = false)::int AS output_claims,
    COUNT(*) FILTER (WHERE s.is_final = true)::int AS inference_claims
FROM volunteer_worker_claims c
JOIN submissions s ON s.id = c.submission_id
WHERE c.worker_id = $1
`

type CountWorkerActiveClaimsByKindRow struct {
	OutputClaims    int32 `json:"output_claims"`
	InferenceClaims int32 `json:"inference_claims"`
}

func (q *Queries) CountWorkerActiveClaimsByKind(ctx context.Context, workerID uuid.UUID) (CountWorkerActiveClaimsByKindRow, error) {
	row := q.db.QueryRow(ctx, countWorkerActiveClaimsByKind, workerID)
	var i CountWorkerActiveClaimsByKindRow
	err := row.Scan(&i.OutputClaims, &i.InferenceClaims)
	return i, err
}

const createVolunteerWorker = `-- name: CreateVolunteerWorker :one
INSERT INTO volunteer_workers (user_id, display_name, capabilities, max_workers)
VALUES ($1, $2, $3::text::jsonb, $4)
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

type CreateVolunteerWorkerParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	DisplayName string      `json:"display_name"`
	Column3     string      `json:"column_3"`
	MaxWorkers  int16       `json:"max_workers"`
}

func (q *Queries) CreateVolunteerWorker(ctx context.Context, arg CreateVolunteerWorkerParams) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, createVolunteerWorker,
		arg.UserID,
		arg.DisplayName,
		arg.Column3,
		arg.MaxWorkers,
	)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const createWorkerClaimWithFinish = `-- name: CreateWorkerClaimWithFinish :one
INSERT INTO volunteer_worker_claims (
    worker_id, submission_id, predicted_finish_at, lease_expires_at, last_heartbeat_at
)
VALUES ($1, $2, $3, $4, now())
RETURNING id, worker_id, submission_id, claimed_at, predicted_finish_at, attempt_id, lease_expires_at, last_heartbeat_at
`

type CreateWorkerClaimWithFinishParams struct {
	WorkerID          uuid.UUID          `json:"worker_id"`
	SubmissionID      uuid.UUID          `json:"submission_id"`
	PredictedFinishAt pgtype.Timestamptz `json:"predicted_finish_at"`
	LeaseExpiresAt    pgtype.Timestamptz `json:"lease_expires_at"`
}

// Creates a claim with lease + predicted finish time for scheduling.
func (q *Queries) CreateWorkerClaimWithFinish(ctx context.Context, arg CreateWorkerClaimWithFinishParams) (VolunteerWorkerClaim, error) {
	row := q.db.QueryRow(ctx, createWorkerClaimWithFinish,
		arg.WorkerID,
		arg.SubmissionID,
		arg.PredictedFinishAt,
		arg.LeaseExpiresAt,
	)
	var i VolunteerWorkerClaim
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.SubmissionID,
		&i.ClaimedAt,
		&i.PredictedFinishAt,
		&i.AttemptID,
		&i.LeaseExpiresAt,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const deactivateVolunteerWorker = `-- name: DeactivateVolunteerWorker :one
UPDATE volunteer_workers
SET status     = 'inactive',
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

func (q *Queries) DeactivateVolunteerWorker(ctx context.Context, id uuid.UUID) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, deactivateVolunteerWorker, id)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const deleteStaleWorkerClaims = `-- name: DeleteStaleWorkerClaims :many
DELETE FROM volunteer_worker_claims
USING submissions s
WHERE volunteer_worker_claims.submission_id = s.id
  AND (
    volunteer_worker_claims.lease_expires_at < now()
    OR (s.is_final = false AND volunteer_worker_claims.claimed_at < $1)
    OR (s.is_final = true  AND volunteer_worker_claims.claimed_at < $2)
  )
RETURNING volunteer_worker_claims.worker_id, volunteer_worker_claims.submission_id, volunteer_worker_claims.attempt_id
`

type DeleteStaleWorkerClaimsParams struct {
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
	ClaimedAt_2 pgtype.Timestamptz `json:"claimed_at_2"`
}

type DeleteStaleWorkerClaimsRow struct {
	WorkerID     uuid.UUID `json:"worker_id"`
	SubmissionID uuid.UUID `json:"submission_id"`
	AttemptID    uuid.UUID `json:"attempt_id"`
}

// Batch delete stale claims in one query; RETURNING for re-enqueue loop.
func (q *Queries) DeleteStaleWorkerClaims(ctx context.Context, arg DeleteStaleWorkerClaimsParams) ([]DeleteStaleWorkerClaimsRow, error) {
	rows, err := q.db.Query(ctx, deleteStaleWorkerClaims, arg.ClaimedAt, arg.ClaimedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteStaleWorkerClaimsRow
	for rows.Next() {
		var i DeleteStaleWorkerClaimsRow
		if err := rows.Scan(&i.WorkerID, &i.SubmissionID, &i.AttemptID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVolunteerWorker = `-- name: DeleteVolunteerWorker :exec
DELETE FROM volunteer_workers WHERE id = $1
`

func (q *Queries) DeleteVolunteerWorker(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVolunteerWorker, id)
	return err
}

const getAllActiveWorkersWithEarliestAvailable = `-- name: GetAllActiveWorkersWithEarliestAvailable :many

SELECT
    w.id,
    w.capabilities,
    w.max_workers,
    COUNT(*) FILTER (WHERE s.is_final = false)::int AS output_claims,
    COUNT(*) FILTER (WHERE s.is_final = true)::int AS inference_claims,
    CASE
        WHEN COALESCE((w.capabilities->>'exclusive_inference')::boolean, false) = true
             AND COUNT(c.id) > 0
        THEN MIN(COALESCE(c.predicted_finish_at, now() + interval '20 minutes'))
        WHEN COUNT(c.id) < w.max_workers THEN now()
        ELSE MIN(COALESCE(c.predicted_finish_at, now() + interval '20 minutes'))
    END AS earliest_available_at
FROM volunteer_workers w
LEFT JOIN volunteer_worker_claims c ON c.worker_id = w.id
LEFT JOIN submissions s ON s.id = c.submission_id
WHERE w.status = 'active'
GROUP BY w.id, w.capabilities, w.max_workers
`

type GetAllActiveWorkersWithEarliestAvailableRow struct {
	ID                  uuid.UUID   `json:"id"`
	Capabilities        []byte      `json:"capabilities"`
	MaxWorkers          int16       `json:"max_workers"`
	OutputClaims        int32       `json:"output_claims"`
	InferenceClaims     int32       `json:"inference_claims"`
	EarliestAvailableAt interface{} `json:"earliest_available_at"`
}

// ── Global Best Finish Time Scheduling ──────────────────────────────────────
// Returns all active workers and when they will next have a free slot.
// earliest_available_at = now() if worker has free capacity, else min(predicted_finish_at).
func (q *Queries) GetAllActiveWorkersWithEarliestAvailable(ctx context.Context) ([]GetAllActiveWorkersWithEarliestAvailableRow, error) {
	rows, err := q.db.Query(ctx, getAllActiveWorkersWithEarliestAvailable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveWorkersWithEarliestAvailableRow
	for rows.Next() {
		var i GetAllActiveWorkersWithEarliestAvailableRow
		if err := rows.Scan(
			&i.ID,
			&i.Capabilities,
			&i.MaxWorkers,
			&i.OutputClaims,
			&i.InferenceClaims,
			&i.EarliestAvailableAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVolunteerWorkerByID = `-- name: GetVolunteerWorkerByID :one
SELECT id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers FROM volunteer_workers WHERE id = $1
`

func (q *Queries) GetVolunteerWorkerByID(ctx context.Context, id uuid.UUID) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, getVolunteerWorkerByID, id)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const getVolunteerWorkerByToken = `-- name: GetVolunteerWorkerByToken :one
SELECT id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers FROM volunteer_workers
WHERE api_token = $1 AND status = 'active'
LIMIT 1
`

func (q *Queries) GetVolunteerWorkerByToken(ctx context.Context, apiToken *string) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, getVolunteerWorkerByToken, apiToken)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const incrementWorkerCompleted = `-- name: IncrementWorkerCompleted :one
UPDATE volunteer_workers
SET jobs_completed = jobs_completed + 1,
    last_seen_at   = now(),
    updated_at     = now()
WHERE api_token = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

func (q *Queries) IncrementWorkerCompleted(ctx context.Context, apiToken *string) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, incrementWorkerCompleted, apiToken)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const incrementWorkerFailed = `-- name: IncrementWorkerFailed :one
UPDATE volunteer_workers
SET jobs_failed = jobs_failed + 1,
    last_seen_at = now(),
    updated_at   = now()
WHERE api_token = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

func (q *Queries) IncrementWorkerFailed(ctx context.Context, apiToken *string) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, incrementWorkerFailed, apiToken)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const incrementWorkerFailedByID = `-- name: IncrementWorkerFailedByID :one
UPDATE volunteer_workers
SET jobs_failed = jobs_failed + 1,
    updated_at  = now()
WHERE id = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

func (q *Queries) IncrementWorkerFailedByID(ctx context.Context, id uuid.UUID) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, incrementWorkerFailedByID, id)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const listVolunteerWorkers = `-- name: ListVolunteerWorkers :many
SELECT id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers FROM volunteer_workers
ORDER BY created_at DESC
`

func (q *Queries) ListVolunteerWorkers(ctx context.Context) ([]VolunteerWorker, error) {
	rows, err := q.db.Query(ctx, listVolunteerWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VolunteerWorker
	for rows.Next() {
		var i VolunteerWorker
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Status,
			&i.ApiToken,
			&i.Capabilities,
			&i.LastSeenAt,
			&i.CpuUsage,
			&i.RamUsage,
			&i.JobsCompleted,
			&i.JobsFailed,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxWorkers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerActiveClaimCounts = `-- name: ListWorkerActiveClaimCounts :many

SELECT worker_id, COUNT(*)::int AS active_claims
FROM volunteer_worker_claims
GROUP BY worker_id
`

type ListWorkerActiveClaimCountsRow struct {
	WorkerID     uuid.UUID `json:"worker_id"`
	ActiveClaims int32     `json:"active_claims"`
}

// ── Engineering optimizations (Phase 06) ────────────────────────────────────
// Single aggregation to replace N+1 CountWorkerActiveClaims in AdminList.
func (q *Queries) ListWorkerActiveClaimCounts(ctx context.Context) ([]ListWorkerActiveClaimCountsRow, error) {
	rows, err := q.db.Query(ctx, listWorkerActiveClaimCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkerActiveClaimCountsRow
	for rows.Next() {
		var i ListWorkerActiveClaimCountsRow
		if err := rows.Scan(&i.WorkerID, &i.ActiveClaims); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectVolunteerWorker = `-- name: RejectVolunteerWorker :one
UPDATE volunteer_workers
SET status     = 'rejected',
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

func (q *Queries) RejectVolunteerWorker(ctx context.Context, id uuid.UUID) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, rejectVolunteerWorker, id)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const renewWorkerClaimLease = `-- name: RenewWorkerClaimLease :one
UPDATE volunteer_worker_claims
SET lease_expires_at = $3,
    last_heartbeat_at = now()
WHERE submission_id = $1
  AND attempt_id = $2
RETURNING id, worker_id, submission_id, claimed_at, predicted_finish_at, attempt_id, lease_expires_at, last_heartbeat_at
`

type RenewWorkerClaimLeaseParams struct {
	SubmissionID   uuid.UUID          `json:"submission_id"`
	AttemptID      uuid.UUID          `json:"attempt_id"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) RenewWorkerClaimLease(ctx context.Context, arg RenewWorkerClaimLeaseParams) (VolunteerWorkerClaim, error) {
	row := q.db.QueryRow(ctx, renewWorkerClaimLease, arg.SubmissionID, arg.AttemptID, arg.LeaseExpiresAt)
	var i VolunteerWorkerClaim
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.SubmissionID,
		&i.ClaimedAt,
		&i.PredictedFinishAt,
		&i.AttemptID,
		&i.LeaseExpiresAt,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const updateWorkerHeartbeat = `-- name: UpdateWorkerHeartbeat :one
UPDATE volunteer_workers
SET last_seen_at = now(),
    cpu_usage    = $2,
    ram_usage    = $3,
    updated_at   = now()
WHERE api_token = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

type UpdateWorkerHeartbeatParams struct {
	ApiToken *string `json:"api_token"`
	CpuUsage *int16  `json:"cpu_usage"`
	RamUsage *int16  `json:"ram_usage"`
}

func (q *Queries) UpdateWorkerHeartbeat(ctx context.Context, arg UpdateWorkerHeartbeatParams) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, updateWorkerHeartbeat, arg.ApiToken, arg.CpuUsage, arg.RamUsage)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const workerIsAtCapacity = `-- name: WorkerIsAtCapacity :one
SELECT COUNT(*) >= $2 AS at_capacity
FROM (
    SELECT 1 FROM volunteer_worker_claims WHERE worker_id = $1 LIMIT $2
) sub
`

type WorkerIsAtCapacityParams struct {
	WorkerID uuid.UUID   `json:"worker_id"`
	Column2  interface{} `json:"column_2"`
}

// Bounded check: stops scanning after max_workers rows found.
// Returns true when worker already has max_workers active claims.
func (q *Queries) WorkerIsAtCapacity(ctx context.Context, arg WorkerIsAtCapacityParams) (bool, error) {
	row := q.db.QueryRow(ctx, workerIsAtCapacity, arg.WorkerID, arg.Column2)
	var at_capacity bool
	err := row.Scan(&at_capacity)
	return at_capacity, err
}
