// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: volunteer_workers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveVolunteerWorker = `-- name: ApproveVolunteerWorker :one
UPDATE volunteer_workers
SET status      = 'active',
    api_token   = $2,
    approved_at = now(),
    updated_at  = now()
WHERE id = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

type ApproveVolunteerWorkerParams struct {
	ID       uuid.UUID `json:"id"`
	ApiToken *string   `json:"api_token"`
}

func (q *Queries) ApproveVolunteerWorker(ctx context.Context, arg ApproveVolunteerWorkerParams) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, approveVolunteerWorker, arg.ID, arg.ApiToken)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const createVolunteerWorker = `-- name: CreateVolunteerWorker :one
INSERT INTO volunteer_workers (user_id, display_name, capabilities, max_workers)
VALUES ($1, $2, $3::text::jsonb, $4)
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

type CreateVolunteerWorkerParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	DisplayName string      `json:"display_name"`
	Column3     string      `json:"column_3"`
	MaxWorkers  int16       `json:"max_workers"`
}

func (q *Queries) CreateVolunteerWorker(ctx context.Context, arg CreateVolunteerWorkerParams) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, createVolunteerWorker,
		arg.UserID,
		arg.DisplayName,
		arg.Column3,
		arg.MaxWorkers,
	)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const deactivateVolunteerWorker = `-- name: DeactivateVolunteerWorker :one
UPDATE volunteer_workers
SET status     = 'inactive',
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

func (q *Queries) DeactivateVolunteerWorker(ctx context.Context, id uuid.UUID) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, deactivateVolunteerWorker, id)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const deleteStaleWorkerClaims = `-- name: DeleteStaleWorkerClaims :many
DELETE FROM volunteer_worker_claims
WHERE claimed_at < $1
RETURNING worker_id, submission_id
`

type DeleteStaleWorkerClaimsRow struct {
	WorkerID     uuid.UUID `json:"worker_id"`
	SubmissionID uuid.UUID `json:"submission_id"`
}

// Batch delete all stale claims in one query; RETURNING for re-enqueue loop.
func (q *Queries) DeleteStaleWorkerClaims(ctx context.Context, claimedAt pgtype.Timestamptz) ([]DeleteStaleWorkerClaimsRow, error) {
	rows, err := q.db.Query(ctx, deleteStaleWorkerClaims, claimedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteStaleWorkerClaimsRow
	for rows.Next() {
		var i DeleteStaleWorkerClaimsRow
		if err := rows.Scan(&i.WorkerID, &i.SubmissionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVolunteerWorker = `-- name: DeleteVolunteerWorker :exec
DELETE FROM volunteer_workers WHERE id = $1
`

func (q *Queries) DeleteVolunteerWorker(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVolunteerWorker, id)
	return err
}

const getVolunteerWorkerByID = `-- name: GetVolunteerWorkerByID :one
SELECT id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers FROM volunteer_workers WHERE id = $1
`

func (q *Queries) GetVolunteerWorkerByID(ctx context.Context, id uuid.UUID) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, getVolunteerWorkerByID, id)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const getVolunteerWorkerByToken = `-- name: GetVolunteerWorkerByToken :one
SELECT id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers FROM volunteer_workers
WHERE api_token = $1 AND status = 'active'
LIMIT 1
`

func (q *Queries) GetVolunteerWorkerByToken(ctx context.Context, apiToken *string) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, getVolunteerWorkerByToken, apiToken)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const incrementWorkerCompleted = `-- name: IncrementWorkerCompleted :one
UPDATE volunteer_workers
SET jobs_completed = jobs_completed + 1,
    last_seen_at   = now(),
    updated_at     = now()
WHERE api_token = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

func (q *Queries) IncrementWorkerCompleted(ctx context.Context, apiToken *string) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, incrementWorkerCompleted, apiToken)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const incrementWorkerFailed = `-- name: IncrementWorkerFailed :one
UPDATE volunteer_workers
SET jobs_failed = jobs_failed + 1,
    last_seen_at = now(),
    updated_at   = now()
WHERE api_token = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

func (q *Queries) IncrementWorkerFailed(ctx context.Context, apiToken *string) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, incrementWorkerFailed, apiToken)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const incrementWorkerFailedByID = `-- name: IncrementWorkerFailedByID :one
UPDATE volunteer_workers
SET jobs_failed = jobs_failed + 1,
    updated_at  = now()
WHERE id = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

func (q *Queries) IncrementWorkerFailedByID(ctx context.Context, id uuid.UUID) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, incrementWorkerFailedByID, id)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const listVolunteerWorkers = `-- name: ListVolunteerWorkers :many
SELECT id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers FROM volunteer_workers
ORDER BY created_at DESC
`

func (q *Queries) ListVolunteerWorkers(ctx context.Context) ([]VolunteerWorker, error) {
	rows, err := q.db.Query(ctx, listVolunteerWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VolunteerWorker
	for rows.Next() {
		var i VolunteerWorker
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Status,
			&i.ApiToken,
			&i.Capabilities,
			&i.LastSeenAt,
			&i.CpuUsage,
			&i.RamUsage,
			&i.JobsCompleted,
			&i.JobsFailed,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxWorkers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerActiveClaimCounts = `-- name: ListWorkerActiveClaimCounts :many

SELECT worker_id, COUNT(*)::int AS active_claims
FROM volunteer_worker_claims
GROUP BY worker_id
`

type ListWorkerActiveClaimCountsRow struct {
	WorkerID     uuid.UUID `json:"worker_id"`
	ActiveClaims int32     `json:"active_claims"`
}

// ── Engineering optimizations (Phase 06) ────────────────────────────────────
// Single aggregation to replace N+1 CountWorkerActiveClaims in AdminList.
func (q *Queries) ListWorkerActiveClaimCounts(ctx context.Context) ([]ListWorkerActiveClaimCountsRow, error) {
	rows, err := q.db.Query(ctx, listWorkerActiveClaimCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkerActiveClaimCountsRow
	for rows.Next() {
		var i ListWorkerActiveClaimCountsRow
		if err := rows.Scan(&i.WorkerID, &i.ActiveClaims); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectVolunteerWorker = `-- name: RejectVolunteerWorker :one
UPDATE volunteer_workers
SET status     = 'rejected',
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

func (q *Queries) RejectVolunteerWorker(ctx context.Context, id uuid.UUID) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, rejectVolunteerWorker, id)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const updateWorkerHeartbeat = `-- name: UpdateWorkerHeartbeat :one
UPDATE volunteer_workers
SET last_seen_at = now(),
    cpu_usage    = $2,
    ram_usage    = $3,
    updated_at   = now()
WHERE api_token = $1
RETURNING id, user_id, display_name, status, api_token, capabilities, last_seen_at, cpu_usage, ram_usage, jobs_completed, jobs_failed, approved_at, created_at, updated_at, max_workers
`

type UpdateWorkerHeartbeatParams struct {
	ApiToken *string `json:"api_token"`
	CpuUsage *int16  `json:"cpu_usage"`
	RamUsage *int16  `json:"ram_usage"`
}

func (q *Queries) UpdateWorkerHeartbeat(ctx context.Context, arg UpdateWorkerHeartbeatParams) (VolunteerWorker, error) {
	row := q.db.QueryRow(ctx, updateWorkerHeartbeat, arg.ApiToken, arg.CpuUsage, arg.RamUsage)
	var i VolunteerWorker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.ApiToken,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CpuUsage,
		&i.RamUsage,
		&i.JobsCompleted,
		&i.JobsFailed,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxWorkers,
	)
	return i, err
}

const workerIsAtCapacity = `-- name: WorkerIsAtCapacity :one
SELECT COUNT(*) >= $2 AS at_capacity
FROM (
    SELECT 1 FROM volunteer_worker_claims WHERE worker_id = $1 LIMIT $2
) sub
`

type WorkerIsAtCapacityParams struct {
	WorkerID uuid.UUID   `json:"worker_id"`
	Column2  interface{} `json:"column_2"`
}

// Bounded check: stops scanning after max_workers rows found.
// Returns true when worker already has max_workers active claims.
func (q *Queries) WorkerIsAtCapacity(ctx context.Context, arg WorkerIsAtCapacityParams) (bool, error) {
	row := q.db.QueryRow(ctx, workerIsAtCapacity, arg.WorkerID, arg.Column2)
	var at_capacity bool
	err := row.Scan(&at_capacity)
	return at_capacity, err
}
